### ISSUE TITLE
Additional maintainer(s) wanted

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/git-secret#100]
## Call for maintainers
Right now I don't have much time to support this project. Sorry.

But I do not want to leave it unmaintained, since it is working fine, but still needs some major improvements. And I love using it already.

I would love to contribute to this project in the future, but right now it requires someone to care for it. I would post some advertising around the web, so feel free to contact me!

## Required experience

- Solid `bash`
- Solid `git`
- Some `gpg` (it is pretty easy to use, actually)
- Some `docker` (we are running tests inside `docker` containers)
- Some general `DevOps` (since we use a lot of automation: `deb` and `rpm` generation, etc)
- Some testing (tests are still in `bash`)

## Time

I expect that 6 hours a week would be sufficient.

**Comment by Gitcat711** [comment]
So I have experience in some  -
Bash
git 
Will I be able to help?

**Comment by joshrabinowitz** [comment]
Hello @Gitcat711 ! The most pressing issues are 
#120, regarding the deploy process, and
#135 , regarding spaces in pathnames

There are pretty extensive notes on each issue. Your input is welcome and appreciated! Feel free to ask any follow-up questions in the issues themselve.

**Comment by joshrabinowitz** [comment]
@Gitcat711 also let me know if you need help getting your dev environment set up, or if you want to take on an easier issue than the ones above.

**Comment by joshrabinowitz** [comment]
It looks like https://github.com/sobolevn/git-secret/pull/184 fixes #120 
It would be great if someone would fix https://github.com/sobolevn/git-secret/issues/179

**Comment by simbo1905** [comment]
I have got a fix for #179 that I am testing locally (the test ci suite takes a loooooong time locally). 

@sobolevn @joshrabinowitz  Do you mind making me a collaborator so that I can label issues that are blocking the 0.2.4 release so that we can focus on that?

**Comment by sobolevn** [comment]
I totally do not mind! 
Welcome!

**Comment by Gitcat711** [comment]
Hello Josh,
I was burned up due to some other work. So how I can start from scratch and
contribute. I am sorry to let you down, but I ain't no ninja coder.  Let's
see how I can create impact. Any roadmap for environment setup?

**Comment by simbo1905** [comment]
@Gitcat711 the ci build and release is now fixed so its easier to contribute bug fixes. there are also some documentation issues. take a look at the open issues and see if there are any you would like to spend some time on. take a read of contributing.md, fork, fix, send a PR, and watch the travis build to see if it passes and fix as needed 👍🏻

**Comment by joshrabinowitz** [comment]
@Gitcat711 #https://github.com/sobolevn/git-secret/issues/202#issuecomment-396640027 (can someone write a PR to exhibit the problem?) would be a good place to start

**Comment by joshrabinowitz** [comment]
It would also be great if someone would implement https://github.com/sobolevn/git-secret/blob/master/RFC/RFC001.md which would fix interoperation issues between versions of GPG

**Comment by sobolevn** [comment]
@apallennz welcome! 

I am pretty sure there are some things you can help us with.
I would suggest to start from the documentation updates:

- just read through the existing docs and point out parts that are not easily understandable for you
- create new issues with "documentation" badge
- together we will try to fix the bad parts

You can start from `CONTRIBUTING.md` and `README.md` moving to the `man` files later on.
This way you will get familiar with the project and help us to improve the docs.
How does it sound to you?

**Comment by apallennz** [comment]
Sounds good, thanks for responding

**Comment by apallennz** [comment]
so, question
what private data would you be wanting to store inside a git repo?

**Comment by joshrabinowitz** [comment]
@apallennz some examples of secrets you might want to store in a git-secret repo include "This includes SSH keys, SSL private keys, API keys, passwords, and client secrets." <https://embeddedartistry.com/blog/2018/3/15/safely-storing-secrets-in-git>

**Comment by joshrabinowitz** [comment]
We could also use maintainers to help us submit packages to EPEL/Fedora and Debian: 
See #312, #315.
