### ISSUE TITLE
Merge ci folders into one

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/git-secret#108]
Can these folders be merged?

<img width="486" alt="2017-09-27 21 29 39" src="https://user-images.githubusercontent.com/4660275/30930711-2daf6aec-a3cb-11e7-90eb-551b1a319c12.png">

I guess existing `.ci/` folder is fine, isn't it?

**Comment by hurricanehrndz** [comment]
@sobolevn 

I'm not familiar in regards to running macOS ci tests on mac, so I was not comfortable making any edits to that folder. Additionally, the original ci folder is no longer needed for any actual test on Linux. Do you actually use the after_deploy script? I can try and merge them together and see what happens. I think got the gist of it. The old .docker folder needs to be dropped, no longer needed.

**Comment by hurricanehrndz** [comment]
Sorry didn't mean to close.

**Comment by sobolevn** [comment]
Sounds good to me, remove everything that is no longer needed.

**Comment by hurricanehrndz** [comment]
What is the purpose of your dockerfiles?

**Comment by hurricanehrndz** [comment]
ci folders have been merged, the docker folder was deleted and additionally travis test for linux was moved to test kitchen please see [here](https://travis-ci.org/hurricanehrndz/git-secret/jobs/280652621).
Deployment has been broken, I believe they can be re-added to the matrix with the following code:

```
     - os: linux
       env: GITSECRET_DIST="deb"
       sudo: required
     - os: linux
       env: GITSECRET_DIST="rpm"
       sudo: required
```

**Comment by hurricanehrndz** [comment]
All test have fixed except macOS. Can you please look into this?

**Comment by sobolevn** [comment]
@hurricanehrndz I guess it happens because of how `brew` works.

```
==> Caveats
This formula does not install either `gpg` or `gpgv` executables into
the PATH.
If you simply require `gpg` and `gpgv` executables without explicitly
needing GnuPG 1.x we recommend:
  brew install gnupg
If you really need to use these tools without the "1" suffix you can
add a "gpgbin" directory to your PATH from your ~/.bash_profile like:
    PATH="/usr/local/opt/gnupg@1.4/libexec/gpgbin:$PATH"
Note that doing so may interfere with GPG-using formulae installed via
Homebrew.
```

**Comment by hurricanehrndz** [comment]
@sobolevn 

It seems the macos config has changed a little. Anyhow, I don't have access to a mac and going back and forth waiting for results from travis is time consuming. Can we drop the mac tests?

**Comment by sobolevn** [comment]
Comment them for now if it bothers you, and assign a new task to me. I will have a look at it.

**Comment by sobolevn** [comment]
@hurricanehrndz how is this going? do you need any help?

**Comment by hurricanehrndz** [comment]
I'm just finishing other things on my to do list and running the program
for myself. I have added Alpine to the test matrix, I will let you know if
I hit any walls

**Comment by hurricanehrndz** [comment]
@sobolevn,

I'd like to update you on the status of my progress. I'm not sure if github comments are the best, I do not have skype, I do have Telegram and I'm readily available on irc. Just as a small update. I'm hoping to have most things done by November 15. Hope that works for you. So far what is remaining is the bats test for the new option I added, and updating the readme.

**Comment by sobolevn** [comment]
Awesome job! I really appreciate it! 👍 

Let's stick to github issues. So every piece of discussion will be preserved.
