### ISSUE TITLE
"git secret reveal" is not working on Mac.

### ISSUE THREAD

**Issue by ViktorSoroka** [sobolevn/git-secret#112]
I have existing project which use "git secret". I have my key added to it. When I try to decrypt cryptic files nothing happens. I have installed "git-secrets" via brew.

Steps to reproduce this issue?
1. Run "git secret reveal" on mac.

I have to do decryption manually with "gpg --decrypt" command which is ugly. While doing that I have the window for opening password like that (with abracadabra symbols): http://prntscr.com/gtzud9. Moreover this symbols appeared while creating the key (form for entering and confirming the password).

Versions of software I am using:
**Operating system: (`macOS Siera`)
**`git-secret` path:** (`/usr/local/bin/git-secret`)
**`git-secret` version:** (`0.2.2`) 
**Shell type and version:** (`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
`)
**`gpg` version:** (`2.2.1`)

**Comment by sobolevn** [comment]
Yeap, thanks! That's a known issue.
https://github.com/sobolevn/git-secret/issues/46

This happens because `gpg` change its api. 
As a workaround you can downgrade to version prior to `2.1`

**Comment by Vinlock** [comment]
When will this be supported correctly?

**Comment by sobolevn** [comment]
@Vinlock when `0.2.3` will be released. It should happen soon.

**Comment by joan38** [comment]
How do you downgrade gpg on Mac? I installed it with brew and we all know brew is not a real package manager...

Is the release going forward?
Sounds like git secret is currently impossible to be used.

**Comment by michaelt55** [comment]
Not sure why this issue was closed? `git secret reveal` still doesn't work on macOS Sierra 10.12.6 using gpg 2.2.3 (it just silently fails).  "Just downgrade gpg" doesn't seem like a practical solution..  Guess it's time to consider alternatives.

**Comment by sobolevn** [comment]
@michaelt55 @joan38 could you please try a `develop` branch? It should be fixed there.

**Comment by joan38** [comment]
I will try, but what’s blocking the release of the next version?

**Comment by sobolevn** [comment]
Some minor bugs to fix and to stabilize release process.
