### ISSUE TITLE
Hide with -d  argument does not clean up files in sub directories

### ISSUE THREAD

**Issue by a3785lex** [sobolevn/git-secret#116]
What are the steps to reproduce this issue?
-------------------------------------------
1. Create a testing folder `mkdir test` and `cd` into it
2. Init a git repo and git secret with `git init` and `git secret init`, create an empty .gitignore
3. Run `git secret tell` to add someone who can access the secrets
4. Create a file `file1` in the current folder
5. Create a sub directory inside the testing folder with `mkdir sub`
6. Create a file under the folder `sub`, and name it `file2`
7. `git secret add -i file1 sub/file2`
> these files are not ignored: file1 sub/file2 ;
> auto adding them to .gitignore
> 2 items added.
8. `git secret hide -vd`, expecting that unencrepted files got cleaned up.
> removing unencrypted files:
> removed './file1'
>
> done. all 2 files are hidden.

What happens?
-------------
The message of the `git secret hide -vd` command shows that only file1 was deleted.
And it is true that only file1 was deleted, but sub/file2 was not.
Both files were encrypted successfully, just for your information.

What were you expecting to happen?
----------------------------------
I suppose the file in the sub directory should also get deleted?

Any other comments?
-------------------
`ls -l` shows that my user account has full access rights to both file1 and file2.
So I guess it is not the "permission denied" stuff causing the problem.

I cloned the git-secret repo and ran the tests.
All tests passed, including the case "run 'hide' with '-d' and '-v' and files in subdirectories"
So I have no idea about where can be wrong...

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
I use git-secret on Windows with the Linux subsystem feature.
Host: Windows 10
Client: Ubuntu distribution.
Linux DESKTOP-IQ5GKG8 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`) …
/user/bin/git-secret

**`git-secret` version:** (`git secret --version`) …
0.2.2

**Shell type and version:** (`$SHELL --version`) …
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

**`gpg` version:** (`gpg --version`) …
1.4.20

**Comment by sobolevn** [comment]
That's a entry-level issue, I guess. @a3785lex do you want to take this over?

**Comment by a3785lex** [comment]
Well, I surely can.
But I only know a little about shell script and -nix stuffs (mostly live on the Windows) so it may take some time.

**Comment by a3785lex** [comment]
After playing with the test and source code for a while, I cannot find any tiny point that can be wrong.
Then I just `make build` and replace the one found in path with the freshly built one, problem solved.
I did not realize that this bug had been fixed by @ctavan quite a while ago until looking up for the git history.
Sorry for bothering with this dumb issue!

**Comment by ctavan** [comment]
I agree though that it would be nice to release a new version that includes my fix ;). It's the only issue that I find current 0.2.2 version of git-secret.

What do you think @sobolevn ? Since there's rather little development activity here recently, how about at least releasing the latest master to the public?

**Comment by sobolevn** [comment]
Ok, sure. That's not so much left to do, so guess I will manage to find some time this week.

**Comment by ctavan** [comment]
That would be great @sobolevn. Let me know if I can help.

**Comment by sobolevn** [comment]
@hurricanehrndz do you have uncommited changes that can help me? If case you do, could you please commit them? 

@ctavan sure, thanks!

**Comment by hurricanehrndz** [comment]
I will look into it.

**Comment by hurricanehrndz** [comment]
I will commit my change back into dev, sorry for the delay.I have been having troubles finalizing my new dev machine.

**Comment by hurricanehrndz** [comment]
@sobolevn,

My work has been merged into develop. I believe 2.3 is ready for release other than a guides section in the readme.

**Comment by sobolevn** [comment]
@hurricanehrndz you are awesome. Let's do the release!
