### ISSUE TITLE
Enhancement: Password manager ?

### ISSUE THREAD

**Issue by pschoffer** [sobolevn/git-secret#122]
I was thinking about enhancing the functionality to be able to encrypt passwords and return them, not the whole files.

So that you would do something like 
```
$ git secret hide-password <identification=url>
Enter Login: login1
Enter Password: 123
Re-enter Password: 123
Password saved.
```
This would create a temporary file, hide it and remove it. Reveal would print the password on stdout (and rm the temp file again). Overall adds something like git-pass functionality.

What do you think? 

PS: I would be happy to try to implement it.

**Comment by nictrix** [comment]
Sounds similar to this project also: https://github.com/justwatchcom/gopass

I think the functionality you describe (rm temporary non-encrypted file) should be the default workflow and you explicitly ask to create a non-encrypted file.

**Comment by pschoffer** [comment]
@nictrix  thanks, this looks like exactly what I was looking for!
