### ISSUE TITLE
sha256sum command is "shasum -a256" on macOS

### ISSUE THREAD

**Issue by ilovezfs** [sobolevn/git-secret#124]
What are the steps to reproduce this issue?
-------------------------------------------
1. `brew pull https://github.com/Homebrew/homebrew-core/pull/22177`
2. `brew install -s git-secret`
3. `brew test -v git-secret`

What happens?
-------------
```
==> /usr/local/opt/gnupg/bin/gpg --batch --gen-key batch.gpg
gpg: directory '/tmp/git-secret-test-20171228-38697-hdc0f5/.gnupg' created
gpg: keybox '/tmp/git-secret-test-20171228-38697-hdc0f5/.gnupg/pubring.kbx' created
gpg: /tmp/git-secret-test-20171228-38697-hdc0f5/.gnupg/trustdb.gpg: trustdb created
gpg: key 0B593FC47C08BFBC marked as ultimately trusted
gpg: directory '/tmp/git-secret-test-20171228-38697-hdc0f5/.gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/tmp/git-secret-test-20171228-38697-hdc0f5/.gnupg/openpgp-revocs.d/3C2FDE6568107A87A54959AA0B593FC47C08BFBC.rev'
==> git init
Initialized empty Git repository in /private/tmp/git-secret-test-20171228-38697-hdc0f5/.git/
==> git config user.email testing@foo.bar
==> git secret init
'/private/tmp/git-secret-test-20171228-38697-hdc0f5/.gitsecret/' created.
cleaning up...
==> git secret tell -m
gpg: keybox '/private/tmp/git-secret-test-20171228-38697-hdc0f5/.gitsecret/keys/pubring.kbx' created
gpg: /private/tmp/git-secret-test-20171228-38697-hdc0f5/.gitsecret/keys/trustdb.gpg: trustdb created
==> git secret add shh.txt
1 item(s) added.
==> git secret hide
/usr/local/bin/git-secret: line 895: sha256sum: command not found
done. all 1 files are hidden.
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
Test::Unit::AssertionFailedError: <#<Pathname:/tmp/git-secret-test-20171228-38697-hdc0f5/shh.txt.secret>>.exist? is true value expected but was
<false>
```

What were you expecting to happen?
----------------------------------
The test to pass.

Any other comments?
-------------------
macOS has `shasum -a256` not `sha256sum`

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
```
iMac-TMP:~ joe$ uname -a
Darwin iMac-TMP.local 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64
```

**`git-secret` path:** (`which git-secret`) …
```
iMac-TMP:~ joe$ which git-secret
/usr/local/bin/git-secret
```

**`git-secret` version:** (`git secret --version`) …
0.2.3 though it reports as 0.2.2 because version.sh wasn't updated https://github.com/sobolevn/git-secret/blob/v0.2.3/src/version.sh#L4

**`git` version:** (`git --version`) …
```
iMac-TMP:~ joe$ git --version
git version 2.15.1
```

**Shell type and version:** (`$SHELL --version`) …
```
iMac-TMP:~ joe$ $SHELL --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**`gpg` version:** (`gpg --version`) …
```
iMac-TMP:~ joe$ gpg --version
gpg (GnuPG) 2.2.4
libgcrypt 1.8.2
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/joe/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by sobolevn** [comment]
@ilovezfs hm, that seems like a we have to create a new function based on `uname`.
We already have a way to customize this command, but I guess it is not a user-friendly way.
https://github.com/sobolevn/git-secret/blob/master/src/_utils/_git_secret_tools.sh#L18

So, can you please make a PR for this?

Here' what we should do:
1. Wrap `shasum -a256` into the function and add it into https://github.com/sobolevn/git-secret/blob/master/src/_utils/_git_secret_tools_osx.sh
2. Wrap `sha256sum` into function and add it into https://github.com/sobolevn/git-secret/blob/master/src/_utils/_git_secret_tools_linux.sh
3. Make this function conditional based on `uname`: https://github.com/sobolevn/git-secret/blob/master/src/_utils/_git_secret_tools.sh#L102
4. Refactor how `_get_checksum_local` works https://github.com/sobolevn/git-secret/blob/492c8d8b79566e71ccff6a7ee924dc9afc5a57a5/src/commands/git_secret_hide.sh#L54

**Comment by ilovezfs** [comment]
@sobolevn https://github.com/sobolevn/git-secret/pull/127
