### ISSUE TITLE
git secret reveal: gpg: Sorry, no terminal at all requested - can't get input

### ISSUE THREAD

**Issue by simplenotezy** [sobolevn/git-secret#131]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install git secret
2. Go to your project
3. Run `git secret reveal`

What happens?
-------------
Error:

    gpg: Sorry, no terminal at all requested - can't get input

What were you expecting to happen?
----------------------------------

Reveal my secrets!

What versions of software are you using?
----------------------------------------
**Operating system:** Darwin MFMBP.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**`git-secret` path:** `/usr/local/bin/git-secret`

**`git-secret` version:** `0.2.2`

**`git` version:** `git version 2.14.3 (Apple Git-98)`

**Shell type and version:** `zsh 5.3 (x86_64-apple-darwin17.0)`

**`gpg` version:** (`gpg --version`) `gpg (GnuPG/MacGPG2) 2.2.3`

**`git` version:** `git version 2.14.3 (Apple Git-98)` (still 😅)

**Comment by sobolevn** [comment]
Thanks for the report. Could you please update to `0.2.3`?

**Comment by simplenotezy** [comment]
Thanks for prompt reply.

     [admin:~]$ brew upgrade git-secret
     Error: git-secret 0.2.3 already installed
     [admin:~]$ git-secret --version
     0.2.2
     [admin:~]$ brew install git-secret
     Warning: git-secret 0.2.3 is already installed
     [admin:~]$ git-secret --version
     0.2.2

🤔

**Comment by simplenotezy** [comment]
Also tried to reinstall.

	[admin:~]$ git-secret --version
	0.2.2
	[admin:~]$ brew uninstall git-secret
	Uninstalling /usr/local/Cellar/git-secret/0.2.3... (19 files, 56.3KB)
	[admin:~]$ git-secret --version
	zsh: command not found: git-secret
	[admin:~]$ brew install git-secret
	Updating Homebrew...
	==> Downloading https://homebrew.bintray.com/bottles/git-secret-0.2.3.high_sierra.bottle.tar.gz
	Already downloaded: /Users/admin/Library/Caches/Homebrew/git-secret-0.2.3.high_sierra.bottle.tar.gz
	==> Pouring git-secret-0.2.3.high_sierra.bottle.tar.gz
	🍺  /usr/local/Cellar/git-secret/0.2.3: 19 files, 56.3KB
	[admin:~]$ git secret --version
	0.2.2

Makes me wonder if the `git-secret --version` output is lying

**Comment by simplenotezy** [comment]
Running `brew doctor` prints:

	Warning: You have unlinked kegs in your Cellar
	Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
	those kegs to fail to run properly once built. Run `brew link` on these:
	  gnupg
	[admin:~]$ brew link gnupg
	Linking /usr/local/Cellar/gnupg/2.2.4...
	Error: Could not symlink bin/gpg-agent
	Target /usr/local/bin/gpg-agent
	already exists. You may want to remove it:
	  rm '/usr/local/bin/gpg-agent'

	To force the link and overwrite all conflicting files:
	  brew link --overwrite gnupg

	To list all files that would be deleted:
	  brew link --overwrite --dry-run gnupg


Tried runnning `brew link --overwrite gnupg´ but to no avail

**Comment by simplenotezy** [comment]
So following: https://lists.gnupg.org/pipermail/gnupg-users/2003-May/018492.html solved the issue.

I wonder why the `--no-tty` is there, if it breaks thinngs, and I also wonder why I don't seem to be able to upgrade to 0.2.3

**Comment by joshrabinowitz** [comment]
Note: comments above also mention issue #137
