### ISSUE TITLE
Feature request: Support automatic clean/smudge filters for automatic usage via gitattributes

### ISSUE THREAD

**Issue by jgeorgeson** [sobolevn/git-secret#138]
This is a really neat idea!

Reading over the usage it seems like a natural fit to have the hide/reveal scripts called automatically by clean/smudge during checkout and push, based on gitattributes. The LFS utility does this and I think that seamless automatic execution during checkout and push really helped it's adoption.

**Comment by sobolevn** [comment]
Nice! Would you like to contribute?

**Comment by jgeorgeson** [comment]
I'm not opposed to it but it's not something I could take on in the immediate future.

**Comment by sobolevn** [comment]
That's is very close to https://github.com/sobolevn/git-secret/issues/84 Which is on our roadmap.

Closing this one.
