### ISSUE TITLE
Feature request: decrypt single file to stdout; 'git secret cat filename.txt' ?

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#141]
I'd like to be able to decrypt the contents of a single file without decrypting the file(s) in place.

I'm imagining a 'git secret cat' command something like (assuming git secret is already set up):

   % git secret add config.init
   % git secret hide
   % git secret cat config.ini
   ( output of config.ini displays here)

This would be useful to fetch keys from inside programs without decrypting any files on the filesystem).

Thank you

**Comment by sobolevn** [comment]
@joshrabinowitz that's a good one. 
Currently I don't have much to spend on this project, so I encourage people to contribute!

Do you want to send a PR with this feature?

**Comment by joshrabinowitz** [comment]
hm, I could give it a shot. 
Could you provide tips on how it should work?

**Comment by sobolevn** [comment]
Closed via #142
