### ISSUE TITLE
improve documentation about .gitsecret directory contents

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#144]
As of 0.2.4, the docs talk about the `.gitsecret` directory:
 
(See the end of:
https://github.com/sobolevn/git-secret/blob/master/man/man7/git-secret.7.ronn )

Can someone describe the contents of each file in a .gitsecret directory so I can write them up them in the docs? 

Here's what I'm seeing in a .gitsecret directory, with a description of one file:

````
% find .gitsecret/ -type f
.gitsecret/paths/mapping.cfg 
.gitsecret/keys/mapping.cfg
.gitsecret/keys/trustdb.gpg
.gitsecret/keys/secring.gpg
.gitsecret/keys/pubring.gpg
.gitsecret/keys/random_seed  - seed used for keys, must be protected
````

**Comment by joshrabinowitz** [comment]
There are basic descriptions here:

    https://www.gnupg.org/documentation/manuals/gnupg/GPG-Configuration.html

There's special mention about random_seed specifically being in .gitignore, and in git-secret.7.ronn it says that .gitsecret folder 'should not be ignored'. 

Should all files except random_seed be checked in? Let's give clear guidance.

**Comment by sobolevn** [comment]
Yeap, all files except `random_seed` should be checked in.

**Comment by joshrabinowitz** [comment]
The docs have been clarified on this topic
