### ISSUE TITLE
Fix CI builds: lint errors, SSL certificate validation errors, 

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#152]
Errors included

* Python 'InsecurePlatformWarning' / ' SNIMissingWarning' errors:
   https://travis-ci.org/sobolevn/git-secret/jobs/367208318

* "Failed to validate the SSL certificate for api.github.com:443."
   https://travis-ci.org/sobolevn/git-secret/jobs/367273796

* bash linter errors about 'which'

**Comment by joshrabinowitz** [comment]
Fixed in https://github.com/sobolevn/git-secret/pull/148

**Comment by sobolevn** [comment]
🎉
