### ISSUE TITLE
'git secret changes' does not work unless passed secret filenames

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#153]
Contrary to the docs, `git secret changes` does not work unless you pass it filenames of *.secret files.

In all cases with a git-secret repo, if you type

    `git secret changes`

You get no errors, but output like: 

````
     % git secret changes
    changes in /full/path/config.ini:
    <blank line>
````

For the command to work it must be passed the secret filenames (config.ini.secret).

**Comment by sobolevn** [comment]
That's a bug. It should not be this way.

`git secret changes` should by default output all changes. 
And when some filenames are given - only limit this changes by these filenames.
