### ISSUE TITLE
'git secret hide' without source files presents errors but reports success

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#154]
* Steps to replicate:

Set up a git-secret repo set up with a hidden `config.ini` (encrypted with `git secret add config.ini` and `git secret hide -d config.ini`)

```
% ls config.ini*
config.ini.secret
```
and you type `git secret hide` (no filenames)

* Actual results: You get the output:
````
% git secret hide
sha256sum: /full/path/config.ini: No such file or directory  # <- note error
done. all 1 files are hidden.
````

And the file is _not_ re-encrypted.  
 
* Expected results:

A better error message (i.e. 'abort: source file not found: /full/path/config.ini") and a non-zero exit code

**Comment by sobolevn** [comment]
Sorry, I am missing one thing in your description: is this file `add`ed to our keychain?
Or it is just a random file with the `.secret` extension?

**Comment by joshrabinowitz** [comment]
Assuming the file has been `add`ed to the keychain, and the source removed via `git secret hide -r`

**Comment by sobolevn** [comment]
So, that a bug. 😞
