### ISSUE TITLE
http://git-secret.io/ should have link to 'git-secret-cat' and git-secret tutorial video

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#168]
git-secret.io should have a link to the
`git-secret-cat docs` and to 
https://asciinema.org/a/41811?autoplay=1

**Comment by sobolevn** [comment]
Indeed! Thanks for the suggestion!

**Comment by joshrabinowitz** [comment]
Can we stop adding extra tasks to the 0.2.4 milestone and assigning them to me?

**Comment by sobolevn** [comment]
Sorry!

**Comment by joshrabinowitz** [comment]
no problem... thank you!

**Comment by SIGSTACKFAULT** [comment]
dibs

**Comment by SIGSTACKFAULT** [comment]
It seems to already have the link to `git-secret-cat docs`? @joshrabinowitz Second-last one under Command Reference.

**Comment by SIGSTACKFAULT** [comment]
The prompt in the video is too long so I think I'll rerecord it.

**Comment by SIGSTACKFAULT** [comment]
Rerecorded. What file should I add it in? https://asciinema.org/a/277043
