### ISSUE TITLE
Apply Unix permissions from `.secret` file to revealed file

### ISSUE THREAD

**Issue by gthank** [sobolevn/git-secret#172]
I noticed today that revealed files don't get the execute bit from the `.secret` version. I can work around this during my deploys by remembering to set the permissions explicitly, but it would be nice if `git-secret` automatically chmodded the revealed file to have the same perms as the encrypted original.

EDIT: On *nix machines, it should be essentially a one-liner:

```
chmod `stat -f "%Op" $src_file` $target_file
```

after the [`_decrypt` call](https://github.com/sobolevn/git-secret/blob/master/src/commands/git_secret_reveal.sh#L43) in the `reveal` command.

It might also make sense to do the same thing in the other direction when hiding files.

The trick is whether or not this would work on Windows devices (using WSL), and what to do in non-WSL environments (if those are in fact supported).

**Comment by sobolevn** [comment]
@gthank nice one! do you want to elaborate on this?

**Comment by joshrabinowitz** [comment]
Maybe this would make sense to be activated with a `-p` option, like `tar` and `cp` have.

**Comment by gthank** [comment]
@sobolevn My use-case is that I am hiding a shell script that has some credentials in it. As it currently stands, I have to go back and chmod that plaintext file after I reveal it. I think it would be more convenient if `git-secret` did that for me. After all, `git` is already tracking the mode on the `.secret` file, so `git-secret` "knows" (or more realistically, can find out via the `stat` command) what we want the mode to be on the plaintext version. I'm like 99% sure the one-liner I proposed would also pick up things like the sticky bit and setuid/setguid, which I think would be the desired behavior.

If you mean "elaborate on how that actually works", `stat` pulls basically everything the OS knows about the file, and then the `-f "%Op"` part says "show me the permissions (`p`) and format it in octal (`%O`).

@joshrabinowitz For `cp`, the `-p` flag lets you pass a bunch of fine-grained controls over whether to preserve the mode, the timestamp, xattrs, etc., and the default is to preserve the mode (along w/ ownership and timestamps). I don't really use `tar` often enough to say for sure whether it has the same defaults, but I would guess it does. I guess it might make `git-secret` a better command-line citizen if it accepted the same basic args as `cp` or `tar`, but it seems like a lot more work (for one thing, I'm not sure how you'd "preserve" the timestamps, since it's not an actual copy operation; you'd need stronger shell-fu than mine for that part), and I'm not sure how often people would want to do it.

**Comment by gthank** [comment]
@joshrabinowitz I'd prefer if it were the default behavior, but having the option at all is a win.

**Comment by joshrabinowitz** [comment]
I'm planning to add this feature in the near future.
