### ISSUE TITLE
git secret reveal not working or providing ouput

### ISSUE THREAD

**Issue by CalebSchwartz** [sobolevn/git-secret#174]
What are the steps to reproduce this issue?
-------------------------------------------
1. Clone git repo onto server
2. navigate to repo on server and run 'git secret reveal'

What happens?
-------------
Nothing happens. There isn't any output and I cannot find a way to output some sort of debug steps .

What were you expecting to happen?
----------------------------------
I was expecting git secret reveal to prompt for a password

Any logs, error output, etc?
----------------------------
Nothing ouputs

Any other comments?
-------------------
I am running git secret reveal on a rhel7 server. I have successfully added the users gpg key using git secret tell <username> from my local machine. I then push the changes to git and pull them down onto the server. I tried to use git secret reveal but it doesn't prompt me for a password input or seem to do anything for that matter.

 GIT_TRACE=1 git secret reveal
11:48:55.578966 git.c:576               trace: exec: 'git-secret' 'reveal'
11:48:55.579059 run-command.c:627       trace: run_command: 'git-secret' 'reveal'
11:48:55.588624 git.c:344               trace: built-in: git 'check-ignore' '--no-index' '-q' '.gitsecret/'
11:48:55.591553 git.c:344               trace: built-in: git 'rev-parse' '--show-toplevel'

I have verified that .gitsecret is not a part of the .gitignore (I have even removed the .gitignore). If I use gpg --decrypt <secret_file>, it will successfully decrypt the file. git secret whoknows lists the user that I am expecting to find. 

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
Linux 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`) …
/usr/bin/git-secret

**`git-secret` version:** (`git secret --version`) …
0.2.2 

**`git` version:** (`git --version`) …
git version 2.16.3

**Shell type and version:** (`$SHELL --version`) …
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

**`gpg` version:** (`gpg --version`) …
gpg (GnuPG) 2.2.7
libgcrypt 1.8.2

**Comment by joshrabinowitz** [comment]
Hello @CalebSchwartz 

Would it be possible to re-test your issue with the current master branch? There's been a decent amount of code changes related to error checking and error messages in the last month or so.

Also, if you run 
````
'bash -x `which git-secret` reveal'
````

it will show all the steps bash takes.

**Comment by CalebSchwartz** [comment]
`bash -x git-secret reveal
+ GITSECRET_VERSION=0.2.2
+ WORKING_DIRECTORY=/file/path/to
+ SECRETS_DIR=.gitsecret
+ SECRETS_DIR_KEYS=.gitsecret/keys
+ SECRETS_DIR_PATHS=.gitsecret/paths
+ SECRETS_DIR_KEYS_MAPPING=.gitsecret/keys/mapping.cfg
+ SECRETS_DIR_KEYS_TRUSTDB=.gitsecret/keys/trustdb.gpg
+ SECRETS_DIR_PATHS_MAPPING=.gitsecret/paths/mapping.cfg
+ : .secret
+ : gpg
+ GPGLOCAL='gpg --homedir=.gitsecret/keys --no-permission-warning'
+ set -e
+ _init_script reveal
+ [[ 1 == 0 ]]
+ local dry_run=0
+ [[ 1 -gt 0 ]]
+ local opt=reveal
+ case "$opt" in
+ break
+ [[ 0 == 0 ]]
+ _check_setup
+ local is_tree
++ _is_inside_git_tree
++ git rev-parse --is-inside-work-tree
++ echo 0
+ is_tree=0
+ [[ ! 0 -eq 0 ]]
+ local ignored
++ _check_ignore .gitsecret/
++ git check-ignore --no-index -q .gitsecret/
++ echo 1
+ ignored=1
+ [[ ! 1 -eq 1 ]]
+ local secring=.gitsecret/keys/secring.gpg
+ [[ -f .gitsecret/keys/secring.gpg ]]
++ _function_exists reveal
++ declare -f -F reveal
++ echo 0
+ [[ 0 == 0 ]]
+ [[ ! reveal == _* ]]
+ reveal
+ local homedir=
+ local passphrase=
+ local force=0
+ OPTIND=1
+ getopts hfd:p: opt
+ shift 0
+ '[' '' = -- ']'
+ _user_required
+ _secrets_dir_exists
+ local root_path
++ _get_git_root_path
++ local result
+++ git rev-parse --show-toplevel
++ result=/file/path/to
++ echo /file/path/to
+ root_path=/file/path/to
+ local full_path=/file/path/to/.gitsecret
+ [[ ! -d /file/path/to/.gitsecret ]]
+ local 'error_message=no users found. run '\''git secret tell'\'' before adding files.'
+ [[ ! -f .gitsecret/keys/trustdb.gpg ]]
+ local keys_exist
++ gpg --homedir=.gitsecret/keys --no-permission-warning -n --list-keys
+ keys_exist='file/path/to/.gitsecret/keys/pubring.kbx
--------------------------------------------------------------
USER INFORMATION HERE - Removed for privacy
+ local counter=0
+ read -r line
+ _decrypt /file/path/to/environment.ini: 1 0 '' ''
+ local filename=/file/path/to/environment.ini:
+ local write_to_file=1
+ local force=0
+ local homedir=
+ local passphrase=
+ local encrypted_filename
++ _get_encrypted_filename /file/path/to/environment.ini:
++ local filename
+++ dirname /file/path/to/environment.ini:
+++ basename /file/path/to/environment.ini: .secret
++ filename=/file/path/to/environment.ini:
++ echo /file/path/to/environment.ini:.secret
++ sed -e 's#^\./##'
+ encrypted_filename=/file/path/to/environment.ini:.secret
+ local 'base=gpg --use-agent -q --decrypt --no-permission-warning'
+ [[ 1 -eq 1 ]]
+ base='gpg --use-agent -q --decrypt --no-permission-warning -o /file/path/to/environment.ini:'
+ [[ 0 -eq 1 ]]
+ [[ ! -z '' ]]
+ [[ ! -z '' ]]
+ gpg --use-agent -q --decrypt --no-permission-warning -o /file/path/to/environment.ini: vms/env/environment.ini:.secret`

I'll work on pulling the master branch. Should have time today if not I will tomorrow.

**Comment by CalebSchwartz** [comment]
@joshrabinowitz Whatever changes are in master seemed to work. I was able to successfully reveal my file. Thanks for the suggestion!
