### ISSUE TITLE
Automatically add file to .gitignore on git secret add

### ISSUE THREAD

**Issue by mettjus** [sobolevn/git-secret#18]
It would be convenient if files where automatically added to `.gitignore` when `git secret add <file>` is run.

**Comment by sobolevn** [comment]
Well, I thought about this feature. I guess it can be implemented as an option-flag.

**Comment by mettjus** [comment]
It could be. I just can't think of a case when you wouldn't want the file to be added to `.gitignore`. The only advantage I can think of is that keeping the command more dummy (as in this case) leaves more responsibility to the user and doesn't make assumptions which could turn out wrong.

**Comment by mettjus** [comment]
I would rather add it as a global configuration option.

**Comment by sobolevn** [comment]
I got your point. Will experiment with different approaches today.
Anyway it is important to test the filename to be already ignored. To prevent doubling. Because in my workflow I just add `*.secret` to the `.gitignore` and that's all.

**Comment by mettjus** [comment]
From what I can see you already do the check with `_check_ignore` and store the list of unignored files in `not_ignored`. It would probably only need to loop over the entries and append them to `.gitignore` instead of aborting in case length is `> 0`.
Not sure I understand why you add `*.secret` to `.gitignore`; aren't `*.secret` files the ones that should be version controlled?
Btw I forked the repo and would love to help, but I am absolutely not good in bash programming nor TDD :(

**Comment by sobolevn** [comment]
Ummm, yeah... Never mind about that files' extension stuff.

You are absolutely right about the loop. Thanks for your effort!

**Comment by mettjus** [comment]
Well and quickly done! ;)
