### ISSUE TITLE
Git secret 0.2.1 reveal fails on a git secret hide 0.2.3

### ISSUE THREAD

**Issue by rjcoelho** [sobolevn/git-secret#182]
If I add a new git secret file on 0.2.3, the git secret reveal fails because of the mapping, which apparently now includes  

Did we change the format on 0.2.3 ? https://github.com/sobolevn/git-secret/commit/638b67e155e9f9fe436b40dd570fc872463b8d13#diff-b02a252754749c1e9180b731b39e9e3b

Can you confirm this ? and if do we have some breaking change notes ?

**Comment by rjcoelho** [comment]
Unfortunately brew install git-secret@0.2.1 doesn't work. Do you know any wait to install an old version ? Thanks

**Comment by sobolevn** [comment]
You can install it from here: https://github.com/sobolevn/git-secret/releases

Or you can fix your existing installation:
1. Backup your `.gitsecret/paths/mapping.cfg`
2. Empty the original file
3. Add all files to `gitsecret` once again

It should be fine afterwards. We have updated how path mappings work by adding hash.
This hash is used to determine which files we actually updated. And `gitsecret` now will only re-encrypt only files that had changed.

I am closing this issue as a bug, that we won't fix. Sorry!

Feel free to ask any question that you might have.

**Comment by rjcoelho** [comment]
Your solution doesnt work for me .. i need to git secret reveal on 0.2.1 hidden from the latest

**Comment by sobolevn** [comment]
> i need to git secret reveal on 0.2.1 hidden from the latest

**Comment by rjcoelho** [comment]
Or honor old mapping file format if one already exists

I cannot ungrade .. it’s a Jenkins build host used to build other projects
