### ISSUE TITLE
gnupg-git-fedora-latest gives `sudo: /usr/local/bin/rspec: command not found`

### ISSUE THREAD

**Issue by simbo1905** [sobolevn/git-secret#189]
After upgrading RedHat to use dnf to fix issue #186 we now hit a ruby issue `sudo: /usr/local/bin/rspec: command not found` as shown at. 

https://travis-ci.org/sobolevn/git-secret/jobs/389884422#L3236

**Comment by simbo1905** [comment]
Okay this is the only blocker shown at

 https://travis-ci.org/sobolevn/git-secret/builds/389921524

Reading the code it isn't clear to me where `rspec` is being called and what should be installing that. If I `kitchen login` and `gem install rspec` till install to `/usr/bin/rspec`. So my next guess is that `gem install -n /usr/local/bin rspec` might fix this. Can anyone tell me what should be installing rspec?

**Comment by joshrabinowitz** [comment]
I think rspec is being used by kitchen to run tests using the 
.ci/integration/*/serverspec/default_spec.rb files

Also, looking at that output, I think the right location for rspec in that context might be  /home/travis/.rvm/gems/ruby-2.4.1/bin/rspec (I mentioned this in #188 too)

**Comment by simbo1905** [comment]
I don't know what is calling it to override its path. I just tried having ansible install it to the expected locations and it passed locally. I have pushed it which will update the PR. Its late in my timezone so that's me done for a while.

**Comment by simbo1905** [comment]
fixed in #188
