### ISSUE TITLE
deploy from a git tag

### ISSUE THREAD

**Issue by simbo1905** [sobolevn/git-secret#197]
There was a note in #120 ”We need to run deploy on tags, right now we are using deploys on master branch”. This ticket is to track that build enhancement.

**Comment by sobolevn** [comment]
This should be a really easy feature.

**Comment by simbo1905** [comment]
Approach:
1) fixes and/or features are merged to master 
2) changelog is generated and manually updated as necessary 
3) contributor applies a release tag vX.Y.Z
4) travis build runs for the new tag and the travis deploy steps check that the coding being built is a release tag. if so they run.

If there are transient errors some but not all release artifacts will deploy. We then need to kick-off the build again. Best we automate that. But we now face a choice:

1) contributor re-applies a release tag vX.Y.Z 
2a) deploy steps run as before and overwrite any previous release 
2b) deploy steps look for an existing release and refuse to run assuming it's a rebuild to fix another deploy step 

Assuming we are prompt and tidy there isn't much risk of overwrite release. It would make me nervous doing that with a production service as bad things happen when the principal of immutable releases are relaxed.

What are peoples thoughts on 2a vs. 2b?

**Comment by sobolevn** [comment]
I usually reapply tags manually when something goes wrong on a release.
But, I do it for cases when I am 100% sure that release was not already published.

**Comment by simbo1905** [comment]
@joshrabinowitz do you have a preference?

**Comment by joshrabinowitz** [comment]
For this release especially, I think @sobolevn's suggestion is good. Let's get this out the door expediently. 
In the long run I agree releases should be immutable.

**Comment by joshrabinowitz** [comment]
@simbo1905 @sobolevn should we close this? I see #212 was merged.
