### ISSUE TITLE
missing git tag for v0.2.4

### ISSUE THREAD

**Issue by simbo1905** [sobolevn/git-secret#198]
Looking at the tags on GitHub there isn't one for the v0.2.4

**Comment by simbo1905** [comment]
I pushed a tag for the latest merge to master which was the changelog update for v0.2.4

**Comment by simbo1905** [comment]
@joshrabinowitz @sobolevn I just noticed that there is logic to apply a tag in `utils/hooks/post-commit.sh` which is referenced in `Makefile` at https://github.com/sobolevn/git-secret/blob/dec31f016ed9cf4624aee4d3ef3ea29766e6bd17/Makefile#L77. 

Is that functionality no longer in use?

**Comment by ilovezfs** [comment]
@sobolevn it looks like the explicit GitHub release for 0.2.4 is missing.

https://github.com/sobolevn/git-secret/releases/latest is pointing at 0.2.3

**Comment by joshrabinowitz** [comment]
0.2.4 has not been 'released' yet.

**Comment by simbo1905** [comment]
@joshrabinowitz it seems we got the process a bit back-to-front this time around as the github release is referenced by the brew PR. the brew maintainer reviewing the brew PR will be checking to see whether it is using the new latest release on github. so when we automate this for next release we should sequence the brew release as running after the github release.
