### ISSUE TITLE
Silent error on secret hide when GPG key expires

### ISSUE THREAD

**Issue by rjcoelho** [sobolevn/git-secret#202]
When a GPG key expires we get no output when doing a "git secret hide". We should get a GPG key expired error message (if possible).

**Comment by sobolevn** [comment]
Yeap, that's true. This check should also happens when we try to add (`git secret tell`) an expired key.

**Comment by rjcoelho** [comment]
Basically any call to gpg should check for error codes and report then to stderr (and stop the command). Again if this is possible.

**Comment by joshrabinowitz** [comment]
Could someone write a test in a PR to show the problem?

**Comment by joshrabinowitz** [comment]
@rjcoelho I think this is what you're asking for: PR #205 'more careful error checking running gpg'

**Comment by joshrabinowitz** [comment]
I think we can close this, @rjcoelho please let us know if PR #205  fixes the issues you raise here.

**Comment by rjcoelho** [comment]
@joshrabinowitz it solve my issue. Thanks for such a speedy solution.

**Comment by joshrabinowitz** [comment]
re-opened until #205 is in the released code.

**Comment by joshrabinowitz** [comment]
this is a dup o #238
