### ISSUE TITLE
bats build issues on master branch

### ISSUE THREAD

**Issue by simbo1905** [sobolevn/git-secret#209]
A rebuild of the last successful Travis master build (I cancelled the rpm and deb deploy jobs) gives broken jobs use to a bats install error:

```TASK [Install bats] ************************************************************
       fatal: [localhost]: FAILED! => {"changed": false, "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /opt/bats/libexec/bats", "path": "/usr/bin/bats", "src": "/opt/bats/libexec/bats", "state": "absent"}
       	to retry, use: --limit @/tmp/kitchen/default.retry
```

See https://travis-ci.org/sobolevn/git-secret

This is blocking testing any improvements to the build/release/deploy system and probably any future PR.

**Comment by joshrabinowitz** [comment]
I presume it's an upstream change in bats-core, this test passed 5 days ago. Will investigate

**Comment by joshrabinowitz** [comment]
I think this is the change in bats-core that caused the build breakage.
https://github.com/bats-core/bats-core/commit/e8a2774534c070990b4b13818ac8ddacae6009c5
