### ISSUE TITLE
Add diff command

### ISSUE THREAD

**Issue by mettjus** [sobolevn/git-secret#21]
Here again with another proposal :)

Given that secret files are .gitignored it is not clear how to detect if any of them were modified (`git diff` obviously doesn't work).
It would be very nice to be able to run `git secret diff [paths-to-files]` (or similar) to see what changes were made to a secret file (or all of them if no file paths where specified).

It could run a `git secret reveal` to tmp files, `diff` each secret in the working copy against the temporarily revealed counterpart and then remove the revealed files.

It should understand file paths passed with or without the `$SECRETS_EXTENSION` (eg. `git secret diff my-secret-file.txt` should work as well as `git secret diff my-secret-file.txt.secret`).

**Comment by sobolevn** [comment]
Great!

**Comment by sobolevn** [comment]
Well, I have implemented this feature in the current release.
