### ISSUE TITLE
Fish plugin

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/git-secret#22]
Since `git-secret` is a bash tool it is convenient to have it a plugin for your favourite shell. Right now `git-secret` does support only `zsh`-styled plugins suchs as `oh-my-zsh`, `zgen` and `antigen`.

So, the task is:
- [ ] ensure that `git-secret` works on `fish` shell (I guess it is possible to modify `Travis` build to run tests on different shells)
- [ ] write `fish`-styled plugins for `fisherman` and `oh-my-fish`

**Comment by gretel** [comment]
@sobolevn using `git-secret` as *pre-commit* hook on *fish* without missing anything or having issues.

**Comment by sobolevn** [comment]
This is no longer valid. See https://github.com/sobolevn/git-secret/issues/77
