### ISSUE TITLE
keys with no info but the email address not recognized by whoknows

### ISSUE THREAD

**Issue by brontolinux** [sobolevn/git-secret#227]
What are the steps to reproduce this issue?
-------------------------------------------
1. have a key in the keyring with no info but the email address: gpg will show the email address without the angle brackets; let's say john.smith@example.com
2. do `git secret tell john.smith@example.com`: the key will be correctly added to the keyring
3. do `git secret whoknows`: the key just added with `tell` won't appear anywhere and won't be considered for encryption

What happens?
-------------
See above. The problem seems to be due to the regexps in the script assuming the angle brackets around the email address, which is not the case if the key is generated with `gpg --quick-generate-key`, for example.

What were you expecting to happen?
----------------------------------
I expected the key to be revealed by `whoknows` and used

Any logs, error output, etc?
----------------------------
Not really, but it's easy to reproduce

Any other comments?
-------------------
None

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) 
Linux nelson 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`) 
/usr/bin/git-secret

**`git-secret` version:** (`git secret --version`) 
0.2.4

**`git` version:** (`git --version`) 
git version 2.11.0

**Shell type and version:** (`$SHELL --version`) 
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**`gpg` version:** (`gpg --version`) 
gpg (GnuPG) 2.1.18
libgcrypt 1.7.6-beta
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/bronto/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by joshrabinowitz** [comment]
Hello, @brontolinux.  I've worked up a fix for this. 

Would it be possible for you to test this issue with PR #240 and let me know if it fixes it for you?

**Comment by brontolinux** [comment]
@joshrabinowitz I was on vacation. Planning to check on this fix ASAP. Thanks!
