### ISSUE TITLE
Fix git-secret problems when using different versions of gpg (was: Wrong dependencies in documentation?)

### ISSUE THREAD

**Issue by brontolinux** [sobolevn/git-secret#228]
What are the steps to reproduce this issue?
-------------------------------------------
1. try using git-secret with a gpg version earlier than 2.1

What happens?
-------------
It doesn't work. It appears that the regexps in the script are designed to match the output of gpg v2.1 or later.

What were you expecting to happen?
----------------------------------
Either git-secret to work with gpg 1.4.20 or later, or the docs be updated to state that v2.1 or later is necessary (Docs here say gpg 1.4.20: http://git-secret.io/installation)

Any logs, error output, etc?
----------------------------
Nope

Any other comments?
-------------------
Nope

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) 
Linux nelson 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`) 
/usr/bin/git-secret

**`git-secret` version:** (`git secret --version`) 
0.2.4

**`git` version:** (`git --version`) 
git version 2.11.0

**Shell type and version:** (`$SHELL --version`) 
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**`gpg` version:** (`gpg --version`) 
gpg (GnuPG) 2.1.18
libgcrypt 1.7.6-beta
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/bronto/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by joshrabinowitz** [comment]
Hello, @brontolinux , 

What kinds of errors are you experiencing?

git-secret is tested to work with at least gpg 2.0.22 (which is shipped on centos 7), and with gpg 1.4.22 (from the package 'gpg1' on debian-latest), and with gnupg (2.2.4 from the package gpg2 on ubuntu-rolling) -- You can see the tests and version in the details of the travis-ci test builds.  

(There are known issues with interoperating _between_ different versions of gpg; see issues #136  and #208)

**Comment by brontolinux** [comment]
Hi @joshrabinowitz 

Then it could be an interoperability issue. On the laptop I have 2.1.8, as you can see, and I tested together with a colleague who was using gpg 1.4.20 on a Ubuntu 16.04, and gpg 1.4.22 from a Fedora 27.

We had the problem a couple of days ago and I didn't save the output; what I remember was that we got inconsistencies. E.g. One could do `git secret tell` on one version and `git secret whoknows` would reply consistently, while doing `git secret whoknows` on the other version would show nothing, and commands like `hide` would behave like no key was registered.

With 2.1.8 from Debian Stretch and 2.2.8 from Fedora 27's gpg2 package everything seems fine. That made me understand that v2.1+ was the requirement, and not v1.4+.

**Comment by joshrabinowitz** [comment]
@brontolinux , There's a discussion of this general issue at #136 

Our recommendation for the present time is that "it is best to use
git-secret with the same version of gpg being used by all users. 
This can be forced using SECRETS_GPG_COMMAND environment variable."

(This text is from PR #200 which is not in the released version of git-secret yet). 
You can migrate between versions of GPG by using the --export and --import commands.

Longer-term we expect to solve the GPG interoperability issue by using text formats known to work on all versions of GPG: See https://github.com/sobolevn/git-secret/blob/master/RFC/RFC001.md

**Comment by brontolinux** [comment]
When you say the same version, to which level do you consider it to be the "same"? The major version (e.g.: 2.x.x)? The minor (e.g. 2.1.x)? The full version (e.g. 2.1.8)? Depending on how deep in the version number you go, this could be a very hard requirement to fulfill.

**Comment by joshrabinowitz** [comment]
That's a fair point @brontolinux. 

I'm not an expert on gpg version interoperability but I'd suggest using gpg versions that are at least of the same major version, and probably on the same minor version too for sanity. [Then do interoperability testing to make sure everything works between the versions you've chosen.] The GPG release notes at https://www.gnupg.org/download/release_notes.html can help to figure out what versions will interoperate well. 

We have a ticket at #204 about testing interoperability between certain GPG versions, but it has not been implemented. In leiu of that, perhaps we should provide scripts to help users test git-secret between their particular versions/installs of GPG.

**Comment by brontolinux** [comment]
I believe that any requirement beyond having the same major version would be unreasonably hard.

Running on the same major version should definitely be possible, but running on the same major.minor is already problematic. Think of an environment where different distributions of Linux are used (like, in our case, Debian and Fedora), and you already have a difference (2.1 vs 2.2); then throw MacOS into the battlefield (MacOS is the system of choice of our engineers here): there is no chance that you can get those the gpg versions on those systems aligned beyond the major version at any time, unless the "vendor" does provide the packages at the same version for all the OSs that are in use in a certain project (and it's not the case with GnuPG).

Having tools to check the interoperability before jumping into the tool would definitely help, but only to a point: what if an OS upgrade wants to install a version of gpg that results in interoperability issues? Can you give up OS upgrades? Can you upgrade gpg on all other OSs? The answer is probably "no" in both cases.

I think the goal should be to guarantee interoperability at least when the major version is the same and the difference between the minor versions is 1 (e.g. interoperability between 2.0 and 2.1, or between 2.1 and 2.2, should be guaranteed). Anything stricter would probably be too tight to fulfill in any non-trivial environment.

**Comment by brontolinux** [comment]
And, one more question: what happens when one upgrades the OS and steps from, say, 2.0 to 2.2? What needs to be done to ensure that the person who upgrades can still access the repository after the upgrade? And what needs to be done to ensure that this person doesn't trash the repo for everyone else when he starts using their shiny new gpg?

**Comment by joshrabinowitz** [comment]
> Running on the same major (gpg) version should definitely be possible, but running on the same major.minor is already problematic.

In the medium term, git-secret has a plan (from @simbo1905) to largely remove dependence on the particular version of gpg installed. A solution like this one is definitely the way forward for this problem.  See: https://github.com/sobolevn/git-secret/blob/master/RFC/RFC001.md
The summary: "git-secret will move away from using the keyring format as shared storage of public keys. Instead, it will store public keys as exported keys in ASCII armor format."  

> what if an OS upgrade wants to install a version of gpg that results in interoperability issues?

Typically OS packagers arrange that updates to packages on a particular distribution (say, centos7 or ubuntu 16) are (mostly) backward compatible with the previous version on that distribution. 

So for the case of centos7, which currently packages `gnupg2-2.0.22`, I wouldn't expect a centos7 to upgrade to `gnupg2-2.1.xx` (unless I go to centos8, in which case who knows).  On the other hand if you do a major OS upgrade (say ubuntu 14 to 16 or centos 6 to 7), you could expect more significant changes between gnupg versions.

> what happens when one upgrades the OS and steps from, say, 2.0 to 2.2? 

This brings the issue full circle: git-secret currently has no mechanism for detecting/working around incompatibilities between particular gpg versions; you bring up valid points. [It may make sense to add some provisions for git-secret to detect incompatibilities, but with so many versions of gpg available in the wild, this could get a little hairy and might not be easy or effective in all situations.] https://github.com/sobolevn/git-secret/blob/master/RFC/RFC001.md is definitely the best looking way forward for this issue. 

We definitely welcome PR submissions or suggestions for git-secret.

**Comment by joshrabinowitz** [comment]
this is well documented and outside the scope of what git-secret targets
