### ISSUE TITLE
Suggestion for OSs with both gpg v1 and v2 installed

### ISSUE THREAD

**Issue by brontolinux** [sobolevn/git-secret#229]
What are the steps to reproduce this issue?
-------------------------------------------
N/A

What happens?
-------------
N/A

What were you expecting to happen?
----------------------------------
N/A

Any logs, error output, etc?
----------------------------
N/A

Any other comments?
-------------------
Just a suggestion for the docs. In OSs where both v1 and v2 of gpg are installed you may suggest in the docs to set `$SECRET_GPG_COMMAND` to `gpg2`. If gpg v1 is the default (e.g. it is Fedora v27), one would expect git-secret to work but it doesn't (see #228) and it may take some time before one finds out what the problem actually is.

What versions of software are you using?
----------------------------------------
N/A

**Comment by joshrabinowitz** [comment]
We have some of this language added to the docs in PR #200 (which was committed after the 0.2.4 release).

 I'm planning to close this as a dup of #228 see also the discussion there
