### ISSUE TITLE
build issue on alpine-latest: tasks 'Create git-secret apk package' and 'Create git-secret apk location'

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#232]
builds are failing only on alpine-latest because of error(s) with 
[run-tests.yml](.ci/integration/tasks/run-tests.yml)

For exact error messages, please see the 'alpine-latest' jobs here:
https://travis-ci.org/sobolevn/git-secret/builds/403141496
or below

**Comment by joshrabinowitz** [comment]
Error message:

TASK [Create git-secret apk package] *******************************************

fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["bash", "-lc", "cd /tmp/git-secret && make build-apk"], "delta": "0:00:00.826604", "end": "2018-07-12 14:30:15.027166", "msg": "non-zero return code", "rc": 2, "start": "2018-07-12 14:30:14.200562", "stderr": "/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- etc (LoadError)\n\tfrom /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'\n\tfrom /usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'\n\tfrom /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/lib/fpm/package/puppet.rb:5:in `<top (required)>'\n\tfrom /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'\n\tfrom /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'\n\tfrom /usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'\n\tfrom /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/lib/fpm.rb:13:in `<top (required)>'\n\tfrom /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'\n\tfrom /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'\n\tfrom /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/bin/fpm:4:in `<top (required)>'\n\tfrom /usr/bin/fpm:23:in `load'\n\tfrom /usr/bin/fpm:23:in `<main>'\nmake: *** [Makefile:100: build-apk] Error 1", "stderr_lines": ["/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- etc (LoadError)", "\tfrom /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'", "\tfrom /usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'", "\tfrom /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/lib/fpm/package/puppet.rb:5:in `<top (required)>'", "\tfrom /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'", "\tfrom /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'", "\tfrom /usr/lib/ruby/gems/2.5.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'", "\tfrom /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/lib/fpm.rb:13:in `<top (required)>'", "\tfrom /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'", "\tfrom /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'", "\tfrom /usr/lib/ruby/gems/2.5.0/gems/fpm-1.10.2/bin/fpm:4:in `<top (required)>'", "\tfrom /usr/bin/fpm:23:in `load'", "\tfrom /usr/bin/fpm:23:in `<main>'", "make: *** [Makefile:100 : build-apk] Error 1"], "stdout": "", "stdout_lines": []}
...ignoring
       
TASK [Find git-secret apk file] ************************************************
ok: [localhost]
       
TASK [Set git-secret apk location] *********************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: No first item, sequence was empty.\n\nThe error appears to have been in '/tmp/kitchen/tasks/run-tests.yml': line 53, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set git-secret {{ os_pkg_type }} location\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

to retry, use: --limit @/tmp/kitchen/default.retry

**Comment by joshrabinowitz** [comment]
@sobolevn @simbo1905 any ideas?

**Comment by simbo1905** [comment]
This looks to be "apline-latest" changes that make building the `apk` package fail. I am coming to believe that building packages on the very distros for every PR is not a good idea. We can expect that installing packages is stable (you can build on a stable major release distro and expect the package to install on the latest version) but that building packages on the very latest can and will randomly break with something that is nothing do with the logic in a PR. This harms contributions by making it "hard work" to get a PR with new logic merged. 

So I would suggest that we configure things such that we do a build that does everything on master and configure the tests that run on a PR not to run on "latest".

**Comment by sobolevn** [comment]
@simbo1905 absolutely agree.

**Comment by simbo1905** [comment]
I have added #235 about relaxing PR builds.

Team, if you happy to agree an approach for #235 I will take a look at implementing it to unblock Josh’s latest. Then I will take a look at Alpine which I have no experience with.

**Comment by simbo1905** [comment]
I have created PR #246 for the fix.

**Comment by joshrabinowitz** [comment]
Closing
