### ISSUE TITLE
release v0.2.5

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#236]
There are some changes in git-secret since 0.2.4 that I think deserve a new release. 

* we can fix the release to make sure there's one version of 0.2.4

* we now support directory names with spaces, which has been a long-standing issue people run into.  

* the documentation surrounding gpg interoperability (an issue people seem to have problems with) has been improved, and we can improve it more. [I'll take another look at git-secret's gpg-related docs to see if we can clarify things more.]

* I've set up a github 'milestone' for 0.2.5: https://github.com/sobolevn/git-secret/milestone/7

Team, what do you think? What other issues would you like to see in the milestone?, and should we prep for a 0.2.5 release?

**Comment by joshrabinowitz** [comment]
Releasing master as 0.2.5 will fix several problems people were having with 0.2.4 including:

#253 (Cannot encrypt new files unless all files are decrypted first), 
#244 (freebsd support),
#230 (git secret hide malfunctions if not run at the root of the repository), 
#226 (some commands fail when there is a space in the filename),
#254 (CONTRIBUTING.md and doc updates)

**Comment by joshrabinowitz** [comment]
@simbo1905 @sobolevn do you guys want me to work up a PR for 0.2.5? 
In particular I think we need to update CHANGELOG.mg

**Comment by sobolevn** [comment]
It would be awesome! @joshrabinowitz 

What help do you need in releasing it?

**Comment by joshrabinowitz** [comment]
@sobolevn I can prep the branch and the CHANGELOG.md but I'm not clear on the process required to actually make the release (correctly, with tags, releases for brew and apt, yum, dnf, etc). 

I'll start the PR for 0.2.5 shortly.

**Comment by sobolevn** [comment]
Hm, I should write the docs for this. Since the releases are managed in different ways on different platforms.

**Comment by simbo1905** [comment]
> @sobolevn I can prep the branch and the CHANGELOG.md but I'm not clear on the process required to actually make the release (correctly, with tags, releases for brew and apt, yum, dnf, etc).

I thought i understood the release process until I read contributing.md and saw some things that weren't familiar. We should definitely patch the docs this time.

**Comment by joshrabinowitz** [comment]
@simbo1905 @sobolevn can one of you patch the contributing.md docs in another PR? 
Alternately you can tell me what to change in comments here and I'll apply them to this PR.

**Comment by sobolevn** [comment]
I can do it on friday / weekend.

**Comment by simbo1905** [comment]
I have found that squash-and-merge of PRs creates a clean git log on the master branch while keeping the original commits on the incoming branch. If we standardised on squash-and-merge for future PRs and used the PR number in the squash then it will be way easier to see what is in each new release.

**Comment by joshrabinowitz** [comment]
Just a bump to push these along. Remaining issues above are:

* update CONTRIBUTING.md 
* release 0.2.5

We keep getting reports about silent failures with expired and revoked keys in versions 0.2.4 and before. It would be great to get 0.2.5 released, then we could get downstream maintainers to package 0.2.5.

**Comment by joshrabinowitz** [comment]
I think we simultaneously released v0.2.5
 https://github.com/sobolevn/git-secret/releases
Also I see a tag for 0.2.5 and v0.2.5

**Comment by sobolevn** [comment]
I have removed my tag, it was incorrect anyway.

**Comment by sobolevn** [comment]
The final step is to submit the formula to `brew`: https://github.com/Homebrew/homebrew-core/pulls
And we are done! 

Does anyone especially want to do it? If not, I can submit it tomorrow.

**Comment by joshrabinowitz** [comment]
@sobolevn I took a crack at it: https://github.com/Homebrew/homebrew-core/pull/36041

**Comment by delmendo** [comment]
I noticed you put up the new package for debian/ubuntu - but your package manifests don't list it. Can you update that so that 0.2.5 gets intalled automatically :)

**Comment by joshrabinowitz** [comment]
@delmendo is your note a duplicate of #312? 
(currently debian only packages 0.2.3, we are seeking to get it updated to 0.2.5)
