### ISSUE TITLE
debug code in git-secret remove

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#237]
If you remove a file with git-secret remove, it outputs what seems to be a debug line with the code:

echo "$item -> $normalized_path -> $path"

See https://github.com/sobolevn/git-secret/blob/master/src/commands/git_secret_remove.sh#L36

**Comment by sobolevn** [comment]
Yeap, that should be removed.

**Comment by joshrabinowitz** [comment]
resolved in #239
