### ISSUE TITLE
Add option to `reveal` command to always overwrite the existing files without asking

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/git-secret#24]
`gpg` asks something about overriding the existing files when calling `reveal`.

I guess, that `-f` (force) flag will do the thing.

**Comment by sobolevn** [comment]
I have implemented it already in: https://github.com/sobolevn/git-secret/commit/8206de7ebb5a85a328445a63669cb9cdfb69d056

If you would like to help, it is kindly welcome! 
Current objectives are:
- https://github.com/sobolevn/git-secret/issues/21
- https://github.com/sobolevn/git-secret/issues/22

**Comment by transcedentalia** [comment]
Do you have any plans to merge the develop branch to the master soon?

**Comment by sobolevn** [comment]
Yes, probably on sunday.

**Comment by transcedentalia** [comment]
Thanks.

**Comment by sobolevn** [comment]
@transcedentalia done!
