### ISSUE TITLE
change to master branch development model

### ISSUE THREAD

**Issue by simbo1905** [sobolevn/git-secret#249]
CONTRIBUTING.md says to send PRs against `develop` branch. I hadn't really internalised that so advised the person contributing #247 to send a PR against master as develop was broken with the problem was fixed on master. 

IMHO the move to releasing from `/v.*/` tags seems like an opportunity to simplify things. People can send PRs against `master` and we can release a particular sha of master anytime we want. 

I propose that we remove the advice to send PRs against develop (forcing them to have to refresh that from master which adds complexity).

**Comment by simbo1905** [comment]
@sobolevn @joshrabinowitz ?

**Comment by sobolevn** [comment]
@simbo1905 totally agree. This three branches thing did not work well at all.

I can delete `develop` if there's nothing useful in it.

**Comment by joshrabinowitz** [comment]
I go along with the buildmasters. Sounds fine.

**Comment by joshrabinowitz** [comment]
Shall we close this, @simbo1905 @sobolevn ?

**Comment by simbo1905** [comment]
Closing after checking the docs are now talking about master development.
