### ISSUE TITLE
How to install on Windows?

### ISSUE THREAD

**Issue by fede91it** [sobolevn/git-secret#252]
Hi

How I should install git-secret on Windows OS?

**Comment by sobolevn** [comment]
Hi, @fede91it! Thanks for bringing this up.

I am not a windows user, but there were reports about `git-secret` working on windows some time ago:
- https://github.com/sobolevn/git-secret/issues/40
- https://github.com/sobolevn/git-secret/issues?utf8=%E2%9C%93&q=is%3Aissue+windows

I am pretty sure that `git-secret` will work on ubuntu sub-system.
I would also recommend to try the "Manual" installation method from here: http://git-secret.io/installation

Things you can help us with:
0. provide more OS information (version, service pack, sub-system info, etc)
1. report back if any of these methods worked for you or not
2. super-duper-feature: provide docs for windows folks who will suffer the same problem

Thanks for using `git-secret`. I will appreciate any feedback from you.

**Comment by joshrabinowitz** [comment]
@fede91it: as @sobolevn says, we've had reports about git-secret working well with windows 10 using the "Windows Subsystem for Linux" and Ubuntu <https://docs.microsoft.com/en-us/windows/wsl/install-win10>. 

If you detail here how git-secret does/doesn't work for you on windows I'll add documentation about it to git-secret (unless you beat me to it!). Thanks for filing this issue.

**Comment by joshrabinowitz** [comment]
I was just able to get git-secret's self-tests to pass after cloning the git-secret repo on the Ubuntu system on Windoes 10.

**Comment by fede91it** [comment]
Thank you!
