### ISSUE TITLE
Add per repository config option for SECRET_EXTENSION

### ISSUE THREAD

**Issue by gitmalet** [sobolevn/git-secret#266]
It would be great to have an option in some config file (preferably a tracked file inside `.gitsecrets`) to set the `SECRET_EXTENSION` for this repository.

What were you expecting to happen?
----------------------------------
The extension for git-secret managed files is set to the configured extension for the specific repository, overriding the environment variable.

**Comment by sobolevn** [comment]
@archmalet that's an interesting idea indeed! 

For example, for the next project I have decided to use custom secret files' extension.
So, now all other developers should also specify this variable somewhere in the code/docs/build tools. Keeping inside our own `.gitsecrets/` directory might help.

**Comment by robinleander** [comment]
Interesting proposal! I've went ahead and implemented a possible solution for this!

Please tell me what you think!
