### ISSUE TITLE
make git-secret discern between ignored files and other .gitsecret/* issues

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#275]
As @nozzlegear and @snoopdouglas refer to in comments from Jan 3 2018 and Nov 3 2018 in #105 , git-secret can report the error `.gitsecret folder is ignored. abort`, when that is not the actual error.

To reproduce:
* install git-secret
* setup a new repo with git-secret
* remove read permissions from the files in .gitsecret: `chmod 000 .gitsecret/pubring.kbx`
* run `git-secret whoknows`. 

What happens:
* you get the error  `.gitsecret folder is ignored. abort.`

What were you expecting to happen?
* an error message that describes the issue more accurately, such as 'can't read files in .gitsecret'

**Comment by mihakrajnc** [comment]
Oh boy did you just end my suffering! Been scratching my head for hours trying to figure this out, turns out it was the permissions!

+1 for getting this fixed asap.

**Comment by joshrabinowitz** [comment]
I believe this was fixed by PR #518
