### ISSUE TITLE
You did not specify a user ID

### ISSUE THREAD

**Issue by Benjamin-Dobell** [sobolevn/git-secret#276]
What are the steps to reproduce this issue?
-------------------------------------------
1. Execute `git secret hide`

What happens?
-------------
I receive the prompt:

```
You did not specify a user ID. (you may use "-r")

Current recipients:

Enter the user ID.  End with an empty line:
```

once for every file that is to be encrypted. i.e. `git-secret` is not setting the recipients, instead I have to do it manually.

What were you expecting to happen?
----------------------------------
git-secret to automatically encrypt all `git secret add`'d files with all `git secret tell`'d GPG recipients.

Any logs, error output, etc?
----------------------------
As above

Any other comments?
-------------------
N/A

What versions of software are you using?
----------------------------------------
**Operating system:** macOS 10.13.6 (17G65) - Darwin Kernel Version 17.7.0

**`git-secret` path:** /usr/local/bin/git-secret

**`git-secret` version:** 0.2.4

**`git` version:** git version 2.17.1 (Apple Git-112)

**Shell type and version:**
 * zsh 5.4.2 (x86_64-apple-darwin17.3.0)
 * GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

**`gpg` version:**

```
gpg (GnuPG) 2.2.11
libgcrypt 1.8.4
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/ben/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by joshrabinowitz** [comment]
@Benjamin-Dobell Can you retest with the current development version of git-secret and let us know the results?

Also if you could provide all the git-secret commands needed to reproduce the issue that would be very helpful.

**Comment by Benjamin-Dobell** [comment]
@joshrabinowitz It was when I reached step 5 of the official [usage instructions](http://git-secret.io/) that I ran into this, after adding 7 files. 

*However*, after testing `master` it's all good:

```bash
$ git secret hide
done. 7 of 7 files are hidden.
```

My apologies for not testing `master` already. I'm just a little bit weary to use pre-release software for encryption/decryption purposes, in case of data loss. However, it seems to be working just fine, so I'll happily close this issue.

**Comment by joshrabinowitz** [comment]
Thank you for looking into that @Benjamin-Dobell , we really appreciate it. 

@simbo1905 @sobolevn what do you guys think about releasing a new version of git-secret?

**Comment by joshrabinowitz** [comment]
Also I suspect this issue may have been caused by #227 (keys with no info but the email address not recognized) which is fixed by #240 (fix for keys with only emails, and no usernames)

**Comment by Benjamin-Dobell** [comment]
@joshrabinowitz That seems about right to me, my uid for my secret is simply an email address i.e.

```
uid           [ultimate] benjamin.dobell@g_NO_SPAM_FOR_ME_PLEASE_a.com.au
```

Honestly, I probably ought to fix that!

**Comment by simbo1905** [comment]
+1 on releasing fixed master

**Comment by joshrabinowitz** [comment]
@Benjamin-Dobell technically (according to gpg) that is an acceptable uid for the key. 

So I think it's important that git-secret accept that as a UID, because it's very unlikely gpg is going to change.
