### ISSUE TITLE
git-secret.io SSL

### ISSUE THREAD

**Issue by Benjamin-Dobell** [sobolevn/git-secret#279]
What are the steps to reproduce this issue?
-------------------------------------------
1. Visit https://git-secret.io

What happens?
-------------
Browser displays an invalid certificate error.

What were you expecting to happen?
----------------------------------
The git-secret homepage to load via SSL.

Obviously given it's a static website this isn't the end of the Earth. Basically I just accidentally ran into this as I incorrectly shared a https link.

Any logs, error output, etc?
----------------------------
N/A

Any other comments?
-------------------
TLDR; The DNS A record should point to:

- 185.199.108.153
- 185.199.109.153
- 185.199.110.153
- 185.199.111.153

The SSL certificate is currently configured for *.github.io, however it looks like Github have supported custom domains in partnership with Let's Encrypt since earlier this year:

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Should be reasonably easy to fix, unfortunately it's not the kind of thing I can submit a PR for 😄

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …

N/A

**Comment by sobolevn** [comment]
@Benjamin-Dobell thanks! I will have a look at it on weekend.

**Comment by joshrabinowitz** [comment]
@sobolevn anything I can do to help with this? 

Seems especially egregious for this project's web site [in particular] to not use https

**Comment by sobolevn** [comment]
I will have to figure out how this github/pages/letencrypt things work.
Pretty sure to accomplish this task soon.
<img width="752" alt="2018-12-04 16 43 26" src="https://user-images.githubusercontent.com/4660275/49445828-d9e37700-f7e3-11e8-852f-84d554dad1c2.png">

👍

**Comment by joshrabinowitz** [comment]
Any movement on this? Any way I can help @sobolevn ?

**Comment by sobolevn** [comment]
Configured! 

```
» dig git-secret.io +noall +answer

; <<>> DiG 9.10.6 <<>> git-secret.io +noall +answer
;; global options: +cmd
git-secret.io.		10256	IN	A	185.199.109.153
git-secret.io.		10256	IN	A	185.199.110.153
git-secret.io.		10256	IN	A	185.199.111.153
git-secret.io.		10256	IN	A	185.199.108.153
```

And it look like the process is now finished. But, it is not working at. Github says that it might take an hour to be ready. 


<img width="751" alt="2019-01-01 19 14 18" src="https://user-images.githubusercontent.com/4660275/50574440-bbc86100-0df9-11e9-9346-07096a55af4d.png">

**Comment by jmhardison** [comment]
Confirming it looks good for me. Correctly being forced over to https when trying http, and seeing a lets-encrypt cert issued.
👍

**Comment by sobolevn** [comment]
<img width="804" alt="2019-01-01 20 43 49" src="https://user-images.githubusercontent.com/4660275/50575051-fafcaf00-0e05-11e9-8302-64378a431c51.png">
Yes, it works! Thanks everyone!
