### ISSUE TITLE
Feature request: better messaging about expired keys

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#283]
If gpg encounters an expired key while being used in git-secret, it can issue confusing error messages.

It would be nice to directly detect expired keys.

People have also requested features to show and maybe even warn users about keys and their expiration dates.

(_Edit: all above issues also apply to revoked keys_ EditToTheEdit: Except key revocation requires network access and so should be handled differently and in a separate issue as we may not even have network access when running git-secret)

See also: #281 regarding expired keys.

From PR #262:

joshrabinowitz wrote:
>Current master will issue an erorr if any file failed to decrypt (which technically fixes #238 'Git 
>secret ignoring gpg issues with expired public key') but it won't give you any hint why.

>I'm thinking of adding a patch to git-secret that informs users about keys that expire.
>My first thought is to always mention the expiration date of any keys with expiration dates

adamgotterer wrote:
>whoknows could also list the expirations or days until expiration by default or with a flag to 
>show/hide. Could also have a flag for "expiring soon".

**Comment by joshrabinowitz** [comment]
* whoknows now has a -l option which shows key expirations.
* we should probably still detect when we attempt to use expired (or 'soon' expiring) keys so we can tell user

**Comment by joshrabinowitz** [comment]
See also: #290, 'cannot encrypt for a certain set of keys'

**Comment by ajayramezh** [comment]
Any latest update on this feature, I am planning to work on this.

**Comment by joshrabinowitz** [comment]
Hello, @ajayramezh:
There are no more recent updates, the last updates to this topic were in PRs #626 and #287. 
We look forward to seeing your changes.

**Comment by joshrabinowitz** [comment]
Closed as 'wontfix', see #516

**Comment by joshrabinowitz** [comment]
Since it looks like we're going to merge  #553, I'm re-opening this because users are likely to be confused if `git secret tell` silently ignores expired keys.

**Comment by joshrabinowitz** [comment]
Note that merged PR #518 for issue #516 shows error messages from gpg when it returns an error.

#553 also shows better messaging about expired keys by warning when unusable keys are skipped.

**Comment by joshrabinowitz** [comment]
Closed by #553
