### ISSUE TITLE
Can't remove secrets in subdirectories

### ISSUE THREAD

**Issue by tjarvstrand** [sobolevn/git-secret#30]
Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.

What are the steps to reproduce this issue?
-------------------------------------------
1. git secret add dir/file
2. git secret remove dir/file

What happens?
-------------
```sed: can't find label for jump to `ile/d'```

What were you expecting to happen?
----------------------------------
```removed from index.```

Any other comments?
-------------------
How do I manually remove the secret?

What versions of software are you using?
----------------------------------------
**Operating system:** Ubuntu 15.10

**`git-secret` version:** 0.1.2

**Shell type and version:** bash-4.3.42

**Comment by sobolevn** [comment]
Thanks for your feedback. Could please check if the `0.2.0` version fixes it? 
Here's the original issue: https://github.com/sobolevn/git-secret/issues/23

**Comment by sobolevn** [comment]
Does [v0.2.0](https://github.com/sobolevn/git-secret/releases/tag/v0.2.0) solves your issue?

**Comment by sobolevn** [comment]
Closing as fixed.
