### ISSUE TITLE
docs say travis will push to bintray on each merge to master, but that doesn't happen

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#300]
What are the steps to reproduce this issue?
-------------------------------------------
* look at https://bintray.com/sobolevn/rpm/git-secret#

What happens?
-------------
* note that rpm has not been updated since  2018-06-09T12:12:08.000Z 

What were you expecting to happen?
----------------------------------
* see new data as per docs at https://github.com/sobolevn/git-secret/blob/master/CONTRIBUTING.md#travis-releases

>    "When creating a commit inside master branch, 
>    travis on successful build will publish new deb and 
 >   rpm packages to bintray."

**Comment by joshrabinowitz** [comment]
Docs about this are updated in PR #301

**Comment by hurricanehrndz** [comment]
There should be a deploy when the tag matches a pattern
```
condition: "$TRAVIS_TAG =~ ^v.*$ && $GITSECRET_DIST == rpm"
```
No matter the branch. The last time this was true was Jun 10, 2018. So it does seem to work.

**Comment by joshrabinowitz** [comment]
I think the docs are now correct at #301 .
 Please let me know if you are cool with merging #301  when the build is fixed.

**Comment by joshrabinowitz** [comment]
we see the rpm and deb on bintray for 0.2.5
