### ISSUE TITLE
submit git-secret for inclusion in EPEL/fedora

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#315]
I think git-secret should be considered for inclusion into EPEL / fedora:

Someone would have to go through this process, or already have gone through it. 

https://fedoraproject.org/wiki/Join_the_package_collection_maintainers

Volunteers sought!

**Comment by joshrabinowitz** [comment]
@hurricanehrndz is this something you know how to do?

**Comment by gombosg** [comment]
Hi, I just stumbled upon this. I'm making the specfile and will submit it for review soon.

**Comment by gombosg** [comment]
Yay: https://bugzilla.redhat.com/show_bug.cgi?id=1685270

**Comment by sobolevn** [comment]
@gombosg awesome 👍

**Comment by joshrabinowitz** [comment]
Yes thank you @gombosg ! 

We just got feedback on https://bugzilla.redhat.com/show_bug.cgi?id=1685270 , things look pretty good for git-secret but we got some feedback:

````
- Not needed:

rm -rf $RPM_BUILD_ROOT

 - there's a zsh completion script git-secret.plugin.zsh, install it 
   (don't forget to own the dirs)

 - Use a  better name for your archive:
Source0: https://github.com/sobolevn/%{name}/archive/v%{version}/%{name}-%{version}.tar.gz
````

I'll write up issues for the above items.

Also git-secret was failed on one thing:
  `[!]: Uses parallel make %{?_smp_mflags} macro.`
Not sure what to do about this.

**Comment by gombosg** [comment]
That was some quick feedback fortunately. :smile: These are probably only my packaging issues so no need to create separate issues here if they don't affect the upstream package. I'm going to correct them and then we're all good.

**Comment by joshrabinowitz** [comment]
@gombosg ok sounds great! Feel free to close the above bugs 'per #315' after they're corrected, or let us know if some change is required in git-secret.

**Comment by gombosg** [comment]
I can't close the bugs because I didn't open them and I don't have maintainer rights here. :smile: 
Corrected the issues, you can delete the ZSH installer later since it's deprecated and apparently confused package reviewers, too.

**Comment by joshrabinowitz** [comment]
@gombosg all sounds good. 

Can you please leave a comment in each bug above that's still open and should be closed, requesting we close (ideally with a link to the fix), and I'll close them? 

Want to make sure I don't close them prematurely. Thank you!

**Comment by gombosg** [comment]
Okay, so package approved, built for rawhide (rolling "next" release), here are the [F29](https://bodhi.fedoraproject.org/updates/FEDORA-2019-962eb8fe28) and [F30](https://bodhi.fedoraproject.org/updates/FEDORA-2019-7845890e44) updates.

The updates will be approved after 7 days or if enough people test it and give some good karma at the above links. :slightly_smiling_face: 

As for EPEL, I never used RHEL or CentOS but if the package works OK in Fedora I might simply request a branch for EL7, but for some weird reason the scratch build [fails](https://koji.fedoraproject.org/koji/taskinfo?taskID=33192577) there - not the build but setting up the environment so it may not be a packaging issue. I'm looking into it.

**Comment by joshrabinowitz** [comment]
@gombosg what should we do to test it-- just download and install the rpm, and try it out, or more?

I have set up fedora 29 and 30 VMs to test it out with.

**Comment by gombosg** [comment]
Haha, awesome. Well, just directly install the RPM from the above link or after enabling the `updates-testing` repo. You can test if it encrypts a file, opens the manpage etc. More instructions [here](https://fedoraproject.org/wiki/How_to_test_updates#Steps_to_follow).

It needs 3 karma (3 good test results) to progress, but after 7 days it's automatically approved. Nevertheless, testing never hurts :slightly_smiling_face: 

I'm excited since I'm a new packager and this is my 2nd package for Fedora.

**Comment by joshrabinowitz** [comment]
Hello @gombosg . I see from https://rpms.remirepo.net/rpmphp/zoom.php?rpm=git-secret that git-secret is in fedora f29 and f30 'testing', and the 'devel' branch.  This is exciting progress.

Let us know if there's anything we can do to help move git-secret towards mainline acceptance (I did add one 'karma' point).

Is there a doc that explains the process of a package getting out of 'testing'? I looked but couldn't find one.  
Thank you again for helping us get to this point!

**Comment by gombosg** [comment]
Yep, don't worry I'm taking care of things. 
F29 is pushed to [batched](https://fedoraproject.org/wiki/Bodhi#Package_States) which means it'll go out with the next batch update (today or tomorrow).
There was some bug with the F30 update, it might take a few more days, but F30 is only beta anyway. I'll ping here when it's all done and the bug can be closed. :slightly_smiling_face:

**Comment by joshrabinowitz** [comment]
That's great, @gombosg . What's the story with getting into EPEL?

**Comment by gombosg** [comment]
Once git-secret is in the main Fedora repos and we see that it's OK, I'll request an EPEL branch and do koji builds for it. Then we'll all test it in CentOS VMs to see if it's actually working. :slightly_smiling_face:

**Comment by gombosg** [comment]
Type git-secret into a Fedora command line and now the package should install. I suggest waiting a few weeks for some test input from users, then go for EPEL.

**Comment by gombosg** [comment]
I have requested EPEL branches, here are some scratch builds - worked for me in a VM, testing is welcome!
http://koji.fedoraproject.org/koji/taskinfo?taskID=36829936
http://koji.fedoraproject.org/koji/taskinfo?taskID=36829941

**Comment by gombosg** [comment]
Ok, here are the Bodhi updates:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-2261827101
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-5578d0c2fa
Enjoy!

**Comment by gombosg** [comment]
It's also in EPEL now! For EL7 and EL8.
https://apps.fedoraproject.org/packages/git-secret

**Comment by sobolevn** [comment]
Awesome! Thanks a lot, @gombosg! 🎉
