### ISSUE TITLE
submit git-secret for inclusion in FreeBSD Ports

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#316]
I think git-secret should be considered for inclusion into FreeBSD:

See: https://bitbucket.org/koobs/ports
(Edit: See also: https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/)

**Comment by lrosenman** [comment]
Why don't you generate a port and submit it via our (FreeBSD) bugzilla?

It's not hard, if I can *HELP*, ping me.

**Comment by mvanbaak** [comment]
You are missing a file ```pkg-plist```

More info can be found here: https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/book.html#plist

**Comment by joshrabinowitz** [comment]
@mvanbaak @lrosenman here's where I'm at now:

### Makefile

````
# $FreeBSD$

PORTNAME=       git-secret
DISTVERSION=    0.2.5
CATEGORIES=     security
LICENSE=	MIT
#MASTER_SITES=    https://github.com/sobolevn/git-secret/archive/
USE_GITHUB=    yes
GH_ACCOUNT=    sobolevn
GH_PROJECT=    git-secret
GH_TAGNAME=    94d5ae4

SCRIPTS=	git-secret

#RUN_DEPENDS=	bash:shells/bash gpg2:security/gnupg gawk:lang/gawk
# if I enable above line, I get failures from texinfo

MAINTAINER=    mail@sobolevn.me
COMMENT=    A bash-tool to store your private data inside a git repository.

.include <bsd.port.mk>
````

### cat pkg-plist
````
bin/git-secret
share/man/man7/git-secret.7
share/man/man1/git-secret-add.1
share/man/man1/git-secret-clean.1
share/man/man1/git-secret-changes.1
share/man/man1/git-secret-hide.1
share/man/man1/git-secret-usage.1
share/man/man1/git-secret-cat.1
share/man/man1/git-secret-whoknows.1
share/man/man1/git-secret-init.1
share/man/man1/git-secret-reveal.1
share/man/man1/git-secret-killperson.1
share/man/man1/git-secret-remove.1
share/man/man1/git-secret-list.1
share/man/man1/git-secret-tell.1
````

`distinfo` and `pkg-descr` are the same as before.

Clearly there's more needed. Assistance welcome.

**Comment by mvanbaak** [comment]
The main problem is the way ```make install``` is implemented in git-secret's Makefile.

There are two options:
- Fix the Makefile to not use that shellscript to install the files
- Define your own install target in the port Makefile to install the files instead of running ```make install``` in the source

**Comment by mvanbaak** [comment]
Also, make sure to install the FreeBSD package ```port-authoring-tools``` and run ```portlint``` in the port directory. Your Makefile needs some work.

Good luck!

PS: A 'fixed' version of your Makefile so portlint is happy:


```
# $FreeBSD$

PORTNAME=       git-secret
PORTVERSION=    0.2.5
CATEGORIES=     security

MAINTAINER=     mail@sobolevn.me
COMMENT=        Bash tool to store your private data inside a git repository

LICENSE=        MIT

#RUN_DEPENDS=   bash:shells/bash gpg2:security/gnupg gawk:lang/gawk
# if I enable above line, I get failures from texinfo

USE_GITHUB=     yes
GH_ACCOUNT=     sobolevn
GH_PROJECT=     git-secret
GH_TAGNAME=     94d5ae4

.include <bsd.port.mk>
```


(Make sure to use TABS between the = and the value)

**Comment by joshrabinowitz** [comment]
@mvanbaak @lrosenman
I've got it working, seeking feedback. I've put the code into a github PR just for convenience.

You can see the Makefile and pkg-* files here:
https://github.com/joshrabinowitz/freebsd-ports/pull/1/files

And you can see the current output of 'stage', 'package', 'install', etc here:
https://github.com/joshrabinowitz/freebsd-ports/blob/4d6f3549af2310aeee0423eaf335122f33e46167/security/git-secret/README.md

Thanks for your feedback so far. Any tips for further changes/improvements?

**Comment by joshrabinowitz** [comment]
Submitted to freebsd ports: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235056

**Comment by joshrabinowitz** [comment]
This is complete. git-secret is in freebsd ports:
https://svnweb.freebsd.org/ports/head/security/git-secret/

 and has been mentioned in freshports:
https://www.freshports.org/security/git-secret/
