### ISSUE TITLE
release 0.3.0, because in 0.2.5 'new, backwards compatible functionality is introduced to the public API'

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#318]
As per https://semver.org/#spec-item-7 , 0.2.5 should probably have been released as 0.3.0 since " new, backwards compatible functionality is introduced to the public API" 

Specifically, whoknows has a -l option, and reveal and hide have new -P and -F options

See: https://semver.org/#spec-item-7

````
Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards 
compatible functionality is introduced to the public API. It MUST be 
incremented if any public API functionality is marked as deprecated. It 
MAY be incremented if substantial new functionality or improvements 
are introduced within the private code. It MAY include patch level 
changes. Patch version MUST be reset to 0 when minor version 
is incremented.
````

**Comment by sobolevn** [comment]
Yes, absolutely agree.

**Comment by simbo1905** [comment]
Okay I will try to get #411 updated in a few hours so that we can merge that to test drive it on this release.

**Comment by joshrabinowitz** [comment]
According to #225 , `-i` should become the default for `git secret add` before we cut the official 0.3.0

**Comment by joshrabinowitz** [comment]
I think this means we're ready to cut a 0.3.0 release.

@simbo1905 can you make some sort of 0.3.0 preview release?

**Comment by simbo1905** [comment]
@joshrabinowitz i am not sure what you mean. my understanding is that to do the release you just apply the v0.3.0 tag and that will kick off the deploy steps for the rpm, the deb and create a draft github release. i don't think that we have automated the brew release yet so someone will have to do that. the draft github release will only be visible to collaborators so one of us will have to check and possibly edit it before publishing it.

**Comment by joshrabinowitz** [comment]
@simbo1905 ok thanks for clarifying!

**Comment by gtback** [comment]
I believe that Rule 7 doesn't really apply, since it's only for `x > 0`. Since `git-secret` is still < 1.0, feel free to do whatever 😁 	

Of course, there's no reason *not* to release as 0.3.0 to indicate all the new functionality in 0.2.5.

**Comment by joshrabinowitz** [comment]
I'm planning to release 0.3.0 soon.

**Comment by joshrabinowitz** [comment]
pre-release here: https://github.com/sobolevn/git-secret/releases/tag/v0.3.0
Please take a look and let me know if all is good @sobolevn / @simbo1905 

CONTRIBUTING.md says:
````
- after the commit is successfully created it will also trigger `make build-gh-pages` target on `post-commit` hook, which will push new manuals to the [git-secret site][git-secret-site]. And the new `git` tag will be automatically created if the version is changed:
````

But the post-commit hook fails for me with:

````
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected.
To github.com:sobolevn/git-secret.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:sobolevn/git-secret.git'
````

**Comment by sobolevn** [comment]
@joshrabinowitz hm, I guess the reason is that we had this setting:
<img width="741" alt="Снимок экрана 2019-09-18 в 22 53 38" src="https://user-images.githubusercontent.com/4660275/65181212-3b20c200-da67-11e9-9451-97bf4f74a886.png">

I have temporary removed it, so we can make a release. Later we can switch in back on.

Thanks a lot for your hard work and `0.3` release!
