### ISSUE TITLE
README misses step of 'manual' installation - build

### ISSUE THREAD

**Issue by velimir0xff** [sobolevn/git-secret#32]
What are the steps to reproduce this issue?
-------------------------------------------
1. `$ git clone https://github.com/sobolevn/git-secret.git git-secret`
2. `$ cd git-secret`
3. `$ sudo PREFIX="/usr/local" make install`

What happens?
-------------
```shell
cp: cannot stat ‘<cwd>/git-secret/git-secret’: No such file or directory
Makefile:24: recipe for target 'install' failed
make: *** [install] Error 1
```

What were you expecting to happen?
----------------------------------
```shell
$ sudo PREFIX="/usr/local" make install
Installed git-secret to /usr/local/bin/git-secret
```

**Comment by sobolevn** [comment]
Oh, indeed. The `make build` step is missing. Thank you!
