### ISSUE TITLE
Rethink internal 'design' of git-secret

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#333]
There's some things about git-secret's build system that are weird 
(one packager called git-secret 'very badly designed')

Let's make a list of things that could be clearer/simpler/more consistent with typical packaging:

* don't: append multiple files together from src/ to create a single git-secret script
** If we're going to append all the files together anyway, perhaps we should just have them that way in git

* setting up the temp directory used for testing git-secret
** if you try to run the git-secret tests manually from the git checkout (IE without using the Makefile), everything goes haywire

* if a test fails, a weird string of 'find' errors might get output, see #334 

* other things? Ideas for improved architecture/packaging of git-secret welcome.

**Comment by sobolevn** [comment]
Maybe we can ask @jirutka directly about what can be improved? 
Feedback is always a good thing.

**Comment by joshrabinowitz** [comment]
See also https://wiki.debian.org/UpstreamGuide (mentioned in #312 )

**Comment by joshrabinowitz** [comment]
I think one thing people think is weird is concatenating the sources together into git-secret
