### ISSUE TITLE
Better error message for non-public gpg key

### ISSUE THREAD

**Issue by hypery2k** [sobolevn/git-secret#341]
What are the steps to reproduce this issue?
-------------------------------------------
1. git add ...
2. git secret hide

What happens?
-------------
secret not created.
Still having my textfile ansible/secrets.yml

What were you expecting to happen?
----------------------------------
A file `ansible/secrets.yml.secret` should be created

Any logs, error output, etc?
----------------------------
```
git-secret: abort: problem encrypting file with gpg: exit code 2: ansible/secrets.yml
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating system:** macOS 10.14.2

**`git-secret` path:**/usr/local/bin/git-secret

**`git-secret` version:** 0.2.5

**`git` version:** git version 2.20.1

**Shell type and version:** GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

**`gpg` version:** gpg (GnuPG) 2.2.12

**Comment by sobolevn** [comment]
Thanks for the bug report!

Can you please provide some insights about:
1. type and size of your key
2. does regular `gpg` encrypt and decrypt of files work

**Comment by hypery2k** [comment]
sorry, was my fault. Had a user with a non-public PGP key.
But maybe you can create a more meaningful error message for that case.

**Comment by sobolevn** [comment]
@hypery2k no worries! 

I think that providing a better error message is always a good thing! Let's do it.
What would you accept as a "good message" in this particular case?

**Comment by hypery2k** [comment]
I thinks something like "Missing public key for at least one entry"?

**Comment by joshrabinowitz** [comment]
How about we have the -v flag to 'hide' show the output from the gpg encryption command at https://github.com/sobolevn/git-secret/blob/master/src/commands/git_secret_hide.sh#L168 ?

Currently we always discard stdout and stderr output from GPG when hiding files. Presumably gpg is outputing some sort of error message that we're redirecting to /dev/null in this case

**Comment by joshrabinowitz** [comment]
`git-secret` now has a -v option (and a corresponding env var, SECRETS_VERBOSE) to enable verbosity and show the output from gpg, so I'm closing this ticket. There is a case to argue that we should show the output from gnupg any time it returns a failure code, but this is not how the code works now (and would be something of a hassle to code up in bash).
