### ISSUE TITLE
html docs are out of date

### ISSUE THREAD

**Issue by simbo1905** [sobolevn/git-secret#344]
The following URL has a publish date of Feb 2017: 

https://git-secret.io/git-secret-hide

Running `man git-sectet-hide` shows more flags (e.g., `-m`) than published on the website.

**Comment by joshrabinowitz** [comment]
@simbo1905 I think this is fixed. Please confirm and close or comment! Thank you.

**Comment by simbo1905** [comment]
Fixed.
