### ISSUE TITLE
Don't depend on network during builds (re: bats-core)

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#377]
Debian 'Upstream Developers Guide' <https://wiki.debian.org/UpstreamGuide#Your_Build_System> says:

* No Downloads- You should never assume that Internet access is available during building. 

But in our build process, `make test` might fetch a git clone of `bats-core` 

We should to change code to conform to the Debian recommendation. I think a good solution is to 

1) include vendor/bats-core in the git-secret tree, well documented, so we don't have to download it live at 'make test' time.

2) If the system we're on packages bats-core (I'm not aware of one that does), we ignore vendor/bats-core in favor of the one packaged by the system.

**Comment by sobolevn** [comment]
Is it a recommendation or a strict rule?
Are there any other stages where we can run `git pull`?

**Comment by joshrabinowitz** [comment]
My understanding is that Debian wants to be able to ensure duplicate-able builds, and if a build (or it's test, which is desired at build-time) needs to reach out to github (or whatever), that introduces a build-time/test-time unknown. 

My reading is also that no, there is not another stage we can depend on network access for a `git pull`.

[Debian "guarantees that every binary package can be built from the available source packages for licensing and security reasons" so reaching out at build-time would mean we'd be precluding tests at build-time on Debian.]

My reading is that it's not a hard requirement that we run tests at build time, but the doc says 'Have an automatic test suite to run during build time', which shows a strong preference that we do.

Another win is that debian could add git-secret to their CI system at https://ci.debian.net/

My understanding is that the more we conform to the debian upstream guide the more likely we are to get git-secret updated in Debian 'testing' and promoted to 'stable'.

**Comment by sobolevn** [comment]
So, you are suggesting to use `bats` as a submodule for this reason?

**Comment by joshrabinowitz** [comment]
I suggest we import the bats-core v1.1.0 tree into `vendor/bats-core` verbatim (not as a git submodule technically) -- this is described at https://lwn.net/Articles/277132/ , "Internal Libraries", which is linked from the debian upstream guide and says

"For this reason, a good compromise between the needs of the original authors and the needs of the distributions is to treat internal copies of libraries as untouchable, thus disallowing any changes in its interface or behaviour." There's more details about their thinking at that link.

Then, if we want to upgrade bats-core after import we replace the files in vendor/bats-core.

**Comment by sobolevn** [comment]
Sounds fair. The intent is clear. Let's do it! And hope to be promoted in Debian. This is huge! 🚀

**Comment by joshrabinowitz** [comment]
Note that this issue is for #312 'get git-secret updated in debian'
