### ISSUE TITLE
Add `CentOS` to the containers list in `.docker/rpm`

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/git-secret#38]
It is just pretty much the same as `fedora` one.
It is also needed to add it to the `.tavis.yml` to be tested.

**Comment by sobolevn** [comment]
See: https://github.com/sobolevn/git-secret/blob/develop/.docker/rpm/fedora/Dockerfile
And: https://travis-ci.org/sobolevn/git-secret/builds/138178890

**Comment by sobolevn** [comment]
See this job https://travis-ci.org/sobolevn/git-secret/jobs/205525427

**Comment by sobolevn** [comment]
I guess it can be related to this bug: https://github.com/sobolevn/git-secret/issues/46
`gpg` version needs to be checked.

**Comment by hurricanehrndz** [comment]
@sobolevn,

I would close this. In order for CentOS to be supported appropriately it needs a git version that is newer than the one available. If you wish to have CentOS supported the `_check_ignore` function would need to be re-written as to not use features introduced in version 1.8.5/1.9. Current version is 1.8.3.
