### ISSUE TITLE
remove (not install) git-secret.plugin.zsh script as per #315

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#382]
- there's a zsh completion script git-secret.plugin.zsh, install it 
   (don't forget to own the dirs)

See https://github.com/sobolevn/git-secret/issues/315

**Comment by joshrabinowitz** [comment]
Should we just remove the file at 
https://github.com/sobolevn/git-secret/blob/79a1c45aeb3585a132c6fe3e9eb3974614ec4573/git-secret.plugin.zsh ?

**Comment by gombosg** [comment]
It's not included in `install.sh` so yeah, safe to remove in a next release.

**Comment by sobolevn** [comment]
Yeap, let's remove it.
