### ISSUE TITLE
put `.gitsecret` in version control?

### ISSUE THREAD

**Issue by awesomefireduck** [sobolevn/git-secret#39]
The usage guide currently does not mention at all if the `.gitsecret` directory should be put in version control or not.

Perhaps it would be a good idea to mention that?

**Comment by sobolevn** [comment]
Hi, thanks for your feedback!

Well, as I see it is quite a common question: https://github.com/sobolevn/git-secret/issues/14#issuecomment-224208945

I will put the note into the readme.

**Comment by eigood** [comment]
This isn't clear to me; "not ignored" doesn't necessarily mean to run "git add .gitsecret".  And if after running "git secret init", the files need to be checked in to the repo, then this tool should do just that.

**Comment by eigood** [comment]
Oh, I see, I'm running 0.2.3(older debian install); the latest documents this in a clearer fashion.  My original point of git secret init adding the files still seems to make sense tho.
