### ISSUE TITLE
Document SECRETS_VERBOSE env var in man pages

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#396]
This separates the documentation of the SECRETS_VERBOSE environment variable support (PR #393) from it's implementation.

**Comment by joshrabinowitz** [comment]
May as well also use this opportunity to clarify the docs regarding all the supported SECRETS_* env vars.

**Comment by sobolevn** [comment]
@joshrabinowitz yes, that's totally required. Since we already have a bunch of them!

Thanks for this! You do an awesome work. 🚀

**Comment by joshrabinowitz** [comment]
Thank you @sobolevn ! It's a satisfying project to work on, and it's nice to collaborate with you.
