### ISSUE TITLE
Suggestion: Use https://asciinema.org/ for preview.

### ISSUE THREAD

**Issue by absorber** [sobolevn/git-secret#4]
First of all, interesting project!

I would suggest the following for the preview instead of a gif:
https://github.com/asciinema/asciinema/

You can start, stop and in the web-player even adjust speed (using the `<` and `>` keys).

**Comment by sobolevn** [comment]
Thank you for your interest, I will remove this gif anyway, because it's slow. I will have a look at the `asciinema`. You are welcome submit a PR to the `develop` branch.

**Comment by sobolevn** [comment]
Released in https://github.com/sobolevn/git-secret/pull/13
