### ISSUE TITLE
Is it necessary to kill gpg-agent between test cases

### ISSUE THREAD

**Issue by Mohjive** [sobolevn/git-secret#406]
As mentioned in #402 there are issues with killing the correct gpg-agent when running `make test`. Is it really necessary to kill the agent between tests?

What is the reason it is done in the first place? If it's to get a clean slate between tests, wouldn't it be better to just remove all keys (which I think is already done in all `teardown` with a call to `uninstall_fixture_key`, where applicable).

**Comment by joshrabinowitz** [comment]
I believe it is necessary; many tests fail if we do not stop `gpg-agent` between tests.
We currently use a ps and kill combo (which fails on some windows systems and doesn't work on `busybox`, other methods seen include:
 * gpgconf --kill gpg-agent (only works on some modern versions of gnupg)
 *  gpg-connect-agent reloadagent /bye  (not tried)
 (both of the above are mentioned at https://superuser.com/questions/1075404/how-can-i-restart-gpg-agent)

**Comment by joshrabinowitz** [comment]
closing because yes, it is necessary to stop `gpg-agent` between tests
