### ISSUE TITLE
travis thinks osx builds have passed when they have failed

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#418]
In https://travis-ci.org/sobolevn/git-secret/jobs/505623438 , 
you can see that travis thinks the run has passed, but the log shows almost every test failing.

(note that the osx builds are still passing all tests in master: https://travis-ci.org/sobolevn/git-secret/jobs/505403404 )

**Comment by Mohjive** [comment]
I think I found the issue. It was me failing to propagate the error from bats to the exit of the tests.sh script. I've pushed a change that should make it propagate now.
