### ISSUE TITLE
use DESTDIR in Makefile for debian

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#424]
This is part of #386 

#### The TL;DR:

We should probably be installing into $DESTDIR/$PREFIX

#### Details:

According to the Debian Upstream Guide https://wiki.debian.org/UpstreamGuide we should be using DESTDIR (they don't mention PREFIX)

> Installation
> Please honor the DESTDIR environment variable or make variable and use its contents as a prefix in front of all installation paths. ...

Gnu coding standards agree at https://www.gnu.org/prep/standards/html_node/DESTDIR.html

>DESTDIR is a variable prepended to each installed target file, like this:
>
>   $(INSTALL_PROGRAM) foo $(DESTDIR)$(bindir)/foo
>   $(INSTALL_DATA) libfoo.a $(DESTDIR)$(libdir)/libfoo.a
>
>The DESTDIR variable is specified by the user on the make command line as an absolute file 
>name. For example:

>   make DESTDIR=/tmp/stage install

FreeBSD docs at https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/porting-prefix.html give even more details:

> PREFIX determines where the port will be installed. It defaults to /usr/local, but can be set by the user to a custom path like /opt. The port must respect the value of this variable.
>
> DESTDIR, if set by the user, determines the complete alternative environment, usually a jail or an installed system mounted somewhere other than /.

**Comment by joshrabinowitz** [comment]
@sobolevn @simbo1905 Please let me know if you have thoughts about this issue.

**Comment by simbo1905** [comment]
Seems like a good idea. Will it effect fedora and alpine?

**Comment by joshrabinowitz** [comment]
@simbo1905  they actually document cases where its works just as it does in Debian:

https://wiki.archlinux.org/index.php/creating_packages indicates that arch linux expects it to work as debian does,

https://fedoraproject.org/wiki/Archive:PackagingDrafts/MakeInstall indicates Fedora is the same. 

Apparently it's a GNU thing: https://www.gnu.org/prep/standards/standards.html#DESTDIR

**Comment by joshrabinowitz** [comment]
https://nullprogram.com/blog/2017/08/20/ also talks about DESTDIR and PREFIX both being makefile conventions.
