### ISSUE TITLE
Feature: Allow globs in mapping

### ISSUE THREAD

**Issue by MOZGIII** [sobolevn/git-secret#453]
I would like to manage all my encrypted stuff under an `encrypted` directory, and I'd like use a glob pattern in `paths/mapping.cfg` instead of listing each file individually.

I'd add this to `.gitignore`:
```bash
/encrypted/*
!/encrypted/*.secret
```

But I can't just add `encrypted/*` to `paths/mapping.cfg`.

**Comment by joshrabinowitz** [comment]
@MOZGIII this is an interesting idea! 

The problem, implementation-wise, is that each line of `paths/mapping.cfg` currently stores the name of each file handled by git-secret, and the hash of that file.

If we do want to support globs for matching files to encrypt, maybe it makes sense to use another file, say, `paths/mapping_globs.cfg`, and use that when populating `paths/mapping.cfg`.

**Comment by MOZGIII** [comment]
Well, if that population is automated by the git-secret commands - I think it works for me!

**Comment by joshrabinowitz** [comment]
Patches welcome

**Comment by joshrabinowitz** [comment]
I don't see this getting implemented; closing.
