### ISSUE TITLE
`make build` appears to be broken

### ISSUE THREAD

**Issue by mnieber** [sobolevn/git-secret#459]
After cloning (on Linux Mint) I run `make build` which gives this output

    cat src/version.sh src/_utils/_git_secret_tools_freebsd.sh src/_utils/_git_secret_tools.sh src/_utils/_git_secret_tools_osx.sh src/_utils/_git_secret_tools_linux.sh src/commands/git_secret_list.sh src/commands/git_secret_tell.sh src/commands/git_secret_cat.sh src/commands/git_secret_hide.sh src/commands/git_secret_changes.sh src/commands/git_secret_usage.sh src/commands/git_secret_clean.sh src/commands/git_secret_init.sh src/commands/git_secret_remove.sh src/commands/git_secret_whoknows.sh src/commands/git_secret_killperson.sh src/commands/git_secret_add.sh src/commands/git_secret_reveal.sh src/main.sh > "git-secret"; \
    chmod +x git-secret; sync

I have no idea why this happens (instead of printing to the screen, I was expecting it to do something), it seems just broken. Is it?

**Comment by joshrabinowitz** [comment]
Hello, @mnieber - It is not broken. 

This is the output from `make build` which creates the git-secret script from multiple separate files and performs a `chmod +x` on the resulting script.

The Makefile was changed in #442 to show commands used as per #386. Thanks for opening this issue and please let us know if you have any more questions!

**Comment by mnieber** [comment]
Hi @joshrabinowitz, do you mean that `make build` executes those commands, and also prints them to the screen (as a kind of log)?

**Comment by joshrabinowitz** [comment]
@mnieber yes, this is what debian requests. 

Check out the comments in #422 , I had mistakenly referred to a different PR above (I've corrected it). From that PR and quoting from Debian's Upstream Guide:

````
Verbose builds

We need to record as much detail from the build log as possible so that we can debug 
build failures and other strange issues.  ...
````
