### ISSUE TITLE
git secret hide docs warn about `-F` but not `-m` behaviour 

### ISSUE THREAD

**Issue by simbo1905** [sobolevn/git-secret#467]
In the documentation for git-secret-hide it is very clear that if you don't encrypt all the files all the time, and the set of keys has changed, then bad things might happen. It says that if you know what you are doing then you can use `-F`. It should probably also mention `-m` at the same time as mentioning `-F` as it can lead to the same problems.

**Comment by joshrabinowitz** [comment]
@simbo1905 should we close this?
