### ISSUE TITLE
Command "usage"

### ISSUE THREAD

**Issue by antmak** [sobolevn/git-secret#47]
I do
```
$ git-secret usage
usage: git secret [add|changes|clean|hide|init|killperson|list|module|remove|reveal|scl|tell|usage|whoknows]
```

"module", "scl" - is wrong.

I think this is due to
```
$ compgen -A function | grep -v "^_"
command_not_found_handle
dequote
dus
izs
mkcd
module
quote
quote_readline
scl
```

**Comment by sobolevn** [comment]
Works fine for me:

> [21:14:47] sobolev :: MacBook-Pro-Nikita  ➜  Documents/elixir/elixir_lang_moscow ‹master› » git secret usage        
> usage: git secret [add|changes|clean|hide|init|killperson|list|remove|reveal|tell|usage|whoknows]
> [21:14:49] sobolev :: MacBook-Pro-Nikita  ➜  Documents/elixir/elixir_lang_moscow ‹master› » git secret --version
> 0.2.1

Please provide your os, shell and `git-secret` version.

**Comment by antmak** [comment]
$ git-secret --version
0.2.1

{Fedora 24, Fedora 21} x86_64. bash, version 4.3.42(1)-release (x86_64-redhat-linux-gnu).

**Comment by sobolevn** [comment]
Still can't reproduce
