### ISSUE TITLE
Mac: mktemp error when GNU coreutils are in $PATH

### ISSUE THREAD

**Issue by rcoup** [sobolevn/git-secret#485]
What are the steps to reproduce this issue?
-------------------------------------------
1. `git secret hide`

What happens?
-------------
```
mktemp: too few X's in template ‘_git_secret’
/usr/local/bin/git-secret: line 216: : No such file or directory
```

What were you expecting to happen?
----------------------------------
No error message 😄 This has worked previously.

Any logs, error output, etc?
----------------------------
See above

Any other comments?
-------------------

I guess it relates to #473 — maybe the code should call `/usr/bin/mktemp` on Mac to always use the OS version rather than whatever is in $PATH?

What versions of software are you using?
----------------------------------------
**Operating system:** Mac OSX 10.13.6. GNU Coreutils are from homebrew and `gnubin` is in `$PATH`. (ie. `which mktemp` => `/usr/local/opt/coreutils/libexec/gnubin/mktemp`)

**`git-secret` path:** `/usr/local/bin/git-secret` (Homebrew)

**`git-secret` version:** 0.2.6 (Homebrew)

**`git` version:** 2.21.0 (Homebrew)

**Shell type and version:** `GNU bash, version 5.0.2(1)-release (x86_64-apple-darwin17.7.0)` (Homebrew)

**`gpg` version:** `gpg (GnuPG) 2.2.16` (Homebrew)

**Comment by rjcoelho** [comment]
Same error here

**Comment by joshrabinowitz** [comment]
@rjcoelho - thanks for testing and writing back.

Hm, that's weird, I tested it on my mac and it worked (10.14.5). I'll see if I can get Travis-CI to reproduce the issue, too.

What MacOS version are you on?

**Comment by rjcoelho** [comment]
@joshrabinowitz it's because I am using mktemp from gnu coreutils installed by Homebrew as @rcoup

**Comment by joshrabinowitz** [comment]
@rjcoelho  that's the thing... the PR at #486 , which I think you're saying you tested, makes sure that on OSX only these two uses of `mktemp` are called:

Here: https://github.com/sobolevn/git-secret/pull/486/files#diff-be87b28d02dcf09cb989637ab6036e77R21 which has
`filename=$(/usr/bin/mktemp -t _git_secret )  `
and specifically uses the OS's mktemp at /usr/bin,

and here: 
https://github.com/sobolevn/git-secret/blob/master/tests/_test_base.bash#L18
which uses `mktemp -t 'gitsecret_output.XXXXXX'` and has the required `X`'s.
