### ISSUE TITLE
can't use a smartcard

### ISSUE THREAD

**Issue by bricewge** [sobolevn/git-secret#491]
What are the steps to reproduce this issue?
-------------------------------------------
Following the same steps as the [asciinema](https://asciinema.org/a/41811?autoplay=1) with an private key on a OpenPGP card and the agent managed by a systemd a socket trigger.

What happens?
-------------
`git secret hide` always fail.

What were you expecting to happen?
----------------------------------
To achieve the same as the asciinema.

Any logs, error output, etc?
----------------------------
```sh
$ git-secret hide
git-secret: abort: problem encrypting file with gpg: exit code 2: hideme.txt
```
Any other comments?
-------------------
Same error message as https://github.com/sobolevn/git-secret/issues/341, but probably different cause.

I think the issue come from the fact that the `--homedir` is changed by `git-secret`. A few times since gpg 2.0 the behavior of the agent has changed and now it seems that it's impossible to specify a location for the gpg-agent socket, it's derived from `--homedir`.

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
Linux taxo 4.19.47 #1-NixOS SMP Fri May 31 13:46:35 UTC 2019 x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`) …
/home/bricewge/.nix-profile/bin/git-secret

**`git-secret` version:** (`git secret --version`) …
0.2.5

**`git` version:** (`git --version`) …
git version 2.19.2

**Shell type and version:** (`$SHELL --version`) …
zsh 5.7.1 (x86_64-pc-linux-gnu)

**`gpg` version:** (`gpg --version`) …
gpg (GnuPG) 2.2.13
libgcrypt 1.8.4
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/bricewge/.gnupg
Algorithmes pris en charge :
Clef publique : RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Chiffrement : IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256,
              TWOFISH, CAMELLIA128, CAMELLIA192, CAMELLIA256
Hachage : SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression : Non compressé, ZIP, ZLIB, BZIP2

**Comment by joshrabinowitz** [comment]
@bricewge , thank you for this issue report.  

Could you please retest using git-secret 0.2.6, using
`git secret hide -v`? 
and posting the results here? 

I think it may show more specific information about the error.

**Comment by bricewge** [comment]
Of course! Here you go:
```
gpg: error retrieving 'brice@bricewge.fr' via WKD: Connection refused
gpg: brice@bricewge.fr: skipped: Connection refused
gpg: /home/bricewge/tmp/git-secret-test/hideme.txt: encryption failed: Connection refused
git-secret: abort: problem encrypting file with gpg: exit code 2: hideme.txt
```

**Comment by bricewge** [comment]
Adding even more verbosity to gpg by modifying `args` I got:
```
[...]
gpg: error retrieving 'brice@bricewge.fr' via Local: No public key
gpg: error retrieving 'brice@bricewge.fr' via WKD: Connection refused
gpg: brice@bricewge.fr: skipped: Connection refused
gpg: /home/bricewge/tmp/git-secret-test/hideme.txt: encryption failed: Connection refused
git-secret: abort: problem encrypting file with gpg: exit code 2: hideme.txt
```
I didn't knew about [WKD](https://wiki.gnupg.org/WKD) which has been added to the default locate methods in 2.1.13, usually I use a keyserver or my smartcad URL pointing to Github keys. So again tweaking `args` to add `--auto-key-locate local,keyserver`, effectively replacing the default `local,wkd` the key got imported:
```
[...]
gpg: error retrieving 'brice@bricewge.fr' via Local: No public key
gpg: data source: https://209.244.105.201:443
gpg: armor: BEGIN PGP PUBLIC KEY BLOCK
gpg: armor header: Version: SKS 1.1.6
gpg: armor header: Comment: Hostname: sks.pod02.fleetstreetops.com
[...]
gpg: brice.wge@gmail.com: skipped: public key already present
gpg: reading from '/home/bricewge/tmp/git-secret-test/hideme.txt'
gpg: writing to '/home/bricewge/tmp/git-secret-test/hideme.txt.secret'
gpg: RSA/AES256 encrypted for: "378C4E0E0F25FFEB Brice Waegeneire <brice.wge@gmail.com>"
git-secret: done. 1 of 1 files are hidden.
git-secret: cleaning up: /tmp/_git_secret.KALt7u
```
It wasn't a `gpg-agent` issue after all.

**Comment by joshrabinowitz** [comment]
@bricewge that's great, thank you for the feedback. 

Can you please answer a few follow-up questions?

* how did you modify the `args` using gpg and git-secret?
* can we close this issue?, and/or
* do you think we should make any changes to git-secret regarding this issue?

**Comment by bricewge** [comment]
I modified the following line that set the args for `gpg`.
https://github.com/sobolevn/git-secret/blob/28675d6461c1f491373f56ff44f06f0f0729e953/src/commands/git_secret_hide.sh#L165
I don't think the issue should be closed because it's not trivial to debug it and I will probably run into again, when setting other repos, if the issue isn't actually fix.

For how to go about fixing it, as a preliminary if there is a problem when importing a gpg key it should happen when `git tell` is called as it's help says, and not afterward as currently.
> [git tell] imports  a  person's  public key into the git-secret's inner keychain. From this moment this person can encrypt new  files  with  the  keyring  which  contains  their key, [...]

Then adding to `git tell` the ability to let the user choose how to import or locate keys would suffice, there will be no need to change the default behavior. I don't know all the gpg options related to key import but for me at least the option `--auto-key-locate` and `--no-auto-key-locate` are needed. To keep the options at a minimal and support different use case the implementation could be to pass to gpg the options after the option `--` like it's done in many unix tools. In my case I would do: `git tell -m -- --auto-key-locate local,keyserver --keyserver "hkp://keys.gnupg.net"`.

**Comment by bricewge** [comment]
Postmortem, the following line returned a revoked uid (`uid:r`) which made gpg try to get remote infomration on the key.
https://github.com/sobolevn/git-secret/blob/28675d6461c1f491373f56ff44f06f0f0729e953/src/_utils/_git_secret_tools.sh#L627
```
$ gpg --homedir /home/bricewge/tmp/git-secret-test/.gitsecret/keys --no-permission-warning --list-public-keys --with-colon --fixed-list-mode
tru::1:1561472361:0:3:1:5
pub:-:4096:1:3D36CAA0116F0F99:1388960304:1590063063::-:::scESCA::::::23::0:
fpr:::::::::8929BBC573CD92063DDD979D3D36CAA0116F0F99:
uid:-::::1558527063::4C521E4C4EEA5089B119158506F0CBAD1B5F9CB1::Brice Waegeneire <brice.wge@gmail.com>::::::::::0:
uid:r::::::5EDA4A560EB68E640E53FAFE5F5DF05315CFA749::Brice Waegeneire <brice@bricewge.fr>::::::::::0:
uid:-::::1558527834::9F64F80E92F5E8A6B201B7971079EB90B71142A6::Brice Waegeneire <brice@waegenei.re>::::::::::0:
[...]
```
Even if the PR is merged I still think what I suggest in the previous comment should be done, it would have made the debugging more straight forward.

**Comment by joshrabinowitz** [comment]
@bricewge I've added #509 to track your requests for changes to `tell` and key location. 

Also, above you say 
> if there is a problem when importing a gpg key it should happen when git tell is called as it's help says, and not afterward as currently.

In this particular case, I think the `tell` step technically did succeed, but it imported a revoked key, and the issue  didn't surface until the `hide` step. 

The changes we've made to skip revoked keys should stop this particular issue from recurring (but there's other gnupg key validity values we should handle in code too, see #508)
