### ISSUE TITLE
gawk should be listed as a prerequisite for deb installation

### ISSUE THREAD

**Issue by kag0** [sobolevn/git-secret#493]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install git-secret on Ubuntu linux
2. `git secret init`

What happens?
-------------
```
/usr/bin/git-secret: line 144: gawk: command not found
'/tmp/secrettest/.gitsecret/' created.
/usr/bin/git-secret: line 275: gawk: command not found
```

What were you expecting to happen?
----------------------------------
git secret initialized with no errors

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**`git-secret` version:** (`git secret --version`) …
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)

**Shell type and version:** (`$SHELL --version`) …
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)

**Comment by joshrabinowitz** [comment]
I think the fix for this is to move `gawk` in 
https://github.com/sobolevn/git-secret/blob/79a1c45aeb3585a132c6fe3e9eb3974614ec4573/.ci/integration/vars/Debian.yml 

to the build_tools section. 

Can anyone confirm/deny?

**Comment by joshrabinowitz** [comment]
I have confirmed this issue using Ubuntu 18.04 and the deb package of 0.2.6 at https://dl.bintray.com/sobolevn/deb/

**Comment by joshrabinowitz** [comment]
Believed fixed but not confirmed
