### ISSUE TITLE
Problems running git-secret in centos 6

### ISSUE THREAD

**Issue by rlsai** [sobolevn/git-secret#496]
I have configured git-secret in centos 6. When I tried git secret reveal I am getting error 
fatal: cannot exec 'git-check-ignore': Permission denied
git-secret: abort: '/home/python/ows-oss/.gitsecret' is in .gitignore

I saw you mentioned below requirements 
Requirements
git-secret relies on several external packages:

bash since 3.2.57 (it is hard to tell the correct patch release)
gawk since 4.0.2
git since 1.8.3.1
gpg since gnupg 1.4 to gnupg 2.X
sha256sum since 8.21 (on freebsd and MacOS shasum is used instead)

I have GNU Awk 3.1.7 version which is latest available version for centos 6. Is this is the reason for the above error I am getting.  
Does git-secret supports centos6?

**Comment by joshrabinowitz** [comment]
@rlsai it looks like you have a `git-check-ignore` exe, but it's not executable or you don't have premission to use the exe. Can you please post the results of 
````
   ls -l `which git-check-ignore`
````
?

**Comment by rlsai** [comment]
@joshrabinowitz Thanks for the response

>>ls -l `which git-check-ignore`
[centos@<?xml ~]$ git --version
git version 1.7.1
[centos@<?xml ~]$ ls -l `which git-check-ignore`
/usr/bin/which: no git-check-ignore in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/centos/bin)
total 0

Yeah my git version is <1.8.3 and when tried to update git version it is showing as :

Package git-1.7.1-9.el6_9.x86_64 already installed and latest version
Nothing to do

Is git version is the reason I am unable to decrypt as it was mentioned as requirements but I am unable to upgrade the below packages 
gawk since 4.0.2 ( currently I have GNU Awk 3.1.7)
git since 1.8.3.1 (currently I have git version 1.7.2)

**Comment by joshrabinowitz** [comment]
@rlsai Because CentOS 6 rpms don't have recent enough versions of at git and gawk, git-secret is not supported on CentOS 6 without upgrading prereqs to at least the required versions.

In general, I would recommend testing `git-secret` using `make test` in the source tree on your target platform before installing, because the self-tests should uncover most issues you're likely to encounter in real-world use.

**Comment by rlsai** [comment]
@joshrabinowitz Yeah I will consider your suggestion of testing any package using make test before installing. Now git-secret is working fine by installing prerequisites  manually with tarball.

**Comment by joshrabinowitz** [comment]
@rlsai Excellent, glad to hear that you got git-secret working for you, and thanks for the note!
