### ISSUE TITLE
Running in docker: gpg: cannot open '/dev/tty': No such device or address

### ISSUE THREAD

**Issue by sanohin** [sobolevn/git-secret#502]
I'm trying to reveal secret files with git-secret in Docker.
Here is the script:

```dockerfile
FROM ubuntu:18.04 as secrets
RUN apt-get update -y
RUN apt-get install git gnupg -y
RUN apt-get install git-secret -y
COPY ./key ./key

RUN gpg --batch --import ./key
# RUN echo "no-tty" > ~/.gnupg/gpg.conf

COPY ./ ./

RUN git secret reveal
```

When I run that I get an error:
`gpg: cannot open '/dev/tty': No such device or address`

After googling this error I found recommendations to run gpg with `no-tty` flag. But when I do that, I get another error:
`gpg: Sorry, no terminal at all requested - can't get input`.

How can I solve this problem?

**Comment by joshrabinowitz** [comment]
@sanohin can you please run that script with 
````dockerfile
RUN git secret reveal -v
````
and paste the output here?

**Comment by sanohin** [comment]
Thank you for the help, I didn’t properly exclude those secret files in dockerignore, so they were copied and the error occurred because of prompt asking to override them.
