### ISSUE TITLE
Show output from gnupg if it returns unexpected error code

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#516]
Currently unless -v or `SECRETS_VERBOSE`(or `SECRETS_TEST_VERBOSE` in tests) is enabled, we hide all output (stderr and stdout) from gnupg when hiding files. Analysing the code history,`git-secret` has always hidden most of the output from gnupg (and it's only recently that the verbose options that expose the output were added). 

However, we keep getting error reports about `git-secret` failures that are actually errors from gnupg that we suppress (especially regarding file permissions or unusable keys), and people don't see the errors until they enable verbosity.

Presumably stderr from gnupg is hidden because gnupg also has a habit of outputting non-error data to stderr, which also means we can't just hide stdout and show stderr to make sure we show errors.

I propose that we alter git-secret to always show the output (stderr and stdout) from gnupg if it _unexpectedly_ returns a non-zero error code. This will help users understand errors, especially regarding permissions and bad keys and other issues that are currently only detected and reported by git-secret

**Comment by joshrabinowitz** [comment]
See #510, #491, and #317 which I think this resolves.

**Comment by sobolevn** [comment]
I agree, that showing direct error messages is a good idea. It will eliminate a lot of confusing.
