### ISSUE TITLE
release 0.3.0 and 0.3.1

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#526]
I think we should release 0.2.7, which now has
* improved gnupg error reporting
* support for setting gnupg's PINENTRY setting
* support for busybox

and more. For details see CHANGELOG.md https://github.com/sobolevn/git-secret/blob/master/CHANGELOG.md

**Comment by sobolevn** [comment]
By the way, we now have a monthly budget of 100$ on https://opencollective.com/git-secret
I am certain that @joshrabinowitz and @simbo1905 deserved to get paid for maintaining the project. Because you do a great job! 

Please, reach me out via email.

**Comment by joshrabinowitz** [comment]
@sobolevn I've worked up a 0.3.0 release and a quick 0.3.1 doc update (sorry) at https://github.com/sobolevn/git-secret/releases

You want to make 'em official? :)

Josh

**Comment by sobolevn** [comment]
@joshrabinowitz done! 🎉 

There's still a homebrew repo that is released separately. 
https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-secret.rb

**Comment by joshrabinowitz** [comment]
0.3.1 is released!
