### ISSUE TITLE
Dev: get test-kitchen instances other than alpine to work locally using virtualbox

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#534]
I've been trying for some time to set up `test-kitchen` to test `git-secret` on all the fedora/ubuntu/alpine/debian targets locally. 

I'm using docker and docker-machine with boot2docker on my mac, and everything works if I test an alpine-based target with a command like:

`bundle exec kitchen verify --test-base-path="$PWD/.ci/integration" gnupg2-alpine-latest`. 

But if I try any other test targets (like `gnupg2-fedora-latest`), I get errors like one of these: 

`[SSH] connection failed, retrying in 1 seconds (#<Errno::ECONNREFUSED: Connection refused - connect(2) for 192.168.2.20:32769>)`

or

`Error: No public port '22/tcp' published for 80d1736706fddad3cfdb41957d710fddd96d23615d44eab57606c71bf17a3d6c`

Again, with the `alpine` targets everything works fine. 

Getting this working will be a big help in testing and performing `git-secret` releases, and I'll make sure to improve the docs to help others setup git-secret & test-kitchen too.

Can someone help me to debug this?

**Comment by joshrabinowitz** [comment]
Here's a log of a failing test run: 
https://gist.github.com/joshrabinowitz/54ecdace91b1317df489741c790f1d43

**Comment by joshrabinowitz** [comment]
I should add that all these tests work on jenkins (using the same distros/ISOs etc) at https://travis-ci.org/sobolevn/git-secret/builds/582026783

**Comment by joshrabinowitz** [comment]
@sobolevn @simbo1905 do you guys have this working on your local machines? 
Can you see what's going wrong or help me debug this?

**Comment by joshrabinowitz** [comment]
Update: this issue disappears using 'Docker for Mac' instead of docker and docker-machine from brew.

 It would still be great to understand why it doesn't work using docker from brew.

**Comment by joshrabinowitz** [comment]
More: I can only get this working using "docker for mac" and without VirtualBox. 
If I use vbox (with brew or Docker for Mac) I get the port 22 issues above.

**Comment by sobolevn** [comment]
Maybe @hurricanehrndz knows something about it.

**Comment by joshrabinowitz** [comment]
See also #543

**Comment by joshrabinowitz** [comment]
This works with 'docker for mac', closing as 'wontfix'.
