### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by gombosg** [sobolevn/git-secret#550]
Hi!

I'm the Fedora + EPEL packager. I saw a lot of releases recently - is 0.3 a stable release? How stable is it to be included in Fedora Rawhide (beta), Fedora Stable and EPEL?

As a volunteer packager I don't have the resources to push out updates 3 times a week so I can wait a bit for a more mature release if needed 😄 

Thanks!

**Comment by joshrabinowitz** [comment]
Hi @gombosg, 
yes 0.3.2 is stable, and I'm expecting it to be the last release for a while. 
Was trying to hunt down #460

**Comment by gombosg** [comment]
Thanks! I have submitted the necessary updates to Fedora/EPEL.
