### ISSUE TITLE
Packages files at https://dl.bintray.com/sobolevn/deb are always one version out of date

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#551]
When we cut a new release, new deb files get uploaded to 
https://dl.bintray.com/sobolevn/deb
but the Packages files there get updated to include all but the current release. 

It seems like perhaps the Packages files get generated before the deb packages are created? Not sure.  

 (This issue  is a cleanup of  #460 -- see that PR for more details. 
As noted in #460 this could be related to #312)

**Comment by joshrabinowitz** [comment]
@simbo1905 / @sobolevn someone should hunt down and fix this, hoping one of you has the bandwidth.

**Comment by sobolevn** [comment]
I am 30% done with `rust` version 🙂

**Comment by joshrabinowitz** [comment]
@sobolevn that is great! 

This bug is about the deb packaging, so it probably also applies to a rust rewrite.

**Comment by joshrabinowitz** [comment]
I'm seeing 0.3.2 on https://dl.bintray.com/sobolevn/deb now - is this resolved?
