### ISSUE TITLE
Difference with git-secrets

### ISSUE THREAD

**Issue by lrkwz** [sobolevn/git-secret#562]
What is the difference with https://github.com/awslabs/git-secrets/ ?

See https://github.com/awslabs/git-secrets/issues/142

**Comment by joshrabinowitz** [comment]
`git-secret` encrypts secrets so the encrypted, unreadable versions can be committed to a git repo. 

`git-secrets` helps prevent you from committing unencrypted secrets to a git repo.

**Comment by lrkwz** [comment]
You did such a good job, I think you should write it in your README.
