### ISSUE TITLE
different output files generated every time

### ISSUE THREAD

**Issue by zvictor** [sobolevn/git-secret#564]
What are the steps to reproduce this issue?
-------------------------------------------
1. run the steps in "[Setting up git-secret in a repository](https://git-secret.io/#usage-setting-up-git-secret-in-a-repository)"
2. run `git secret hide` and check the hash of the generated `.secret` file
3. without changing the content of any file, repeat item 2

What happens?
-------------
the files generated in items 2 and 3 are different, with different hash and slightly different size

What were you expecting to happen?
----------------------------------
they should be the same, otherwise the `pre-commit` hook would make all commits lead to a merge-conflict hell

What versions of software are you using?
----------------------------------------
**Operating system:** Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

**`git-secret` path:** /usr/local/bin/git-secret

**`git-secret` version:** 0.3.2

**`git` version:** git version 2.21.0 (Apple Git-122.2)

**Shell type and version:** zsh 5.7.1 (x86_64-apple-darwin19.0)

**`gpg` version:** gpg (GnuPG) 2.2.18; libgcrypt 1.8.5

**Comment by joshrabinowitz** [comment]
According to my reading on the subject, this is how gnupg works -- encryption with gnupg is not deterministic. You are not guaranteed to get the same encrypted results with a given key and file content.
