### ISSUE TITLE
Documentation : how to use gpg?

### ISSUE THREAD

**Issue by aymericbouzy** [sobolevn/git-secret#574]
The documentation seems to assume the user has knowledge of what the `gpg` command is and how to use it : 

> Before starting, make sure you have created gpg RSA key-pair: public and secret key identified by your email address.

Pointing to the documentation that explains how to do these steps would be helpful.

**Comment by joshrabinowitz** [comment]
These are great ideas! Could you possibly submit a PR with the changes you recommend?
