### ISSUE TITLE
Documentation : how to use with CI/CD?

### ISSUE THREAD

**Issue by aymericbouzy** [sobolevn/git-secret#575]
`git-secret` seems very promising, but I'm not quite sure how I could use it with my CI/CD (in my case, Codeship Basic).

I can set env vars but that's about it : is it possible to generate a public/private keypair from my computer, and add the private key to my CI/CD through an env var? Documentating this would be very helpful to get started.

**Comment by aymericbouzy** [comment]
Thanks to https://www.devdungeon.com/content/gpg-tutorial I was able to : 

1. generate a private key pair for my CI/CD using `gpg --gen-key`
1. export the private key using `gpg --export-secret-keys --armor XXXXXXXX` where XXXXXXXX is the hexadecimal key ID
1. share the secret with CI/CD using `git secret tell cicd@email.id` (replace with the fake email you chose at step 1.)
1. set a `GPG_PRIVATE_KEY` env var in my CI/CD with the content of the private key
1. deploy in CI/CD with this script: 

```sh
echo $GPG_PRIVATE_KEY > ./gpg_private_key.asc
gpg --import ./gpg_private_key.asc
git secret reveal -p $GPG_PRIVATE_KEY_PASSWORD
```

Is it worth mentioning in the documentation?

**Comment by joshrabinowitz** [comment]
We would appreciate if you would submit a PR with the changes you recommend

**Comment by aymericbouzy** [comment]
Will do : I'm currently polishing the details 👍
