### ISSUE TITLE
"repository is broken" on git secret reveal if .git/hooks doesn't exist

### ISSUE THREAD

**Issue by rjcoelho** [sobolevn/git-secret#58]
Calling `git secret reveal` on a repo that doesn't have `.git/hooks` returns error `repository is broken`. Creating an empty `.git/hooks` solves the issue. 

My suggestion is to either 1) don't complain if `git secret reveal` doesn't need it, or 2) `git secret init` should create it if it doesn't exit and we will git add it to repo.

**Comment by sobolevn** [comment]
Hello, sorry for the long answer. It took me sometime to solve this issue.
This looks fair enough for me. I guess checking for the `.hooks` subfolder is to strict. So this check is removed already in the `develop` branch. See https://github.com/sobolevn/git-secret/commit/4bf48da28122bdb765057ad59440e944c287166e

Thanks for your feedback!
