### ISSUE TITLE
(question) `killperson`? really?

### ISSUE THREAD

**Issue by alumarcu** [sobolevn/git-secret#585]
Hi,
Just started using `git-secret` today for one of our team's projects, we're coming from `git-crypt`, and everything seems much better. Thanks for building this!
The naming choice of the command `killperson` for removal of the key however - did make us raise a few eyebrows, and we're generally all about having fun naming things too. Could you explain this naming decision a bit? 

IMHO there are two issues with the current choice: 1) it's somewhat confusing and 2) it feels rather cringey and unnecessarily violent. Would you consider less confusing, and maybe less aggressive naming choices such as `remove-key`, `deny`, `revoke`, `block`, etc.? Thank you!

**Comment by sobolevn** [comment]
Thanks a lot for this question, naming is always really hard. 

As Mark Twain once said: "two people can keep a secret if one of them is dead". This is a reference to the classics.

To solve this for you team: 
1. You can create a bash alias with whatever name that you think is best. 
2. You can create a [plugin](https://github.com/sobolevn/git-secret/wiki/Third-party-plugins) that will serve as a proxy
3. You can fork this repo, it is licensed as MIT

I am afraid, that renaming commands at this point is not a option. This is related to the really complex packaging and distribution process. A lot of operating system already have this project. And too many users rely on it the way it is. And shipping a breaking change in this manner will be a really bad thing. 

You can open a new name suggestion to the new version (we are rewriting this package in Rust): https://github.com/sobolevn/git-secret-rust It will be considered! 

Best regards,
Nikita

**Comment by sobolevn** [comment]
Also `/bin/kill` is a nice analogy.

**Comment by joshrabinowitz** [comment]
I agree with the underlying complaint in this issue, but I also agree that `killperson` can't be renamed, for all the reasons above.

My biggest issue with `killperson` is that  `tell` and `killperson` aren't clear opposites -- `hide`/`reveal`, `add`/`remove` are more obvious complements. 

One way forward would be to add a synonym for `killperson` that is a clearer antonym of `tell`. I liked the suggestion`revoke` best.  This would mean `git secret revoke user@example.com` would be the same as using `git secret killperson user@example.com`. 

However, Implementation of this would require adding an exe like `git-secret-revoke`, along with doc changes, man pages, packaging changes, etc. All doable, but maybe too much code changes for just adding a command synonym. 

So I _mildly_ feel that adding 'synonym' support carries just a little bit too much code overhead. But I could possibly be talked out of this position. If someone submitted a PR that made all the changes to add support for `revoke` in addition to `killperson` we could talk about it more concretely.
