### ISSUE TITLE
confusing error message from `git-secret-add`

### ISSUE THREAD

**Issue by riccardomurri** [sobolevn/git-secret#586]
What are the steps to reproduce this issue?
-------------------------------------------
1. Have a file already checked into `git`; for the sake of example let it be `etc/service.properties`:

         $ ls -l etc/service.properties
        -rw-rw-r-- 1 rmurri rmurri 9063 gen 31 17:31 etc/service.properties

2. Try to `git-secret-add` it:

         $ git secret add etc/service.properties
        etc/service.properties is not a file. abort.

What happens?
-------------
`git-secret` outputs a confusing error message telling me that an existing regular file is not a file.

What were you expecting to happen?
----------------------------------
That `git-secret` would output an error message stating that I cannot add a file that has already been checked into Git.

Any logs, error output, etc?
----------------------------
```
$ ls -l etc/service.properties
-rw-rw-r-- 1 rmurri rmurri 9063 gen 31 17:31 etc/service.properties

 $ git secret add etc/service.properties
etc/service.properties is not a file. abort.
```

What versions of software are you using?
----------------------------------------
**Operating system:**
```
 $ uname -a
Linux dunja 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:    19.10
Codename:   eoan
```

**`git-secret` path:** `/usr/bin/git-secret`

**`git-secret` version:** `0.2.2`

**`git` version:** 2.20.1

**Shell type and version:** zsh 5.7.1 (x86_64-ubuntu-linux-gnu)

**`gpg` version:** gpg (GnuPG) 2.2.12

**Comment by riccardomurri** [comment]
I see this is already fixed in "master", and the Ubuntu package is lagging behind...

**Comment by joshrabinowitz** [comment]
@riccardomurri can you help us to get git-secret updated in ubuntu? (I think it has to get updated in debian first, because it's upstream)

**Comment by riccardomurri** [comment]
hello @joshrabinowitz 

> can you help us to get git-secret updated in ubuntu?

I'm afraid I'm just a Ubuntu user and not a developer.  I can report bugs in Ubuntu or Debian's tracker, if you think that would be useful.

**Comment by joshrabinowitz** [comment]
@riccardomurri yes if you could report it in Debian's tracker that could be useful (it's upstream from Ubuntu, as mentioned above)
