### ISSUE TITLE
`git secret hide` should skip revoked identities

### ISSUE THREAD

**Issue by riccardomurri** [sobolevn/git-secret#587]
What are the steps to reproduce this issue?
-------------------------------------------
1. Run `git secret tell` with some GPG key that has multiple email addresses, some of which have been revoked.
2. Run `git secret hide` and watch it fail with GPG error messages.

What happens?
-------------
GPG errors out, and so does `git-secret` (sorry, back-translated from italian-language locale, error messages might not be exactly those output by GPG in `en_US`):
```
gpg: riccardo.murri@+++: skipped: public key already added
gpg: riccardo.murri@---: skipped: public key already added
gpg: error retrieving 'murri@***' via WKD: missing data
gpg: murri@***: skipped: missing data
gpg: etc/service.properties: encryption failed: missing data
git-secret: abort: problem encrypting file with gpg: exit code 2: etc/service.properties
```

What were you expecting to happen?
----------------------------------
That revoked GPG identities are skipped.

They are marked with `r` in the second field of GPG's `--with-colon` list output.

What versions of software are you using?
----------------------------------------
**Operating system:** Linux dunja 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**`git-secret` path:** /usr/bin/git-secret

**`git-secret` version:** 0.3.1

**`git` version:** git version 2.20.1

**Shell type and version:** bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)

**`gpg` version:** gpg (GnuPG) 2.2.12

**Comment by joshrabinowitz** [comment]
See also issues mentioned in PR #553:  #552, #508, #317, #290, #283, and #238
