### ISSUE TITLE
Feature: Allow adding key by ID instead of Email

### ISSUE THREAD

**Issue by hikaru-shindo** [sobolevn/git-secret#590]
What are the steps to reproduce this issue?
-------------------------------------------
1. git secret tell 10F4FDEBA9D731418F5AF310FEE503327D63D8D3

What happens?
-------------
git-secret: abort: does not appear to be an email: 10F4FDEBA9D731418F5AF310FEE503327D63D8D3

What were you expecting to happen?
----------------------------------
Key is added to the keyring.

This allows for adding the key explicitly (ex. if there are multiple keys for the email address) and verifying the correct key verified with the person to be added to be correct is added.

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
Darwin 143954S0 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64

**`git-secret` path:** (`which git-secret`) …
/usr/local/bin/git-secret

**`git-secret` version:** (`git secret --version`) …
0.3.2
**`git` version:** (`git --version`) …

**Shell type and version:** (`$SHELL --version`) …
zsh 5.3 (x86_64-apple-darwin18.0)

**`gpg` version:** (`gpg --version`) …
gpg (GnuPG/MacGPG2) 2.2.17
libgcrypt 1.8.4
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/nitsche/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by joshrabinowitz** [comment]
Closing, this is a dup of the solution suggested for #268

**Comment by joshrabinowitz** [comment]
@hikaru-shindo thank you for this issue report
