### ISSUE TITLE
Github Secrets API

### ISSUE THREAD

**Issue by VikashKothary** [sobolevn/git-secret#595]
Would it be in scope for this project to support GitHub Secrets API as a provider? 

https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by sobolevn** [comment]
Sorry, I am not able to find any information about providers for GitHub Secrets API 😞 
<img width="1095" alt="Снимок экрана 2020-05-25 в 16 47 05" src="https://user-images.githubusercontent.com/4660275/82818444-6afe5000-9ea7-11ea-85e5-006b51e73c64.png">


Can you please provide a more specific link?

**Comment by VikashKothary** [comment]
I think I might have misunderstood what this repo does. But I was wondering whether it would be a good idea to use thee new [Github Actions API](https://developer.github.com/v3/actions/secrets/) to upload/download the secrets as an alternative to the secret files.

**Comment by sobolevn** [comment]
Sorry, I don't have enough experience with Github Actions to give this advice.

**Comment by VikashKothary** [comment]
That's fine.

**Comment by joshrabinowitz** [comment]
I looked at this a little. I don't see them being particularly compatible.
Git-secret uses `git` and `gnupg` to store secrets in any git repo, and uses bash and standard unix utilities to work.
github-secrets depends on github (not `git`), and uses a REST-ful API to access secrets which can span repositories. 

The models are so different I have a hard time even envisioning what a rational integration would be.
