### ISSUE TITLE
Getting error in installation of git-secret on Windows 10

### ISSUE THREAD

**Issue by premchand-algo** [sobolevn/git-secret#596]
Hi

I am getting an issue in the installation of git-secret on window os.

I have install the ubuntu sub-system.
I would also recommend to try the "Manual" installation method from here: http://git-secret.io/installation

home@DESKTOP-7BD1J3J:~/git-secret$ sudo apt install make build PREFIX="/usr/local" make install
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package build
E: Unable to locate package PREFIX=/usr
E: Unable to locate package install

**Comment by sobolevn** [comment]
Your command does not seem correct to me: `sudo apt install make build PREFIX="/usr/local" make install`
It should be: `sudo apt install make && make build && PREFIX="/usr/local" make install`
Note that I use `&&` to chain commands to be executed one after another.

**Comment by premchand-algo** [comment]
@sobolevn  
Now I am getting the following error after executing commons as suggested to you.

mkdir: cannot create directory ‘/usr/local/share/man/man1’: Permission denied
mkdir: cannot create directory ‘/usr/local/share/man/man7’: Permission denied
make: *** [Makefile:25: install] Error 1

**Comment by premchand-algo** [comment]
@sobolevn 

I have to get a successful installation of it as follows.

home@DESKTOP-7BD1J3J:~/git-secret$ sudo apt install make && make build && PREFIX="/user"
Reading package lists... Done
Building dependency tree
Reading state information... Done
make is already the newest version (4.2.1-1.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
make: Nothing to be done for 'build'.
home@DESKTOP-7BD1J3J:~/git-secret$ sudo make install
chmod +x "./utils/install.sh"; sync; \
"./utils/install.sh" ""/usr""
**Installed git-secret to /usr/bin/git-secret**
home@DESKTOP-7BD1J3J:~/git-secret$
 
Can you help me that how can I test my project with it?

**Comment by sobolevn** [comment]
> Can you help me that how can I test my project with it?

What do you mean?

**Comment by premchand-algo** [comment]
Next step, How to setup git-secret to test project on windows os?

**Comment by sobolevn** [comment]
You should now have a binary that can be used. Follow the steps in the tutorial https://git-secret.io/

**Comment by joshrabinowitz** [comment]
@premchand-algo , you might also find the video on <https://github.com/sobolevn/git-secret/blob/master/README.md> helpful.

**Comment by joshrabinowitz** [comment]
Closing this ticket as the person who opened the ticket has git-secret installed
