### ISSUE TITLE
download ShellCheck from correct URL, so travis builds work

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#597]
https://travis-ci.com/github/sobolevn/git-secret/jobs/338915115 shows:

````
You are downloading ShellCheck from the wrong URL!
\nPlease update to the latest one:\n
https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.x86_64.tar.xz\n\nFor more information, see:\n
https://github.com/koalaman/shellcheck/issues/187
````

**Comment by joshrabinowitz** [comment]
@sobolevn

**Comment by sobolevn** [comment]
I will change this line (https://github.com/sobolevn/git-secret/blob/b504facc5d2fa7d2c7e8c8abdee86cff5835e6f8/.ci/integration/tasks/dependencies.yml#L17) to https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.x86_64.tar.xz

**Comment by sobolevn** [comment]
Thanks a lot for the report!
