### ISSUE TITLE
Is there a compatibility issue with GnuPG 2.X ?

### ISSUE THREAD

**Issue by juliosueiras** [sobolevn/git-secret#6]
## Info

using zplug for adding git-secret

``` sh
gpg (GnuPG) 2.1.11
git version 2.7.3
```

Error message

``` sh
no users found. run 'git secret tell' before adding files. abort.
```

**Even though I had done that**
## Tests

``` sh
34 tests, 17 failures
```

P.S. do you need the full test detail?

**Comment by juliosueiras** [comment]
**UPDATE:** Did a test under a docker container with `gpg 1.4.18` and all test pass
Testing under a gpg2 container right now

**Comment by juliosueiras** [comment]
**UPDATE 2:** GnuPG 2 test all pass , so is probably my computer at fault

**Comment by sobolevn** [comment]
Adding `gpg2` into `.travis.yml` is a good idea, will see why it fails.

**Comment by kbrownlees** [comment]
I just hit this on my arch box, the issue for me was that by default gpg now generates pubring.kbx not pubring.gpg so the check for SECRETS_DIR_KEYS_PUBRING was failing. From https://www.gnupg.org/faq/whats-new-in-2.1.html there is fallback behaviour so this will only be an issue for a secret directory first created by gpg > 2.1.

Changing the variable to use pubring.kbx appears to work fine, but probably forces everyone to have a recent gpg version.

```
$> gpg --version
gpg (GnuPG) 2.1.12
libgcrypt 1.7.0
```

**Comment by sobolevn** [comment]
@kbrownlees thanks, now it's clear what to fix.

**Comment by sobolevn** [comment]
Information for the reference:

```
root@d7756c738880:/temp# ls .gitsecret/keys/
S.gpg-agent        private-keys-v1.d/ pubring.kbx~       
mapping.cfg        pubring.kbx        trustdb.gpg   
```

The error was with `pubring.kbx` filename.

**Comment by mrmachine** [comment]
@sobolevn This appears to still be a problem. We upgraded a previously working Ubuntu 14.04 LTS Docker image to 16.04 LTS and that brought with it a new version of gnupg2. I've updated to git-secret 0.2.2, but I still get an error when I try `git secret tell ...`:

```
bash-4.3# rm -rf .gnupg .gitsecret
bash-4.3# git secret init
'.gitsecret/' created.
bash-4.3# gpg2 --batch --gen-key <<-EOF
> Key-Type: RSA
> Key-Usage: encrypt
> Passphrase: $GPG_PASSPHRASE
> Name-Email: $GPG_EMAIL
> EOF
gpg: directory '/opt/syrinscape/.gnupg' created
gpg: can't open '/usr/share/gnupg2/dirmngr-conf.skel': No such file or directory
gpg: new configuration file '/opt/syrinscape/.gnupg/gpg.conf' created
gpg: keybox '/opt/syrinscape/.gnupg/pubring.kbx' created
gpg: /opt/syrinscape/.gnupg/trustdb.gpg: trustdb created
gpg: key F59A4727 marked as ultimately trusted
gpg: directory '/opt/syrinscape/.gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/opt/syrinscape/.gnupg/openpgp-revocs.d/D4C8897A601A9A9CFA849526ED78DAC0F59A4727.rev'
bash-4.3# gpg --list-keys
gpg: keyring `/opt/syrinscape/.gnupg/pubring.gpg' created
gpg: checking the trustdb
gpg: public key of ultimately trusted key F59A4727 not found
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
bash-4.3# gpg2 --list-keys
/opt/syrinscape/.gnupg/pubring.kbx
----------------------------------
pub   rsa2048/F59A4727 2017-06-01 [CE]
uid         [ unknown]  <git-secret@syrinscape>

bash-4.3# git secret tell "$GPG_EMAIL"
gpg: keyring `/opt/syrinscape/.gnupg/secring.gpg' created
gpg: WARNING: nothing exported
gpg key is empty. check your key name: "gpg --list-keys". abort.
cleaning up...
bash-4.3# git secret whoknows
no users found. run 'git secret tell' before adding files. abort.
bash-4.3# gpg2 --version
gpg (GnuPG) 2.1.11
libgcrypt 1.6.5
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /opt/syrinscape/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
bash-4.3# git secret --version
0.2.2
```

**Comment by sobolevn** [comment]
Thanks for the report. Reopened.

**Comment by sobolevn** [comment]
By default `Ubuntu 16.04` has `gpg 1.4.20`
> root@50884a92fde5:/# gpg --version
> gpg (GnuPG) 1.4.20
> Copyright (C) 2015 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Home: ~/.gnupg
> Supported algorithms:
> Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
> Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
>         CAMELLIA128, CAMELLIA192, CAMELLIA256
> Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
> Compression: Uncompressed, ZIP, ZLIB, BZIP2

And no `gpg2`:

> root@50884a92fde5:/# gpg2 --version
> bash: gpg2: command not found
> root@50884a92fde5:/# 
> 

After installing `gpg2`:

> root@50884a92fde5:/# gpg2 --version
> gpg (GnuPG) 2.1.11

Now trying to generate a new key:

> root@50884a92fde5:/test# export GPG_PASSPHRASE=somepass
> root@50884a92fde5:/test# export GPG_EMAIL=some@mail
> root@50884a92fde5:/test# gpg2 -vvv --gen-key --batch --debug-quick-random <<-EOF 
> Key-Type: RSA
> Key-Usage: encrypt
> Passphrase: $GPG_PASSPHRASE
> Name-Email: $GPG_EMAIL
> EOF
> gpg: using character set 'iso-8859-1'
> gpg: writing self signature
> gpg: RSA/SHA256 signature from: "B8B6BB35 [?]"
> gpg: writing public key to '/root/.gnupg/pubring.kbx'
> gpg: /root/.gnupg/trustdb.gpg: trustdb created
> gpg: using PGP trust model
> gpg: key B8B6BB35: accepted as trusted key
> gpg: key B8B6BB35 marked as ultimately trusted
> gpg: directory '/root/.gnupg/openpgp-revocs.d' created
> gpg: writing to '/root/.gnupg/openpgp-revocs.d/8B1296E520D4F0D3543DA34485072952B8B6BB35.rev'
> gpg: RSA/SHA256 signature from: "B8B6BB35  <some@mail>"
> gpg: revocation certificate stored as '/root/.gnupg/openpgp-revocs.d/8B1296E520D4F0D3543DA34485072952B8B6BB35.rev'
> root@50884a92fde5:/test# gpg2 --list-keys
> gpg: checking the trustdb
> gpg: marginals needed: 3  completes needed: 1  trust model: PGP
> gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
> /root/.gnupg/pubring.kbx
> 
> pub   rsa2048/B8B6BB35 2017-06-01 [CE]
> uid         [ultimate]  <some@mail>

Now adding this user to the `git-secret`:

> root@50884a92fde5:/test# SECRETS_GPG_COMMAND=gpg2 git secret tell "$GPG_EMAIL"
> done. some@mail added as someone who know(s) the secret.
> cleaning up...

So, my guess that you are missing `SECRETS_GPG_COMMAND=gpg2`.

**Comment by fjcaetano** [comment]
I've stumbled with this same issue, except I'm trying to reveal the ecrypted files instead.

I'm trying to run `git secret reveal` in Travis CI with Ubuntu. The files were encrypted in macOS, which uses gpg2, so git-secret created a `pubring.kbx` file. In the Ubuntu machine, it uses `gpg` by default which looks for `pubring.gpg` and creates the file when it's not found. Consequently, `gpg` thinks there are no public keys configured.

Even after setting `SECRETS_GPG_COMMAND=gpg2` it's still behaving the same. I double checked if the env var was being used by setting it to `echo` and it printed the arguments sent to `gpg`, so that was confirmation that it is indeed running with `gpg2`.

I have no idea how to move from this. I tried searching for a way to convert a `kbx` file to `gpg`, but my quick search came up empty.

This is the Travis log with all of the above: https://travis-ci.org/Shufflow/mind-blown/builds/554862992

**Comment by joshrabinowitz** [comment]
@fjcaetano thanks for your comment. 

You don't specify the version of git-secret you're using but make sure you're using 0.2.6 or later so you get the newest behavior and error reporting. Also, setting the SECRETS_VERBOSE=1 should show you more about the gpg commands run and the errors gpg emits.

There are known interoperability issues between different versions of gpg (even between different versions of gpg2); see https://github.com/sobolevn/git-secret/issues/228

Can you look into the particular versions of gpg2 you're running on Travis and macOS? I suspect they have interoperation issues if you try to use binary files from one version on another. (see below)

The way to get different versions of gpg to interoperate is to export the relevant data using gpg on one system and import it again on the other system (instead of depending on the binary files working across versions). Check out gpg docs for `--export` and `--armor`. 

Also, we have a long-term plan to work around these gpg interop issues, see PR #207 / https://github.com/sobolevn/git-secret/blob/master/RFC/RFC001.md

**Comment by fjcaetano** [comment]
I'm using 0.2.6 and 0.2.5 in different Macs and Travis is building from source, so it's the latest version.

I was actually able to work around this by installing gpg < 2.0 in my Mac and calling `git secret tell` with the same keys that had access originally. This created a `pubring.gpg` in parallel with the `pubring.kbx`. The downside is having to keep both updated when adding or removing access.

It's still unclear to me why `git-secret` didn't create a `.kbx` file on Linux when I told it to use `gpg2`. Shouldn't that be related to gpg's version?

Anyway, just wanted to let you know that there's a simple way to have it working for both versions of `gpg`.

**Comment by joshrabinowitz** [comment]
@fjcaetano Thanks for writing back again, and I'm glad you've resolved your issue. 

The files in .gitsecret/keys are written and read solely by gnupg/gnupg2 (whatever versions have been used over time in the user's repo). From https://github.com/sobolevn/git-secret/blob/master/RFC/RFC001.md :
_GPG maintains backwards compatibility but not forwards compatibility. Running a new GPG version can and will upgrade the keyring storage files in a way that is not recognized by older versions of GPG. This is not normally a problem for typical GPG usage. Users will upgrade and rarely downgrade. It is a problem for git-secret as the keyring storage is committed to git and shared between users. Someone using an older version of GPG can no longer open the upgraded keyring file._
