### ISSUE TITLE
docs: clarify why a public key ought to be transmitted via secure channel

### ISSUE THREAD

**Issue by anno1985** [sobolevn/git-secret#603]
I was just reading through the docs the other day, and stumbled over this sentence at the end of the [gpg paragraph](https://git-secret.io/#using-gpg):
> Be sure to use a secure channel to share your public key!

What's the rationale for using a secure channel? 

As it's a public key I was under the impression it shouldn't be an issue if someone got hold of it.

Is the idea that you need to make sure you get the right public key (so you don't grant access to someone who shouldn't have access)? Is it to instil in users the idea to always share keys via an encrypted connection (me equating secure and encrypted might be the mistake)? Or is it something else?

**Comment by sobolevn** [comment]
Hi @anno1985! Thanks a lot for your question!

> Is the idea that you need to make sure you get the right public key (so you don't grant access to someone who shouldn't have access)? 

Yes, this is the idea. There's no need to secure your public key (mine is available publicly here: https://sobolevn.me/about/) 

Maybe we can use a better wording for this?
