### ISSUE TITLE
Using git-secret in GitHub Actions not successful

### ISSUE THREAD

**Issue by cboulanger** [sobolevn/git-secret#615]
What are the steps to reproduce this issue?
-------------------------------------------
1. Follow instructions on https://git-secret.io/ to prepare repository & store GPG Key in secret environment variable, `git secret add` test file and `git secret hide` it.
2. [add job step to install git-secrets](https://github.com/cboulanger/bibliograph/commit/8a2b06ddf641658f0a324c308533d85764c276dc)

What happens?
-------------
[Error: `gpg: no valid OpenPGP data found.`](https://github.com/cboulanger/bibliograph/runs/1159057160?check_suite_focus=true#step:9:108)

What were you expecting to happen?
----------------------------------
It should work

Any logs, error output, etc?

- error log: https://github.com/cboulanger/bibliograph/runs/1159057160?check_suite_focus=true#step:9:108
- GitHub Action Step: https://github.com/cboulanger/bibliograph/commit/8a2b06ddf641658f0a324c308533d85764c276dc

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
`Darwin MacBook-Pro-2.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`

**`git-secret` path:** (`which git-secret`) …
`/usr/local/bin/git-secret`
**`git-secret` version:** (`git secret --version`) …
`0.3.2`
**`git` version:** (`git --version`) …
`git version 2.26.2`
**Shell type and version:** (`$SHELL --version`) …
`zsh 5.7.1 (x86_64-apple-darwin19.0)`
**`gpg` version:** (`gpg --version`) …
`gpg (GnuPG) 2.2.19`

**Comment by sobolevn** [comment]
Does it work locally? Are you sure that your secret key in `$GPG_PRIVATE_KEY` is valid?

**Comment by cboulanger** [comment]
Thank you for your quick response! I will investigate and report.

**Comment by cboulanger** [comment]
It works locally. I've updated the code to this:
```
          echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | sudo tee -a /etc/apt/sources.list
          wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
          sudo apt-get update && sudo apt-get install git-secret
          export GPG_TTY=$(tty)
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --no-tty --import --batch
          git secret reveal
```
but I still get an error: 

https://github.com/cboulanger/bibliograph/runs/1164637230?check_suite_focus=true#step:9:176

Files:
 - https://github.com/cboulanger/bibliograph/blob/develop/deploy/test.secret
 - https://github.com/cboulanger/bibliograph/tree/develop/.gitsecret

**Comment by sobolevn** [comment]
Can you please show what `gpg` version is installed inside GA?

**Comment by cboulanger** [comment]
```
gpg (GnuPG) 2.2.4
libgcrypt 1.8.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/runner/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

`echo "TTY: $(tty)"` => `TTY: not a tty`

https://github.com/cboulanger/bibliograph/runs/1165110806?check_suite_focus=true#step:9:193

**Comment by cboulanger** [comment]
It would be super-duper if there was a GitHub Action for git-secrets ...
https://github.com/marketplace?category=security&type=actions

**Comment by cboulanger** [comment]
Do you know of an example of git-secret running in a GA? I am probably not the first to try...

**Comment by sobolevn** [comment]
None that I am aware of. I would be interested to see them!

**Comment by cboulanger** [comment]
I've done some amount of search but didn't find one, to my surprise. This would immediately change if you published a GitHub Action on the GH marketplace. 

Any idea what could be the problem?

**Comment by sobolevn** [comment]
Only my limited free time 😄

**Comment by antoscarface** [comment]
@cboulanger Just had the same issue and that is because you need to give the passphrase, so the terminal asks you an input, which doesn't work inside the job workflow :)

My fix was to add the passphrase as well in the `git secret reveal` command, by passing it with `-p` argument (as says the doc https://git-secret.io/git-secret-reveal), that is `git secret reveal -p "${{ secrets.GPG_PASSPHRASE }}" (obviously configured in the repo secrets).

Hope it helps as well.

**Comment by cboulanger** [comment]
@antoscarface That works, thank you very much. I was trying to use a key with no passphrase, I guess that‘s not supported (and probably doesn’t need to be).

@sobolevn Maybe you want to add code for GH Actions , something like https://github.com/cboulanger/bibliograph/blob/develop/.github/workflows/tests.yml#L55

**Comment by sobolevn** [comment]
@cboulanger awesome! Thanks a lot for the working example. 

Github Action will be published at some point.
