### ISSUE TITLE
remove wiki pages from git-secret's github setup, and integrate content from there into git-secret docs somehow

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#618]
I think we should retire the wiki and integrate any meaningful content into git-secret. 

We already have git-secret.io and the docs in git-secret.

**Comment by sobolevn** [comment]
Yes, I agree! 👍 

The only meaningful content there is 

> git-secret-diff allows you to compare encrypted files between specific commits or between a specific commit and your local changes. It makes use of the already existing git secret changes.

https://github.com/msilvestre/git-secret-diff

**Comment by sinnytk** [comment]
I'd like to take a look at this for Hacktoberfest, any tips on how would I start going about this?

**Comment by joshrabinowitz** [comment]
Maybe put the script and README from the git-secret-diff repo into a directory in git-secret called `/contrib`?
