### ISSUE TITLE
will add subcommand add --all?

### ISSUE THREAD

**Issue by sandylaw** [sobolevn/git-secret#619]
What are the steps to reproduce this issue?
-------------------------------------------

1. Now `git secret add file ` will add one file, how can use command to add all files  in the current repo directory to encrypt?

2. I wish add one subcommand :   `git secret add --all`
             == 
 `find . ! -path "./.gitignore/*" ! -path "./.git/*" ! -path "./.gitsecret/*" ! -path "./.gitignore" ! -path "./.git" ! -path "./.gitsecret" -exec git secret add {} \;`

Well, I have used shell script to make it.

Thank you.

**Comment by joshrabinowitz** [comment]
@sobolevn do you think we should add an `-a` feature to 'git secret add` that adds all the relevant files in the repo to git? 

On one hand, it seems like overkill; on the other hand (and someone explicitly asking for this feature shows there's some demand), I can see it being useful for people who are using a git repo specifically to use git-secret on every file in the repo.

**Comment by sobolevn** [comment]
I think that `-a` is an overkill for `git secret add`

```sh
find . ! -path "./.gitignore/*" ! -path "./.git/*" ! -path "./.gitsecret/*" ! -path "./.gitignore" ! -path "./.git" ! -path "./.gitsecret" -exec git secret add {} \;
```

This does not seem like a big deal for me, because it is:
- a rare case
- a command that you only need to run once
- might be customized by other use-cases
