### ISSUE TITLE
Release new version of git-secret, because it's been about a year and there are fixes/features

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#621]
See https://github.com/sobolevn/git-secret/blob/master/CHANGELOG.md
for changes since 0.3.2

In particular:
- #552, #508, #317, #290, #283, #238, #579, #607, #577, #603, #609

Also @gombosg asked me about us making a new release

**Comment by gombosg** [comment]
Haha! Thanks, packaged the update! :)

**Comment by joshrabinowitz** [comment]
Closed by release of v0.3.3
