### ISSUE TITLE
Support for extra gpg options, like --armor

### ISSUE THREAD

**Issue by jpbochi** [sobolevn/git-secret#630]
This is a feature request/suggestion.

## Rationale

Right now, with `SECRETS_…` env vars, it's possible to pass in options like `--verbose` and `--pinentry`. It would be nice to make that more extensible. Upgrading that to an options file, rather than only env vars, would probably be good.

### Examples

One `gpg` option I'm particularly interested is `--armor`, since I'd personally prefer to commit armored files rather than binaries. Another option that might be useful for other is `--trust-model`. One idea [that may or may not be bad] to implement these would be to allow `git secret hide --armor` and `git secret reveal --trust-model tofu+pgp`.

## Implementation suggestion

I think git-secret needs to grow out of receiving configuration _only_ via env vars, and start reading from a config file. To avoid everyone having yet another config file, it could rely on git config. Git does allow for any custom sections to be put there. The "secrets" and "secret" are not sections taken, so git config --default "${SECRETS_GPG_COMMAND:-gpg}" --get secrets.gpgcommand would work and be backwards compatible.

`tig`, which is an excellent tool extending git, also accepts configuration to it saved directly in git config. See https://jonas.github.io/tig/doc/tigrc.5.html#_git_configuration That might serve as inspiration.

**Comment by sobolevn** [comment]
`--armor` is now supported! Thanks!
