### ISSUE TITLE
store '-armor' versions of .secret files instead of binary versions, so they're ascii and not binary

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#631]
In #630, @jpbochi suggested he'd "personally prefer to commit armored files rather than binaries", which is a good idea.

**Comment by joshrabinowitz** [comment]
I think this may fix #136

**Comment by jonjensen** [comment]
I mentioned this in a pending PR already - https://github.com/sobolevn/git-secret/pull/661#discussion_r627719375 - but I prefer the current behavior of storing as binary by default. Seems like --armor would be a nice user-configurable option, but binary seems the better default. Has anyone mentioned actual problems with storing binary blobs in Git as git-secret has always done before?

**Comment by sobolevn** [comment]
Done!
