### ISSUE TITLE
Bintray is going away

### ISSUE THREAD

**Issue by dkrutsko** [sobolevn/git-secret#646]
According to [this blog post](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter), Bintray is being retired May 1st. I believe this project will be affected as some of your artifacts, like RPM, are being stored there.

**Comment by sobolevn** [comment]
Oh, bad news 😢

**Comment by Fouppy** [comment]
Any plans to move packages somewhere else?

**Comment by StephenMP** [comment]
Bintray finally bit the dust, we switched to installing from source which works; however, may be good to look at getting a debian package hosted somewhere?

**Comment by joshrabinowitz** [comment]
@Fouppy / @StephenMP  Do you (or other users of git-secret) have suggestions about which package hosting service we should consider?

**Comment by dkrutsko** [comment]
As a stopgap measure, why not just host repository files directly on GitHub through their releases feature?

**Comment by Neamar** [comment]
Agreed, hosting on Github would be a good way to fix the issue :)

**Comment by joshrabinowitz** [comment]
@sobolevn can you make this change?

**Comment by sobolevn** [comment]
Yes! 👍

**Comment by Neamar** [comment]
Hi!

![image](https://user-images.githubusercontent.com/536844/116726291-5d204b80-a9e3-11eb-8ddb-96b46d39df41.png)

Bintray is going away in a couple hours, and the current installation procedure is still using it. Is there any other methode that can be used?

**Comment by sobolevn** [comment]
I have reached GitHub engineers and consulted their docs, GitHub releases cannot be used as an alternative for Bintray yet. Because it does not provide `apt`-compatible interface.

There's https://packagecloud.io/l/apt-repository
But, I will need more time to research it.

**Comment by Neamar** [comment]
I see. Otherwise, can we host the actual binary (without apt) to be downloaded as a release?

For instance, just hosting the .deb file? This way users can `dpkg -i` the file.

**Comment by sobolevn** [comment]
I guess that in our case it would be easier to host just a text file, because `git-secret` is written in `bash`, so it can be as easy as just dropping a single text file into `$PATH`.

This is, of course, a temporary fix, utill we can fully move to a new hosting provider.

**Comment by dkrutsko** [comment]
@sobolevn in the meantime, maybe the repository packages can just be stored in GitHub's release infrastructure? We can, for example, download the RPM and install it locally on our systems.

**Comment by sobolevn** [comment]
I have attached deb release here: https://github.com/sobolevn/git-secret/releases/tag/0.4.0.alpha1

Please, check that it is valid and signed properly.
Sorry for the fuzz! I am communicating with several providers, there are no free options at the moment.

Any ideas are welcome 🙂

**Comment by gombosg** [comment]
@sobolevn is this alpha safe to package in Fedora/EPEL? Or should I wait for the final?

**Comment by dkrutsko** [comment]
Would you be able to attach the rpm as well please?? It'll be good enough until a suitable alternative can be found. I'm also wondering if GitHub itself can be used as a repository for debian and rpm as well. Since it's just a file structure at the end. Not sure if GitHub would be too happy about that though.

**Comment by sobolevn** [comment]
Done! https://github.com/sobolevn/git-secret/releases/download/0.4.0.alpha1/git-secret-0.4.0.alpha1-1.noarch.rpm

**Comment by Levino** [comment]
I think the docs should be updated. I am struggling a little bit on how exactly to fix this...

**Comment by dkrutsko** [comment]
@Levino So instead of adding a repo and installing the package through the package manager, you're going to download the `*.deb` or `*.rpm` file and use the package manager to initiate a local install. So something like `sudo dpkg -i /path/to/file.deb` or `sudo yum localinstall /path/to/file.rpm`

**Comment by venux92** [comment]
@dkrutsko so you mean we can't do something like this anymore?
```
echo "deb https://github.com/sobolevn/git-secret/releases/tag/0.4.0.alpha1 git-secret main" | sudo tee -a /etc/apt/sources.list
wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
sudo apt-get update && sudo apt-get install git-secret
```

Why trying to understand why I was getting
`Failed to fetch https://github.com/sobolevn/git-secret/releases/tag/0.4.0.alpha1/dists/git-secret/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)`

Does this mean we don't need to verify the signature anymore? 🤔

**Comment by sobolevn** [comment]
@venux92 because GitHub sadly does not support `apt` repositry interface, so @dkrutsko is right. You have to manually download `git-secret` with `wget` or whatever and then use `dpkg -i`.

My ETA on new hosting provider is the end of this week. Right now I am wondering if Artifactory will work for us.
https://jfrog.com/pricing/

**Comment by dkrutsko** [comment]
We've been using Artifactory (self-hosted) since September of last year, it's a fantastic product but the licensing isn't the cheapest thing out there. Their open source version is free but limited to a single repository. I guess you're looking at their hosted solution though, right? I was going to say if you're self hosting you might be able to just set up two Artifactory free Artifactory instances for each repository. But maybe they host open source projects for free.

**Comment by sobolevn** [comment]
Looks like it is possible 🤔 
<img width="1280" alt="Снимок экрана 2021-05-03 в 17 22 11" src="https://user-images.githubusercontent.com/4660275/116888424-242ae580-ac34-11eb-8409-10f265a6b622.png">

**Comment by dkrutsko** [comment]
@sobolevn Yeah the limitation is with the self-hosted version, not the cloud version, unless they changed something. For the GPG key, you may also want to add it as a `.gpg` file as part of the release so we can simply download it to perform a manual GPG check.

Also, according to [this comment](https://github.com/tetratelabs/getenvoy/issues/196#issuecomment-829238231), JFrog pushed back the date to July 4th? I can't confirm that since I did get some forbidden errors, but it's worth pointing out in case it is true.

Finally, here's the full commands I use for installing on CentOS (Amazon Linux) and Debian (Ubuntu):

```bash
# RPM
curl -sSL -o /tmp/git-secret.rpm https://github.com/sobolevn/git-secret/releases/download/0.4.0.alpha1/git-secret-0.4.0.alpha1-1.noarch.rpm
sudo yum -y localinstall /tmp/git-secret.rpm

# DEB
curl -sSL -o /tmp/git-secret.deb https://github.com/sobolevn/git-secret/releases/download/0.4.0.alpha1/git-secret_0.4.0.alpha1_all.deb
sudo dpkg -i /tmp/git-secret.deb
```

**Comment by sobolevn** [comment]
Oh wow, Artifactory even has Alpine repos!
<img width="938" alt="Снимок экрана 2021-05-03 в 22 51 34" src="https://user-images.githubusercontent.com/4660275/116925710-3754aa00-ac62-11eb-9328-878efb0d96f8.png">

**Comment by sobolevn** [comment]
It works! 
<img width="752" alt="Снимок экрана 2021-05-03 в 23 35 55" src="https://user-images.githubusercontent.com/4660275/116930362-5b1aee80-ac68-11eb-8fd4-a4d8370361e9.png">

Try it out (this is still alpha and may change):

```bash
sudo sh -c "echo 'deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main' >> /etc/apt/sources.list"
wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
apt-get install git-secret
```

**Comment by pgaxatte** [comment]
I'm having an issue with jfrog's artifactory on ubuntu 18.04 when running `apt-get update` after adding the repo:
```
[...]
Ign:6 https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret InRelease
Err:7 https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret Release
  404  Not Found [IP: 20.71.12.238 443]
Reading package lists...
E: The repository 'https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret Release' does not have a Release file.
```

**Comment by pgaxatte** [comment]
Looking at the repo, it is expected since only debian releases are created.

**Comment by sobolevn** [comment]
@pgaxatte what distro are you using? Ubuntu?

**Comment by p-schneider** [comment]
I think due to a recent change in the folder structure of the repository the releases you would now hat to use a repository like this:
`deb https://gitsecret.jfrog.io/artifactory/git-secret-deb buster main`

So for now you can edit your `/etc/apt/sources.list` once more and replace `...git-secret main` with `...buster main`.

I know it worked when @sobolevn originally posted the new repository settings for `/etc/apt/sources.list`, but then it stopped working later.

Unless git-secret has specific dependencies that are named differently on ubuntu (18.04=>bionic) than on debian (buster) that buster repository should also work on Ubuntu (bionic/focal/etc.).
Ideally there would be subfolders in https://gitsecret.jfrog.io/artifactory/git-secret-deb/dists/ called bionic (Ubuntu 18.04) and focal (Ubuntu 20.04), if there are ubuntu specific builds and dependencies. But if that's not the case we could use a "common" folder like it originally had (the folder was called "git-secret" before).

**Comment by hpolonskaya** [comment]
How to get git-secret  version Ubuntu 20.04?

**Comment by p-schneider** [comment]
> How to get git-secret version Ubuntu 20.04?

Normally wait for this ticked to be closed and a official/updated instruction is available in the readme. -> https://git-secret.io/installation
But for now you can do this:
```
sudo sh -c "echo 'deb https://gitsecret.jfrog.io/artifactory/git-secret-deb buster main' >> /etc/apt/sources.list"
wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
apt-get install git-secret
echo -n "Hello World - oh, wait, you do not have to run this command   :-)"
```
_If at some point a subfolder "focal" is created in https://gitsecret.jfrog.io/artifactory/git-secret-deb/dists/ you could then edit your `/etc/apt/sources.list` file to use that (by replacing `...git-secret-deb buster main` with `git-secret-deb focal main`)._

**Comment by hpolonskaya** [comment]
Thank you it's breaking our Ci/cd

**Comment by sobolevn** [comment]
New installation docs is now live: https://git-secret.io/installation

It should just work for `deb` and `rpm` releases. Please, make sure to report any problems.
At this point, I treat them as bugs!

**Comment by 030** [comment]
@sobolevn Just followed the new instructions for deb and it seems to install 0.4.0 on Ubuntu:

```
git secret --version
0.4.0
```

Could you confirm whether that is correct?

**Comment by p-schneider** [comment]
Yes, that's correct.
Yesterday the version was `0.4.0.alpha1`, and ubuntu thinks `0.4.0` is older/lower than `0.4.0.alpha1`.
So for those having yesterday's `0.4.0.alpha1` version installed the upgrade (or, as ubuntu would say, downgrade) to `0.4.0` could be done by this command: `sudo apt install git-secret=0.4.0`

**Comment by sobolevn** [comment]
Yes, this is correct. `0.4.0` is the latest version.

**Comment by 030** [comment]
Related https://github.com/sobolevn/git-secret/issues/656
