### ISSUE TITLE
git-secret/src/_utils/_git_secret_tools_linux.sh has wrong call to function for a variable assignment

### ISSUE THREAD

**Issue by bunkiedc** [sobolevn/git-secret#647]
What are the steps to reproduce this issue?
-------------------------------------------
1. …The problem occurs when using the -P option to git secret hide
2. …
3. …

What happens?
-------------
…causes an error to be thrown to the screen when it fails to execute the variable assignment

What were you expecting to happen?
----------------------------------
…not to complain

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
It's pretty clear what the issue is, it occurs on line 39 of the file.
IS:  stat_is_busybox=_exe_is_busybox "stat"
SB: stat_is_busybox="$(_exe_is_busybox "stat")"

Any other comments?
-------------------
Works fine after changing the assignment…

What versions of software are you using?
----------------------------------------

**Operating system:** (`uname -a`) …
Linux Docker-Server 5.4.0-64-generic #72~18.04.1-Ubuntu SMP Fri Jan 15 14:06:34 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`) …
/usr/bin/git-secret
**`git-secret` version:** (`git secret --version`) …
git secret --version
0.3.2
**`git` version:** (`git --version`) …
git version 2.17.1
**Shell type and version:** (`$SHELL --version`) …
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
**`gpg` version:** (`gpg --version`) …
gpg (GnuPG) 2.2.4
libgcrypt 1.8.1

**Comment by joshrabinowitz** [comment]
@bunkiedc thank you for this issue report. 
I will take a look in the next few days and probably submit a PR to fix this. 
Can you retest with Busybox after I make the proposed change?

**Comment by joshrabinowitz** [comment]
@bunkiedc can you please test #648

**Comment by bunkiedc** [comment]
Hi Josh.  I'm not using busybox, just the -P option, and it failed onthat line.


-----Original Message-----

**Comment by joshrabinowitz** [comment]
@bunkiedc it failed with my change, or without it? 
Can't tell if you tested #648

**Comment by bunkiedc** [comment]
Hi Josh,I haven't tested your change... I'm not using busybox, just Ubuntu cmd line.It failed on that line regardless of using busybox or not, once the -P is invoked.
Your change looks okay to me.  If you want me to try it with my environment, I cando that later today.


-----Original Message-----

**Comment by joshrabinowitz** [comment]
@bunkiedc yes please do, thank you

**Comment by bunkiedc** [comment]
Josh,The patch works great!thanks for your work!!
best,       dave


-----Original Message-----
