### ISSUE TITLE
Do we really need the sha-256 hashes in mapping.cfg

### ISSUE THREAD

**Issue by ikhomyakov** [sobolevn/git-secret#649]
It appears that sha-256 hashes in `.gitsecret/paths/mapping.cfg` are more a hindrance than help: 

1. They are never used by any other git-secret commands.
2. They increase the likelihood of merge conflicts. `.gitsecret/paths/mapping.cfg` changes every time when any secret file changes, and therefore one extra file to worry about during commits and merges.
3. This verification mechanism appears to be redundant to GnuPG's partial tampering verification (MDC?) and potentially is a security risk because it may reveal some additional information about the clear text content to an adversary.
4. If an adversary manages to change and re-encrypt the secret files in their entirety, then the adversary can also update the hashes. If protection is needed to prevent this, GnuPG signature that uses the private key of committer can be considered.  

**We propose to remove the hashes from `.gitsecret/paths/mapping.cfg`**

We are running git-secret version 0.3.3. 

Edit: realized that our workaround doesn't work. Thanks for the clarifications provided by @hurricanehrndz (issues #107 and #92).  I am removing the workaround description so that other folks dont follow this incorrect workaround.

**Comment by hurricanehrndz** [comment]
@ikhomyakov 

It has been a while since I have taken a look at the codebase. This feature was originally introduced to resolve the following #107 

I am assuming today you are using git filters, if that is the case I do not see the need to keep the hashes.

**Comment by hurricanehrndz** [comment]
PS really sorry for bringing up such an old commit and how bad my commit messages were in the past. Ewee.

**Comment by ikhomyakov** [comment]
Thanks for the pointers! This is perfect -- I think I understand the issue now and why the hashes were introduced. Let me process this information a bit and I will get back .

**Comment by ikhomyakov** [comment]
By the way, we are not using using filters, we are using git-secret in a manual mode, i.e. running git-secret commands manually.

**Comment by hurricanehrndz** [comment]
No worries. At the time that was the most elegant solution, I could come up with. There may be a better approach today, but that would require getting caught with a lot of changes.

**Comment by joshrabinowitz** [comment]
@hurricanehrndz I'm here to answer any questions!!!!

**Comment by ikhomyakov** [comment]
We just realized that the workaround that I described earlier doesn't work. Thanks for the clarifications provided by @hurricanehrndz (issues #107 and #92). I have removed the workaround description so that other folks wouldn't fall for the same trap.

**Comment by ikhomyakov** [comment]
Thanks guys. Now I understand why the hashes were introduced in the first place and how they are used by `git-secret hide -m` to encrypt only only those secret files that were modified -- it is a needed feature and after all the implemented solution with hashes in mapping.cfg appears to be quite elegant and does the job and the potential issues it introduces (items #2 and #3 in the original issue description above) are minimal. 

One question:  in #92 @kingpong proposed the following approach which was approved by @sobolevn who said that "I think that this is a nice way to solve it.":

	1. Encrypt the plaintext and store the ciphertext in a temp file.
	2. Decrypt the original ciphertext (if it exists).
	3. Extract the list of public keys from the original ciphertext (if it exists).
	4. If old(plaintext,pubkeys) == new(plaintext,pubkeys), delete the temp file and continue.
	5. Replace the ciphertext with the temp file.

It appears that this approach addresses #92 even without the need to keep the hashes in mapping.cfg. Why this approach wasn't used to implement #92?

**Comment by hurricanehrndz** [comment]
Yes the solution you proposed will work, there is a potential for secret leakage so that will need to be taken into consideration.

I will pin something back soon, so that we ensure secrets do not get leaked.

Otherwise, I think it is a sensible approach and I know of other tools that do it in the manner.

**Comment by ikhomyakov** [comment]
@hurricanehrndz, could you clarify what potential secret leakage you are referring to? 

If we were to implement @kingpong's proposal, I would enhance it a little bit roughly as follows: 
1. Calculate sha-256 of the plaintext (if plaintext exists): **h1**. If plaintext doesn't exist, then Skip the rest.
2. Decrypt the ciphertext (if it exists and if the user has the private key) and Calculate sha-256 hash on the fly (don't touch the disk): **h0**
3. Extract the list of public keys from the original ciphertext (if it exists): **k0**
4. Extract the list of public keys from the pubring, i.e. `git-secret whoknows` (this list should exist and be non-empty): **k1**
5. If **plaintext exists** and **(h1, k1) != (h0, k0)** then Encrypt the plaintext else Do nothing.

**Comment by hurricanehrndz** [comment]
Something similar to this issue is a potential depending on the implementation. I think as long as the permissions are set correctly on temp files and an appropriate umask is set, you will be golden. 

https://github.com/ryantm/agenix/issues/1

**Comment by ikhomyakov** [comment]
@hurricanehrndz, please note that the enhanced solution does not use any temporary files.

**Comment by hurricanehrndz** [comment]
@ikhomyakov 

My apologies, I totally glanced over the updated proposal. Looks good!

**Comment by ikhomyakov** [comment]
If no one objects, I will close this issue because the benefits do not seem significant enough to warrant this change. 

However, if you guys would like to go this route and try to simplify git-secret even more, here are two more questions: 

2) **Do we really need mapping.cfg?** Extension ".secret" is special anyway. Why not pick up the secret files by simply traversing the file tree by extension? Another option is to create a shadow subtree ".vault" with the same directory structure as the main tree and keep all encrypted files there.

3) **Do we really need the pubring inside the repo?** It appears that one of the design choices was that all encrypted files have to be decryptable by all recipients whose public keys are on repo's pubring, however, git-secret cannot ensure this. Why try to achieve this? What not allow each secret file to have its own list of recipients? GPG supports it and it covers more use cases where , for example, in one repo we want to store secrets destined for different environments (e.g. development and production). When we add a new secret file, we can specify the list of recipients (emails) and git-secret can use our own default pubring to encrypt the file. Later when we change the content and reencrypt, git-secret can derive the list of recipients from the older version.

### Extra Thought

Currently git-secret provides a set of its own commands separate from git commands. Not sure how feasible it would be but what we tried to implement a thin wrapper around git to make git aware of secret files?

For example, we would still have the following genuine git-secret's commands like (I have renamed the first two to avoid confusion with git-add and git-rm):

* `classify [plain…] [-r receipient…]` - to make a new secret file (currently known as `git-secret add`)
* `declassify [plain…]` - what's currently known as `git-secret remove`
* `hide [plain…] [-r receipient…]` - encrypts or re-encrypts “plain” to “.plain.gpg” if contents or recipients are different
* `reveal [plain…]` - decrypts secret file

In addition the following commands (or at least some of them) can be implemented as (hopefully thin) wrappers around git, i.e. make git aware of secret files: add, rm, mv, status, diff, checkout, merge, rebase...

Also could be interesting to add capability to encrypt/decrypt separate fields inside certain formats like in Ansible.

Please let me know what you guys think, and again, thanks for the existing very elegant product that we use successfully in Columbia University!
