### ISSUE TITLE
Why is there a "hyphen" missing from some of your documentation?

### ISSUE THREAD

**Issue by jradxl** [sobolevn/git-secret#655]
What are the steps to reproduce this issue?
-------------------------------------------
1. … Read the documentation, and realise there is a difference between
git-secret init
AND
git secret init

What happens?
-------------
Complete confusion to a first time user.

What were you expecting to happen?
----------------------------------
Your command is "git-secret"

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
Error message thus, missing hyphen
```
git-secret init
git-secret: abort: not in dir with git repo. Use 'git init' or 'git clone', then in repo use 'git secret init'

```

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
Linux z390ma 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`) …
which git-secret
/usr/bin/git-secret

**`git-secret` version:** (`git secret --version`)  <<< SEE WHAT I MEAN!!
git-secret --version
0.3.2

**`git` version:** (`git --version`) …
git --version
git version 2.27.0

UPDATE:
SEE https://git-secret.io/

Also, sorry, it's your competitor "git-secrets" that's worst.
but you do have some

**Comment by mrampant-nist** [comment]
aren't they both the same command?

**Comment by sobolevn** [comment]
I would appreciate a fix, we should refer to `git-secret` as `git-secret` 🙂
