### ISSUE TITLE
forbidden while trying to download https://dl.bintray.com/sobolevn/deb/git-secret_0.3.3_all.deb

### ISSUE THREAD

**Issue by 030** [sobolevn/git-secret#656]
Since today, it does not seem to be possible to download the git-secret debian packages from bin tray anymore.

**Comment by cyril94440** [comment]
Same happening here! All CI/CD down :(

**Comment by 030** [comment]
Could the debian packages be moved to the releases section of [github](https://github.com/sobolevn/git-secret)?

**Comment by sobolevn** [comment]
Looks like GitHub cannot store `deb` releases the same way BinTray did. 

There are different tools to emulate it: https://github.com/rpatterson/github-apt-repos
But, it does not seem good enough.

**Comment by venux92** [comment]
any workaround?
I'm having the same issue: `The repository 'https://dl.bintray.com/sobolevn/deb git-secret InRelease'` is not signed

**Comment by sobolevn** [comment]
I have attached `deb` release here: https://github.com/sobolevn/git-secret/releases/tag/0.4.0.alpha1

Please, check that it is valid and signed properly.
Sorry for the fuzz! I am communicating with several providers, there are no free options at the moment.

Any ideas are welcome 🙂

**Comment by sobolevn** [comment]
Let's move to https://github.com/sobolevn/git-secret/issues/646

**Comment by 030** [comment]
Related https://github.com/sobolevn/git-secret/issues/646
