### ISSUE TITLE
Broken installation using Bintray APT repository (403 Forbidden)

### ISSUE THREAD

**Issue by TAnas0** [sobolevn/git-secret#665]
What are the steps to reproduce this issue?
-------------------------------------------
1. Visit https://dl.bintray.com/sobolevn/deb

This endpoint is referenced in here as an installation method: https://github.com/sobolevn/git-secret/blob/19941f91f42b95ea3b003a499618ebe629e0433e/docs/_posts/2021-05-05-git-secret.md#L96

What happens?
A `Forbidden 403` error response

What were you expecting to happen?
----------------------------------
See the contents of the repository

Any logs, error output, etc?
----------------------------
Please not the issue was initially faced in a Github Action, part of a CI pipeline.
Here is the relevant output:
```
Run echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | sudo tee -a /etc/apt/sources.list
deb https://dl.bintray.com/sobolevn/deb git-secret main
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:5 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:7 https://download.mono-project.com/repo/ubuntu stable-focal InRelease
Hit:8 https://packages.microsoft.com/repos/azure-cli focal InRelease
Hit:9 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Hit:10 http://ppa.launchpad.net/apt-fast/stable/ubuntu focal InRelease
Get:6 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [9383 B]
Hit:11 http://ppa.launchpad.net/hvr/ghc/ubuntu focal InRelease
Err:12 https://dl.bintray.com/sobolevn/deb git-secret InRelease
  403  Forbidden [IP: 34.214.135.19 443]
Hit:13 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
Reading package lists...
E: Failed to fetch https://dl.bintray.com/sobolevn/deb/dists/git-secret/InRelease  403  Forbidden [IP: 34.214.135.19 443]
E: The repository 'https://dl.bintray.com/sobolevn/deb git-secret InRelease' is not signed.
Error: Process completed with exit code 100.
```

Any other comments?
-------------------
I visited the link manually, got a 403 and thought it is worth mentioning.
Please not the installation went fine when I tried it on an Ubuntu machine using `docker run -it --entrypoint bash ubuntu:18.04`

I fixed the issue by switching to the different APT repositories mentioned in https://git-secret.io/installation
This may just a piece of old documentation (see reference above) that broke my CI.

**Comment by sobolevn** [comment]
Thanks! I have missed this one!

**Comment by sobolevn** [comment]
Closed by https://github.com/sobolevn/git-secret/commit/295a4eeb4f8708f35f0200557cc976cb124079a6
