### ISSUE TITLE
Enable dependabot

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/git-secret#670]
What do we need?
1. Ruby deps here: https://github.com/sobolevn/git-secret/tree/master/docs
2. Docker updates in our release / test envs
3. Github Actions updates

**Comment by sobolevn** [comment]
It is working: https://github.com/sobolevn/git-secret/blob/master/.github/dependabot.yml

<img width="926" alt="Снимок экрана 2021-05-20 в 11 41 26" src="https://user-images.githubusercontent.com/4660275/118947779-56d91b80-b960-11eb-88fa-aab54b66b0aa.png">

Next, I will probably need to fix how `docker`-based checks are executed, because we don't really need the latest version in most cases.

**Comment by joshrabinowitz** [comment]
Closing, we have dependabot enabled.
