### ISSUE TITLE
Reveal different secrets for different keys/environments

### ISSUE THREAD

**Issue by kuvaldini** [sobolevn/git-secret#673]
Imagine given several environments on CI. Every env has own key to reveal git-secret.
It would be great if git-secret decrypts different secrets according to the input key.

I think it is possiple to implement using different git-secret instances/folders

**Comment by sobolevn** [comment]
You can use different secret dirs via `SECRETS_DIR` env var. So, each secret dir would have different secrets and different permissions.

For example:
- `.gitsecret.dev`
- `.gitsecret.ci`
- `.gitsecret.prod`

If you want to use the same secret database, but just revealing different files based on some external logic - then use `git secret reveal $FILENAME`

Does this solve your problem?

**Comment by kuvaldini** [comment]
Yes, it does. But need additional external logic. And need to keep several git-secret instances. The only bad thing that consumer should keep in mind from which folder he should take secrets - lets try everyone! ;)
