### ISSUE TITLE
git secret reveal - password input stalls

### ISSUE THREAD

**Issue by samothx** [sobolevn/git-secret#674]
What are the steps to reproduce this issue?
-------------------------------------------
1. call `git secret reveal` with no options
2. enter password and press enter on password prompt

What happens?
-------------
nothing, password prompt stays visible, no linefeed after entering password and the program only terminates after pressing ctl c.

What were you expecting to happen?
----------------------------------
checking out of secret files and return to command prompt

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating system:** Linux ymir 5.12.2-1-MANJARO #1 SMP PREEMPT Fri May 7 17:53:15 UTC 2021 x86_64 GNU/Linux 

**`git-secret` path:** /usr/bin/git-secret

**`git-secret` version:** 0.4.0 

**`git` version:** 2.31.1 

**Shell type and version:** zsh 5.8 (x86_64-pc-linux-gnu)

**`gpg` version:** gpg (GnuPG) 2.2.27

**Comment by sobolevn** [comment]
@joshrabinowitz I remember that something like that had already happened.

**Comment by joshrabinowitz** [comment]
This sounds a lot like #97 and/or #503.
Might this be related to some sort of `pinentry` issue?

**Comment by FanchenBao** [comment]
I suddenly got hit with this problem as well. So I closed the terminal and opened up a new one, and the problem was gone.

**Comment by joshrabinowitz** [comment]
I seem to remember this could happen if one changed from `root` to another user using `sudo` and THEN interacted with gnupg. Can anyone confirm/deny?
