### ISSUE TITLE
My colleagues can't execute killperson

### ISSUE THREAD

**Issue by vctrsmelo** [sobolevn/git-secret#676]
What are the steps to reproduce this issue?
-------------------------------------------
1. git secret init
2. git secret tell any-key-mail@any.com
3. git secret killperson any-key-mail@any.com

What happens?
-------------
```
$ git secret killperson any-key-mail@any.com
gpg: error running '/usr/local/Cellar/gnupg/2.3.1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: there is a secret key for public key "any-key-mail@any.com"!
gpg: use option "--delete-secret-keys" to delete it first.
```

What were you expecting to happen?
----------------------------------
`killperson` command to work as expected.

Any other comments?
-------------------
It is happening in a project I work. On my computer the command works perfectly, but for my colleagues this error happens. If they create another project, initialize git and git-secret there, it works.

I created a branch, initialized git-secret and tried the commands. They worked. Then a colleague did the same thing during a call with me, but the killperson did not work.

We already tried:
* reinstalling gpg (the versions are the same).
* deleting and cloning the repository.
* recreating the keys.

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
Darwin Helenas-MBP 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

**`git-secret` path:** (`which git-secret`) …
/usr/local/bin/git-secret

**`git-secret` version:** (`git secret --version`) …
0.4.0

**`git` version:** (`git --version`) …
git version 2.30.1 (Apple Git-130)

**Shell type and version:** (`$SHELL --version`) …
zsh 5.8 (x86_64-apple-darwin20.0)

**`gpg` version:** (`gpg --version`) …
gpg (GnuPG) 2.3.1
libgcrypt 1.9.3
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Home: /Users/lahelena.leitao/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
AEAD: EAX, OCB
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by sobolevn** [comment]
@vctrsmelo do you include `.gitsecret/` folder into your `git`?

**Comment by vctrsmelo** [comment]
@sobolevn the `.gitsecret/` folder is created inside the `git` project folder when we execute `git secret init`.

My colleague tried deleting this `.gitsecret/` folder then executing `git secret init` again. This command apparently initializes git secret as expected, but the problem persisted when she called `tell` then `killperson` (the `tell` works, but `killperson` doesn't).

**Comment by joshrabinowitz** [comment]
Those errors are all coming from `gpg` and `gpg-agent`; I think this issue is  also probably related to at least one of the following:  the environment, the particular keys, and/or the email addresses used. 

Can you try running the commands after setting  `SECRETS_VERBOSE=1` , like this? It will turn off the --quiet option when invoking `gpg`:

````
export SECRETS_VERBOSE=1 
git secret killperson any-key-mail@any.com
````

If you continue to have issues, if you could provide a full example with (test) keys and steps to reproduce the problem on an another environment, that would be very helpful in debugging this.

**Comment by vctrsmelo** [comment]
Thanks for the answer, @joshrabinowitz.

Unfortunately, we could not get any other message than the one presented above.

As we are working in a remote context, it's hard even for me to test with them, as `git-secret` works as expected on my computer (even after removing and reading the keys, the same process they did). I tried even sending a (test) private key to her, but nothing worked, unfortunately.

It's really weird because my two colleagues could add a person, but neither was able to run `killperson` command.

Since we didn't find a solution after some days of researching, we decided to use another approach to handle secrets for now. We thought it would bring a process risk for the project if only I could remove persons (what happens if I leave the project, for example? They can't remove anyone, neither if they delete then re-run `git secret init`).

Anyway, thanks for the attention guys :)

**Comment by joshrabinowitz** [comment]
Sorry we were unable to debug this with you; this is a pretty unusual situation and we didn't get enough data to replicate.

**Comment by bstoss** [comment]
Hello
Iam facing the same issue right now but in our situation no one can remove any person ... its a bit weird i have to say.
The killperson command is trying to remove keys from the .gitsecret/keys folder but there as well secret keys.

When listing the public keys, everything looks fine, but when listing the secret keys i get some errors
`
gpg --homedir .gitsecret/keys -k
pub   ed25519 2021-06-08 [SC] [verfällt: 2023-06-08]
      XXXX
uid        [ unbekannt ] User Name <mail>
sub   cv25519 2021-06-08 [E] [verfällt: 2023-06-08]
etc ....

gpg --homedir .gitsecret/keys -K
gpg: Fehler bei Ausführung von `/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': Endestatus 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
`

When trying to delete the secret it shows this error as well, but still shows me the secret and asking me to remove it.
This is failing as well.

`
gpg --homedir .gitsecret/keys --delete-secret-key <mail>

gpg (GnuPG) 2.3.3; Copyright (C) 2021 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gpg: Fehler bei Ausführung von `/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': Endestatus 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error

sec  ed25519/XXX 2021-06-08 User Name <mail>

Diesen Schlüssel aus dem Schlüsselbund löschen? (j/N) j
Dies ist ein privater Schlüssel! - Wirklich löschen? (j/N) j
gpg: Fehler bei Ausführung von `/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': Endestatus 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: Fehler bei Ausführung von `/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': Endestatus 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: Fehler beim Löschen des privaten Schlüssels: No agent running
gpg: Fehler bei Ausführung von `/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': Endestatus 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: Fehler bei Ausführung von `/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': Endestatus 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: Fehler beim Löschen des privaten Unterschlüssels: No agent running
gpg: mail: delete key failed: No agent running
`

Something may not work with `gpg-agent`... but i dont get it. 
Sorry for the german logs btw .....

hope we can find a solution

**Comment by joshrabinowitz** [comment]
I now believe this was a permissions issue that stopped gpg-agent from starting
