### ISSUE TITLE
--no-cache option missing while installing apk package

### ISSUE THREAD

**Issue by 030** [sobolevn/git-secret#678]
https://git-secret.io/installation

```
apk add --update --no-cache git-secret
```

**Comment by sobolevn** [comment]
@030 can you please add `--no-cache` here? https://github.com/sobolevn/git-secret/blob/master/utils/apk/install.sh

**Comment by 030** [comment]
@sobolevn PR has been created.

**Comment by 030** [comment]
@sobolevn Thank you for merging the PR. Could you indicate when the changes will appear on https://github.com/sobolevn/git-secret/blob/master/utils/apk/install.sh?

**Comment by 030** [comment]
I just saw that it has been changed on the website.
