### ISSUE TITLE
--armour option should be given at te beginning of the gpg command

### ISSUE THREAD

**Issue by srvreeswijk** [sobolevn/git-secret#681]
What are the steps to reproduce this issue?
-------------------------------------------
1. gpg --export your.email@address.com --armor > public-key.gpg

What happens?
-------------
gpg gives a error:
gpg: Note: '--armor' is not considered an option

What were you expecting to happen?
---------------------------------
I expected the export to succeed and create a rsa ascii public key

Any logs, error output, etc?
----------------------------
gpg: Note: '--armor' is not considered an option

Any other comments?
-------------------
This is not an issue with git-secret but a request to update the documentation in: `man/man7/git-secret.7.md`
There on line 64 this example command is used. 
Please change it to:
`gpg --armor --export your.email@address.com > public-key.gpg`
Then it will work again as expected

What versions of software are you using?
----------------------------------------
OS: mac osX
gpg:
gpg (GnuPG) 2.3.1
libgcrypt 1.9.3

**Comment by joshrabinowitz** [comment]
@srvreeswijk can you submit a PR that fixes this?

**Comment by srvreeswijk** [comment]
No problem: https://github.com/sobolevn/git-secret/pull/682
