### ISSUE TITLE
Reconsider "killperson" command name

### ISSUE THREAD

**Issue by Tenzer** [sobolevn/git-secret#684]
As a person who just had to offboard a colleague who is terminally ill, having to enter a `killperson` command to remove their access to encrypted secrets leaves a very bad taste in my mouth.

Would you consider changing the command to be `removeperson`, `removeaccess` or similar which hopefully should be less offensive, and possibly keep `killperson` as an invisible alias?

**Comment by sobolevn** [comment]
Yeah, I think we should totally add a more pleasant and himane alias.

P.S.

> colleague who is terminally ill

Sorry to hear that...

**Comment by Tenzer** [comment]
Happy to hear you agree.

I've made a PR in #685 to rename it to `removeperson`.
