### ISSUE TITLE
upgrade copy of bats-core that is checked into the git-secret source code, so we're using latest (released) bats-core 1.3

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#701]
See https://github.com/bats-core/bats-core/tags

vendor/README.md from git-secret indicates that bats-core 1.3 was brought into the tree, but technically bats-core 1.3 wasn't released until after the code was re-imported

 (1.3 was officially released on May 8th; bats-core was imported into git-secret on May 3rd)

Perhaps @sobolevn has input?

**Comment by sobolevn** [comment]
@joshrabinowitz `bats@1.3.0` was released on March 3rd, not May 🙂 
<img width="353" alt="Снимок экрана 2021-07-08 в 19 17 42" src="https://user-images.githubusercontent.com/4660275/124956905-2f7a0300-e021-11eb-9212-5ac5a3e608b4.png">

And `git-secret@0.4.0` was released two month later on May 8th. 
It should be fine! 👍

**Comment by joshrabinowitz** [comment]
Oh I see, mixed up March and May! You are correct.
