### ISSUE TITLE
git secret cat not working when cd'ed to subdir

### ISSUE THREAD

**Issue by SadriG91** [sobolevn/git-secret#710]
What are the steps to reproduce this issue?
-------------------------------------------
1. git secret init
2. git secret tell my@email.com
3. git secret add file
4. git secret hide
5. git secret cat file 

(Note added by @joshrabinowitz : the steps above are not sufficient to replicate this bug. See my comment below for steps to replicate.)

What happens?
-------------
decrypt_message failed: No such file or directory 

What were you expecting to happen?
----------------------------------
cat encrypted file to stdout

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
gpg: can't open '/path/to/repo/file.secret': No such file or directory
gpg: decrypt_message failed: No such file or directory
git-secret: abort: problem decrypting file with gpg: exit code 2: /path/to/repo/file.secret

Any other comments?
-------------------
Even thought i am in the correct folder where secret file is once i run the command it shows the root_of_repo/file.secret instead root_of_repo/path/to/file.secret
gpg: can't open '/path/to/repo/file.secret': No such file or directory
but the file is in '/path/to/repo/folder/keys/file.secret'

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) Darwin C02F70UQML7L 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

**`git-secret` path:** (`which git-secret`) /usr/local/bin/git-secret

**`git-secret` version:** (`git secret --version`) 0.4.0

**`git` version:** (`git --version`) git version 2.31.0

**Shell type and version:** (`$SHELL --version`) zsh 5.8 (x86_64-apple-darwin20.0)

**`gpg` version:** (`gpg --version`) gpg (GnuPG) 2.3.1

**Comment by sobolevn** [comment]
Are you sure that you don't have any other files named `file` in the root of your repo? Seems like a path / name conflict to me.

You can always submit a failing test: https://github.com/sobolevn/git-secret/blob/master/tests/test_cat.bats
It would be a great help! 👍

**Comment by joshrabinowitz** [comment]
I think I understand what this is about. There's a bug with `git secret cat`

The hint is where OP talks about `git secret cat` using  `repo/file.secret instead repo/path/to/file.secret`. 

To replicate:

````
mkdir repo
cd repo
git secret init
git secret tell email@example.com
mkdir subdir
echo "contents!" > subdir/file.txt
git secret add subdir/file.txt
git secret hide
cd subdir
git secret cat file.txt
# above is where you'll get an error: it'll be looking for `repo/file.txt.secret` instead of `repo/subdir/file.txt.secret`
````
The same problem can exist in `cd subdir; git secret reveal file.txt` but is probably seen less because you don't have to pass `file.txt` to `reveal` (just calling `git secret reveal` will decrypt the file correctly)

**Comment by joshrabinowitz** [comment]
@sobolevn I've been looking into fixing this but am not sure where to make what change (I do understand the issue, though). 

Can you be provide guidance on how you'd like to see this bug fixed? Like what functions should be changed, and what code changes should be added?
