### ISSUE TITLE
Can't reveal or cat with keys without passwords

### ISSUE THREAD

**Issue by Repox** [sobolevn/git-secret#720]
What are the steps to reproduce this issue?
-------------------------------------------
1. Execute `git secret cat secret-content.txt.secret`
2.  Look at the `Enter passphrase: ` prompt

What happens?
-------------
Prompting for password. Will reveal secrets if I just press enter.

What were you expecting to happen?
----------------------------------
Not asking for password, since my keys are without passwords.

Any logs, error output, etc?
----------------------------
No.

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) Darwin MacBook-Pro-tilhrende-Dan.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

**`git-secret` path:** (`which git-secret`) /usr/local/bin/git-secret

**`git-secret` version:** (`git secret --version`) 0.4.0

**`git` version:** (`git --version`) git version 2.30.1 (Apple Git-130)

**Shell type and version:** (`$SHELL --version`) zsh 5.8 (x86_64-apple-darwin20.0)

**`gpg` version:** (`gpg --version`) gpg (GnuPG/MacGPG2) 2.2.27

**Comment by sobolevn** [comment]
Hi! Can you please clarify:

> Not asking for password, since my keys are without passwords.

Do you have `gpg` keys without password? Or do you have `gpg-agent` that stores the password for you?

**Comment by Repox** [comment]
> Do you have gpg keys without password? 

I have keys without passwords.

I'm being prompted to provide my password for the key I'm using and by just pressing enter I can decrypt the secret.

**Comment by sobolevn** [comment]
But, do you have `gpg-agent` set up?

**Comment by Repox** [comment]
Not for testing, I've ensured the gpg-agent is stopped by issuing `gpgconf --kill gpg-agent` before trying to reveal my secret.

**Comment by sobolevn** [comment]
Ok, I will ask differently 🙂 

When you work with any `gpg` commands that require an access to your secret key, `gpg` will ask you to enter your password (it does not really matter here how many chars you have: 0 or X). But, when you have `gpg-agent` set up properly, it can store the "password information" for you. So, `gpg` will not prompt you directly.

So, what happens when:
1. You try to use `git secret cat f.txt` with keys that have some non-empty password?
2. You try the same thing with `gpg-agent` enabled?

**Comment by Repox** [comment]
Took me a while, but I actually found that I somehow managed to create two keys with an empty passphrase instead of _no_ passphrase, which I have no idea how I managed. Editing the keys and issuing `passwd` to change the passwords allowed me to remove the passphrases and everything worked.

I'll close the issue.
