### ISSUE TITLE
Makefile install error 127 when running MINGW64

### ISSUE THREAD

**Issue by bennycode** [sobolevn/git-secret#722]
What are the steps to reproduce this issue?
-------------------------------------------
1. Open [Git Bash](https://gitforwindows.org/) (MINGW64) on Windows 10 Pro
2. Run `git clone https://github.com/sobolevn/git-secret.git git-secret`
3. Run `cd git-secret`
4. Run `make build`
5. Run `PREFIX="/usr/local" make install`

What happens?
-------------

Error 127 shows up:

```bash
bn@BENNY-RYZEN MINGW64 /c/dev/projects/git-secret (master)
$ make build
make: Nothing to be done for 'build'.

bn@BENNY-RYZEN MINGW64 /c/dev/projects/git-secret (master)
$ PREFIX="/usr/local" make install
C:/Program Files/Git/usr/bin/sh.exe ./utils/install.sh "C:/Program Files/Git/usr/local"
/usr/bin/sh: C:/Program: No such file or directory
make: *** [Makefile:25: install] Error 127
```

What were you expecting to happen?
----------------------------------

The `git-secret` tool should be installed successfully.

What versions of software are you using?
----------------------------------------
**Operating system:** MINGW64_NT-10.0-19042 BENNY-RYZEN 3.1.7-340.x86_64 2020-10-23 13:08 UTC x86_64 Msys (Windows 10 Pro)

**`git-secret` path:** no git-secret

**`git-secret` version:** no git-secret

**`git` version:** git version 2.29.2.windows.3

**Shell type and version:** GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

**`gpg` version:** gpg (GnuPG) 2.2.25

**Comment by sobolevn** [comment]
Ok, then the problem is in `build`, not in `git-secret` 🤔 

For now, you can just replace `make build` with `make git-secret`. But, I will provide a fix right now! 👍

**Comment by bennycode** [comment]
Hi @sobolevn and thank you for taking immediate action. Unfortunately, I still cannot install `git-secret`.

Here is what I did:

**1. Running `git pull`:**

```
$ git pull
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 2.60 KiB | 532.00 KiB/s, done.
From https://github.com/sobolevn/git-secret
   3b94a01..56e105b  master     -> origin/master
Updating 3b94a01..56e105b
Fast-forward
 Makefile | 12 ++++++------
 1 file changed, 6 insertions(+), 6 deletions(-)
```
 
**2. Running `make git-secret`:**
 
```
$ make git-secret
make: Nothing to be done for 'git-secret'.
```

**3. Running ` make build`:**

```
$ make build

```

**4. Running `PREFIX="/usr/local" make install`:**

``` 
$ PREFIX="/usr/local" make install
C:/Program Files/Git/usr/bin/sh.exe ./utils/install.sh "C:/Program Files/Git/usr/local"
/usr/bin/sh: C:/Program: No such file or directory
make: *** [Makefile:25: install] Error 127
```

Am I holding it wrong? 🤔

**Comment by sobolevn** [comment]
Thanks a lot, @bennycode! Would you be interested in helping us setting up windows CI? 🙏

**Comment by sobolevn** [comment]
Awesome! Happy to help! 👍

**Comment by bennycode** [comment]
After checking the [test setup](https://github.com/sobolevn/git-secret/blob/master/.github/workflows/test.yml) I saw that it requires a [Docker image](https://github.com/sobolevn/git-secret/tree/master/.ci/docker-ci) for Windows which has build tools (i.e. MinGW + GCC) installed and can run scripts from the [Makefile](https://github.com/sobolevn/git-secret/blob/master/Makefile).

Here is a draft PR for creating this: https://github.com/sobolevn/git-secret/pull/728
