### ISSUE TITLE
SHA256 mismatch with brew install

### ISSUE THREAD

**Issue by TribuneX** [sobolevn/git-secret#742]
What are the steps to reproduce this issue?
-------------------------------------------
1. Run `brew install git-secret`

What happens?
-------------
Install interrupts with the following error message:
```
==> Downloading https://git.savannah.gnu.org/cgit/guile.git/patch/?id=1f100a4f20c3a6e57922fb26fce212997e2a03cb
#=#=-#  #                                                                     
Error: git-secret: SHA256 mismatch
Expected: a5adf2586b30381cf24524c7fc0364115f7cb1f568d2b69a9f3fb49ad8355b55
  Actual: a857c5fde2eb1c05379a97ba88047404da1c5b1da0291903f036d0a8745d85b5
```

What were you expecting to happen?
----------------------------------
Successful install

What versions of software are you using?
----------------------------------------
macOS 12.0.1
Homebrew 3.3.9-42-gd1a8199

**Comment by sobolevn** [comment]
@TribuneX please report this here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-secret.rb

It is a packaging issue. Thank you!
