### ISSUE TITLE
killperson throws error deleting keys with 'utf-8' emails on US-ASCII configured system

### ISSUE THREAD

**Issue by bstoss** [sobolevn/git-secret#746]
What are the steps to reproduce this issue?
-------------------------------------------
1. install git-secret as documented
2. import public key from another person
3. git secret tell <mail>
4. hide and reveal files with the other person
5. git secret killperson <mail>

What happens?
-------------
I get an error from gpg that i have to delete the secret key at first.
```
git secret killperson <mail>
gpg: conversion from 'utf-8' to 'US-ASCII' failed: Illegal byte sequence
gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: there is a secret key for public key "<mail>"!
gpg: use option "--delete-secret-keys" to delete it first.
```

What were you expecting to happen?
----------------------------------
It removes the the connection to the user and `git secret whoknows`should not display the mail adress anymore

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Using `gpg -k`, `gpg --homedir -k` `gpg -K` works perfectly
Using `gpg --homedir .gitsecret/keys -K` does not work.
```
 gpg --homedir .gitsecret/keys -K
gpg: WARNING: unsafe permissions on homedir '/Users/bjornrossborsky-stoss/Documents/projects/DT-IT/LPS/lps-service-ios/.gitsecret/keys'
gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
```

There currently 7 entries in `whoknows`

Any other comments?
-------------------
Closed related issue #676 
I can do everything on my system gpg dir.
`git secret hide/reveal`works perfectly
`export SECRETS_VERBOSE=1` does not change the output

when trying to remove the secret key, i get the following error
```
gpg --homedir .gitsecret/keys --delete-secret-key <mail>
gpg: WARNING: unsafe permissions on homedir '<dir>/.gitsecret/keys'
gpg (GnuPG) 2.3.3; Copyright (C) 2021 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error

sec  ed25519/XXX 2021-06-08 Username <mail>

Delete this key from the keyring? (y/N) y
This is a secret key! - really delete? (y/N) y
gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: deleting secret key failed: No agent running
gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: error running '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': exit status 2
gpg: failed to start gpg-agent '/usr/local/Cellar/gnupg/2.3.3_1/bin/gpg-agent': General error
gpg: can't connect to the gpg-agent: General error
gpg: deleting secret subkey failed: No agent running
gpg: <mail>: delete key failed: No agent running
```

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
Darwin iBjorns-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

**`git-secret` path:** (`which git-secret`) …
/usr/local/bin/git-secret

**`git-secret` version:** (`git secret --version`) …
0.4.0

**`git` version:** (`git --version`) …
git version 2.30.1 (Apple Git-130)

**Shell type and version:** (`$SHELL --version`) …
zsh 5.8 (x86_64-apple-darwin20.0)

**`gpg` version:** (`gpg --version`) …
gpg (GnuPG) 2.3.3
libgcrypt 1.9.4
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/<user>/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
AEAD: EAX, OCB
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by jorritvdven** [comment]
I am facing the same problem. 

### Software versions:
**Operating system:** (`uname -a`) …
Darwin Jorrits-MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

**`git-secret` path:** (`which git-secret`) …
/usr/local/bin/git-secret
(/usr/local/bin/git-secret -> ../Cellar/git-secret/0.4.0/bin/git-secret)

**`git-secret` version:** (`git secret --version`) …
0.4.0

**`git` version:** (`git --version`) …
git version 2.22.0

**Shell type and version:** (`$SHELL --version`) …
zsh 5.8 (x86_64-apple-darwin21.0)

**`gpg` version:** (`gpg --version`) …
gpg (GnuPG) 2.3.4
libgcrypt 1.9.4
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/jorrit/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
AEAD: EAX, OCB
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by bstoss** [comment]
I created on a differnt mac a new project and faced a difference that could be releated to the issue.
In the folder `.gitsecret/keys` are more files now.

S.gpg-agent
S.gpg-agent.browser
S.gpg-agent.extra
S.gpg-agent.ssh

This files are not existing on my main project.
I have no idea why they don't exist. I tried to  reproduce this issue but on every clone and machine iam doing all the stuff, iam able to remove persons and have as well this socket files.

**Comment by joshrabinowitz** [comment]
ok, there's different issues happening in different examples above. The common theme is that `git secret killperson` tends to surface issues with git-secret keyrings.

To @bstoss:
One:
* in your first example you show gpg giving the error: `gpg: conversion from 'utf-8' to 'US-ASCII' failed: Illegal byte sequence`
* This is probably why you can't remove the key (which I presume has utf-8 characters in the email)

Two:
* in your other second example, using `gpg --homedir .gitsecret/keys -K`, you're getting the warning: `gpg: WARNING: unsafe permissions on homedir '/Users/bjornrossborsky-stoss/Documents/projects/DT-IT/LPS/lps-service-ios/.gitsecret/keys'`
* I think this permission warning stops the invocation of `gpg-agent`.  (BUT see the point below about how `.gitsecret/keys` shouldn't have any private keys in it.)

Three: 
* you show using `gpg --homedir .gitsecret/keys --delete-secret-key <mail>` to remove the `secret key` from the git-secret keyring. But the git-secret keyring shouldn't contain any private keys. You use your normal keychain in ~/.gnupg for management of your own private and public gpg keys; ` .gitsecret/keys` should only contain public key data.

Four: 
* in your last example, you ask about the files `S.gpg-agent`, `S.gpg-agent.browser` etc in your `.gitsecret/keys` directory. 
* I'm not sure what's up with these; I would recommend reading the docs to gpg-agent to try to figure out what use cases are creating those files.

@jorritvdven: 
* You don't show any of the error messages you receive specifically, so I'm not sure what's going on in your case.

Let me know if this helps you resolve your issues or if you have follow up questions!

**Comment by joshrabinowitz** [comment]
I think we should document the possibility of getting this error (`conversion from 'utf-8' to 'US-ASCII' failed: Illegal byte sequence`), and its resolution, in the docs for `removeperson`, and then close this issue
