### ISSUE TITLE
Add Alfred.preferences file / bundle

### ISSUE THREAD

**Issue by TribuneX** [sobolevn/git-secret#752]
What are the steps to reproduce this issue?
-------------------------------------------
1. Installed git-secret
2. Created a new git repo `git init` & `git secret init`
3. Copied the file [Alfred.preferences](https://www.alfredapp.com) into the new git repo
4. Encrypting the Alfred.preferences file with `git secret add`

What happens?
-------------
```
git secret add Alfred.alfredpreferences              
git-secret: abort: file not found: Alfred.alfredpreferences
```

What were you expecting to happen?
----------------------------------
Adding the file to `git` works as expected:
```
❯ git add Alfred.alfredpreferences
```

But it seems that these preferences are more behaving like a folder / bundle instead of a single file. I get similar issues when I try to add all files within a folder (while trying to encrypt my settings backup from [mackup](https://github.com/lra/mackup)

What versions of software are you using?
----------------------------------------
* macOS 12.0.1 on M1 Pro
* `git-secret` 0.4.0
* `git` version:** 2.34.1
* `gpg`  version  2.3.4

**Comment by sobolevn** [comment]
> But it seems that these preferences are more behaving like a folder / bundle instead of a single file

So, what is it? A folder? Or a single file?

**Comment by TribuneX** [comment]
Its called `Alfred.alfredpreferences`. I actually behaves like a bundle, so you can open it with the finder or navigate into it with `cd`. Storing it in a `git` repo looks like this (not my repo): https://github.com/haranrk/alfred-preferences.

Adding all files of a given folder including files within a subfolder should work? Since the man-page only mentions a list of files for `git secret add [file.txt]`.

**Comment by sobolevn** [comment]
So, it is a folder 🙂 

Then, you have to use `git secret add` on individual files inside it.

**Comment by joshrabinowitz** [comment]
closing because this is resolved
