### ISSUE TITLE
make sure ubuntu and brew versions of git-secret interoperate, because we've seen a report that they didn't

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#760]
In #758 's changes, @FanchenBao wrote about a current (2022-01-17) interoperability issue between OSX's Brew setup of git-secret, and "latest Ubuntu", this quotes him below:

> To be specific, `apt-get install gnupg` points to version [2.2.20](https://packages.ubuntu.com/impish/gnupg), yet `brew install gnupg` points to version [2.3.4](https://formulae.brew.sh/formula/gnupg) (as of 2022-01-17). 
> 
> Thus a `git-secret` encrypted file on macOS using the latest `gpg` installed from `brew` cannot be decrypted on Ubuntu (e.g. GitHub Actions' latest Ubuntu machine) using the latest `gpg` installed from `apt-get`. 
> 
> The work-around for this specific case is to downgrade `gpg` on brew with `brew install gnupg@2.2.33`.

**Comment by joshrabinowitz** [comment]
@FanchenBao , what version of Ubuntu are you using? 

According to https://packages.ubuntu.com/search?keywords=gnupg , it looks like Ubuntu 21.04 and 21.10 currently use gnupg 2.2.20; 20.04 (the LTS version) uses gnupg 2.2.19

Can anyone replicate that there is an interoperability issue between gnupg on (some) Ubuntu's and brew?

**Comment by FanchenBao** [comment]
The Ubuntu I was using was from [GitHub Actions's `ubuntu-latest`](https://github.com/actions/virtual-environments#available-environments), which is 20.04. And I can confirm that the latest `gnupg` version there is 2.2.19.

**Comment by joshrabinowitz** [comment]
@FanchenBao above you're saying `ubuntu-latest` installs 2.2.19; in your original text about this (above) you said `apt-get install gnupg points to version 2.2.20`.

But I'm more concerned with this overall gnupg interoperability issue that surfaces occasionally. 

@sobolevn , do you think that we should specifically recommend that people use "matching" versions of gnupg, like perhaps all `2.2.*` or `2.3.*` ?

**Comment by sobolevn** [comment]
Maybe we can even get `gnupg` version that was used for encryption and warn user that their version does not match it?

**Comment by FanchenBao** [comment]
@joshrabinowitz In the doc, I was referring to the most up-to-date Ubuntu, which has `gnupg` version 2.2.20. I was trying to be more general, not specific to the case of GitHub Actions. Apparently the `ubuntu-latest` used by GitHub Actions is not the most up-to-date Ubuntu.

@sobolevn I think that is a great idea, as it will produce clear error message when decryption fails due to the mismatch of `gnupg` version.

**Comment by sobolevn** [comment]
I have no idea if this is actually possible 🤔

**Comment by sobolevn** [comment]
But, even if it is not possible we can write `VERSION` file with `gpg` version.

**Comment by FanchenBao** [comment]
Yes, that will work. I think we can update the `VERSION` file each time user run `git secret hide`, and verify against `VERSION` each time user run `git secret cat` or `git secret reveal`.

**Comment by sobolevn** [comment]
@FanchenBao do you want to give this a spin? 🙂 
PR is very welcome!

**Comment by FanchenBao** [comment]
Sure thing

**Comment by dkonopka** [comment]
This is something really needed, because in terms of users with macOS, and CI/CI on Ubuntu there is no way to configure git-secret properly with different versions of gpg.. :(

**Comment by joshrabinowitz** [comment]
See 
https://packages.ubuntu.com/search?keywords=gnupg
and
https://formulae.brew.sh/formula/gnupg

**Comment by dkonopka** [comment]
@joshrabinowitz its tricky thing, because installing git-secret via brew, then installing gnupg@2.2 it's not working for me (even older version installed, git-secret is using a newer one) or maybe I don't know how to do it properly :)

**Comment by joshrabinowitz** [comment]
@dkonopka can you please try uninstalling git-secret and gnupg using brew, then installing gnupg at the desired version from brew, then installing git-secret from brew too? Please let us know if this installs the expected versions and works. 

I appreciate this report and feedback, I haven't had a chance to try this on an osx/brew system yet. Thank you!

**Comment by joshrabinowitz** [comment]
Hm you didn't show uninstalling the latest version of gnupg. Are you sure it wasn't still lingering around?

Also look at the env var that lets you specify a particular path to gpg (I forget the var name right now sorry)

**Comment by dkonopka** [comment]
@joshrabinowitz edited my previous comment, I just properly reinstalled gpg, by adding brew cleanup :)

**Comment by joshrabinowitz** [comment]
So this is resolved for you? Looks like you're getting 2.2.xx version of gnupg

**Comment by dkonopka** [comment]
@joshrabinowitz yup, it is finally working for me (however versions are a bit different):

MacOS (dev environment):
```
gpg --version

gpg (GnuPG/MacGPG2) 2.2.34
libgcrypt 1.8.9
```

Ubuntu (ci environment)
```
gpg --version

Tigpg (GnuPG) 2.2.19
libgcrypt 1.8.5
```

**Comment by joshrabinowitz** [comment]
* it is confirmed that at this point the default Ubuntu and Brew packages of gnupg do not interoperate well, 
* we have documented the issue and how to install matching versions in the docs. 
* We also moved suggested code changes to track the versions of gnupg used to #893
