### ISSUE TITLE
Unable to install using rpm

### ISSUE THREAD

**Issue by nmilcoff** [sobolevn/git-secret#767]
What are the steps to reproduce this issue?
-------------------------------------------
1. Try installing package via rpm, as instructions mention: `wget https://raw.githubusercontent.com/sobolevn/git-secret/master/utils/rpm/git-secret.repo -O git-secret-rpm.repo`

What happens?
-------------
…
Installation will fail with a 403 Forbidden error, when trying to access https://gitsecret.jfrog.io/ui/native/git-secret-rpm/rpm/git-secret-0.4.0-1.noarch.rpm

I suspect this has something to do with this change: https://github.com/sobolevn/git-secret/commit/7db41789eae828338ba76e64adc1d9ebb6fd4924

What were you expecting to happen?
----------------------------------
Installation should succeed.

Any logs, error output, etc?
----------------------------
> Downloading packages:
>
> https://gitsecret.jfrog.io/artifactory/git-secret-rpm/rpm/git-secret-0.4.0-1.noarch.rpm: [Errno 14] HTTPS Error 403 - Forbidden

Any other comments?
-------------------
This is blocking :)

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …

**`git-secret` path:** (`which git-secret`) …

**`git-secret` version:** (`git secret --version`) …

**`git` version:** (`git --version`) …

**Shell type and version:** (`$SHELL --version`) …

**`gpg` version:** (`gpg --version`) …

**Comment by sobolevn** [comment]
@nmilcoff are you using Centos? If so, looks like it is deprecated. Our Fedora `rpm` build works just fine.

**Comment by nmilcoff** [comment]
I'm using Alpine (also I must admint I'm not an expert in linux). Could this be a jfrog issue otherwise? 

This is what I have in my yml:

> wget https://raw.githubusercontent.com/sobolevn/git-secret/master/utils/rpm/git-secret.repo -O git-secret-rpm.repo

**Comment by sobolevn** [comment]
If you are using Alpine, you should use `.apk`, not `.rpm`.

Our Alpine release CI passes: https://github.com/sobolevn/git-secret/runs/5073459202?check_suite_focus=true

But, it was failing indeed. Maybe some server probelms. Please, report back if you have any problems in the future!

**Comment by nmilcoff** [comment]
Unfortunately I can't in the Alpine version we use. However I definitely think it was something jfrog related, it started working again later that day.

Thanks a lot for your quick replies, and for this amazing tool!
