### ISSUE TITLE
[question] How "risky" is it to use the "-m" argument with "git secret hide"?

### ISSUE THREAD

**Issue by bperel** [sobolevn/git-secret#795]
The [git-secret hide documentation](https://git-secret.io/git-secret-hide) states that if using `git-secret -m`:

> it’s possible to create a state where the users in the output of git secret whoknows may not be able to decrypt the some files in the repo, or may be able decrypt files they’re not supposed to be able to.

What does the documentation mean about "it’s possible to create a state"? Does it mean as a malicious user? I would like to know how risky it is to use `git-secret hide -m`, as currently it's a bit annoying that all files are re-encrypted each time `git-secret hide` is run: if I forget to exclude these files from my commit, the git history will say that they have changed, even though they haven't.

**Comment by joshrabinowitz** [comment]
If you don't encrypt all the hidden files when you use `hide`, _and you've added or removed keys from your git-secret repo's keychain_, then you can have some hidden files that are decryptable by a different set of users than others. Consider this scenario:

1) start new git-secret repo
2) add one user's (userX) public key to git-secret repo's keychain using `tell`
3) add one file (A.txt) to be encypted using `add`
4) encrypt the file using `hide`
5) add another user's (userY) public key to the git-secret repo's keychain using `tell`
6) add a second file (B.txt) to be encrypted with `add`
7) use `hide -m` to encrypt the second file, but not re-encrypt the first 

now you have a situation A.txt.secret can only be decrypted by userX, but B.txt can be decrypted by userX or userY.

Now imagine modifying this example by pretending two users were added in step 2, and one (userY) was removed in step 5. 
Then A.txt.secret can be decrypted by userX or userY, but B.txt.secret can only be decrypted by userX.
You can also extend this example with more users and more secret files and you can see how you can get to a situation where it's hard to tell who can decrypt which secrets.

Making `hide` re-encrypt all hidden files ensures that the hidden files can all be decrypted by the same set of users.

**Comment by joshrabinowitz** [comment]
Also in the case you're showing, the second _encrypted file_ will have changed (encrypted) contents, even if the unencrypted version has not, because git doesn't track the unencrypted files -- which is the whole point of git-secret.

**Comment by bperel** [comment]
Thank you very much for this explanation, appreciated.
If I understand what you wrote correctly, it's reasonable to hide with `-m` when the following conditions are fulfilled within a commit:
- Secret files are neither added nor removed, only modified
- No git-secret user is being added or removed

Is that correct?

**Comment by bperel** [comment]
Thanks a lot :-)
