### ISSUE TITLE
Git secret changes not showing changes

### ISSUE THREAD

**Issue by msilvestre** [sobolevn/git-secret#80]
What are the steps to reproduce this issue?
-------------------------------------------
1. create a file (echo "123" > file_to_hide)
2. add it to .gitignore
3. add it to git secret (git secret add)
4. hide file
5. reveal file
6. add something to file (echo "435" >> file_to_hide)
7. call git secret changes 

What happens?
-------------
Git secret changes shows all file instead of only the change:
changes in file_to_hide:
<
---
> 123
> 435

What were you expecting to happen?
----------------------------------
Only the changes:
changes in file_to_hide:
<
---
> 435

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
I installed it using brew install git-secret.
Using the previous one 0.2.1 the issue does not happens.

What versions of software are you using?
----------------------------------------
**Operating system:** 
Mac OS

**`git-secret` version:**
0.2.2

**Shell type and version:**
zsh 5.0.8 (x86_64-apple-darwin15.0)

**Comment by sobolevn** [comment]
I guess it may be a feature of the `diff` I am using underneath.
In my case it was like that:

> (flask_sql) [22:40:51] sobolev :: Mackbook-Nikita  ➜  Work/tcehpython/code ‹master*› » echo 'flask' >> requirements.txt
> (flask_sql) [22:41:06] sobolev :: Mackbook-Nikita  ➜  Work/tcehpython/code ‹master*› » git secret changes
> 
> You need a passphrase to unlock the secret key for
> user: "Nikita Sobolev (keybase) <mail@sobolevn.me>"
> 2048-bit RSA key, ID 3F5E2521, created 2016-03-18 (main key ID 8AE3C73E)
> 
> changes in requirements.txt: 1c1,5
> < 
> ---
> appdirs==1.4.0
> packaging==16.8
> pyparsing==2.1.10
> six==1.10.0
> flask
>

**Comment by sobolevn** [comment]
So, I found this option:

> -I RE  --ignore-matching-lines=RE
>               Ignore changes whose lines all match RE.

It may fix this problem. Could you please test this option? Does it suite your needs?

**Comment by msilvestre** [comment]
Great! Thanks for the following up. 
There was really something fishy, from 0.2.1 to 0.2.2
