### ISSUE TITLE
403 Errors when attempting to download git-secret from gitsecret.jfrog.io

### ISSUE THREAD

**Issue by kevholmes** [sobolevn/git-secret#801]
What are the steps to reproduce this issue?
-------------------------------------------
1. Attempt to download .deb package from Artifactory at <https://gitsecret.jfrog.io/ui/native/git-secret-deb/>

What happens?
-------------
```
{
  "errors": [
    {
      "status": 403,
      "message": "Artifact download request rejected: git-secret_0.4.0_all.deb was not downloaded due to the download blocking policy configured in Xray for git-secret-deb. Xray is unavailable."
    }
  ]
}
```

What were you expecting to happen?
----------------------------------
A 200-level OK and a .deb package.

Any logs, error output, etc?
----------------------------
Nothing beyond the 403 error coming back from Artifactory.

Any other comments?
-------------------
When I've set Artifactory + Xray up for clients in the past, there is an option to block downloads if a package doesn't pass the Xray scan. It looks like the Xray scanning engine isn't available so downloads of packages are being blocked entirely.

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …

**`git-secret` path:** (`which git-secret`) …

**`git-secret` version:** (`git secret --version`) …

**`git` version:** (`git --version`) …

**Shell type and version:** (`$SHELL --version`) …

**`gpg` version:** (`gpg --version`) …

**Comment by joshrabinowitz** [comment]
resolved as per #802
