### ISSUE TITLE
Can't make a git secret repository

### ISSUE THREAD

**Issue by haleyk** [sobolevn/git-secret#81]
What are the steps to reproduce this issue?
-------------------------------------------
First, I downloaded gpg, made an RSA key pair. Then, I ran git secret init, which said "git appears to be broken. Try git init" so I used git init and then git secret init, which seemed to worked fine. 
Then,
In terminal:
1. git secret init
2. git secret tell email@email.email

What happens?
-------------
"/usr/local/bin/git-secret: line 655: gpg: command not found
cleaning up...
fatal: 'secret' appears to be a git command, but we were not
able to execute it. Maybe git-secret is broken?"

What were you expecting to happen?
----------------------------------
To be invited to the git repository as a contributor (I'm just setting it up). 

Any logs, error output, etc?
----------------------------
See above

Any other comments?
-------------------
Because it says gpg command not found I assume that the issue is somehow related to that, but I followed the directions on http://git-secret.io/ exactly so I'm not sure if I missed something. 

What versions of software are you using?
----------------------------------------
**Operating system:** macOS Sierra v10.12.3

**`git-secret` version:** unsure

**Shell type and version:** bash-3.2.57(1)

**Comment by sobolevn** [comment]
Thanks for the detailed report! What version of `gpg` do you have? You can check that by `gpg --version`.

And also, could you please show me the output of `which git-secret`. Thanks!

**Comment by haleyk** [comment]
I just re-installed GPG Suite and the error is no longer occurring; I must have done something wrong the first time. Thank you for your time!
