### ISSUE TITLE
reconsider directions about adding other users to git-secret repo

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#813]
In 
https://github.com/sobolevn/git-secret/blob/master/man/man7/git-secret.7.md#usage-adding-someone-to-a-repository-using-git-secret 
we say:

#### Usage: Adding someone to a repository using git-secret
* Get their gpg public-key
* Import this key into your gpg keyring (in ~/.gnupg or similar) by running gpg --import KEY_NAME.txt
* (more steps follow)

Is this good advice? Should we also be telling them to remove that user's public key from their keyring as the final step?

This issue relates to #699

**Comment by sobolevn** [comment]
I think importing public keys is fine **if** you remove it afterwards!
Very good catch! 👍
