### ISSUE TITLE
Revoked key seen as duplicate when trying to add user to tell list

### ISSUE THREAD

**Issue by cjoster** [sobolevn/git-secret#857]
When enumerating keys, revoked keys should be skipped unless forced in some other manner. Since you can only search for keys by email, there is no way to uniquely specify the non-revoked key.

What are the steps to reproduce this issue?
-------------------------------------------
1. Have an old revoked key with your email address.

```
[user@host project]$ gpg --list-keys user@example.com
pub   rsa4096 2015-02-21 [C] [revoked: 2018-03-27]
      670F526AC7BFB4E961C32190427706E974D3BBD7
uid           [ revoked] CJ Oster <user@example.com>

pub   rsa4096 2018-03-27 [C]
      EDBC09F1083B1EB2C2AE67908813B1013F3212DB
uid           [  full  ] CJ Oster <user@example.com>
sub   rsa4096 2018-03-27 [S]
sub   rsa4096 2018-03-27 [E]
sub   rsa4096 2018-03-27 [A]
```

2. Attempt to `git secret tell`

```
[user@host project]$ git secret tell user@example.com
<snip>
git-secret: abort: 2 keys found in gpg user keyring for: user@example.com
```

What happens?
-------------
The script aborts with the error "abort: 2 keys found in gpg user keyring for: user@example.com" and exits with error code 1.

What were you expecting to happen?
----------------------------------
The non-revoked key should be accepted and the revoked key be ignored.

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) Linux hostname 5.16.12-200.fc35.x86_64 #1 SMP PREEMPT Wed Mar 2 19:06:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`) /usr/bin/git secret

**`git-secret` version:** (`git secret --version`) 0.4.0

**`git` version:** (`git --version`) git version 2.35.1

**Shell type and version:** (`$SHELL --version`) GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)

**`gpg` version:** (`gpg --version`) gpg (GnuPG) 2.3.4, libgcrypt 1.9.4-unknown

**Comment by cjoster** [comment]
Please don't merge yet. This results in revoked keys getting added to the keyring, which isn't the end of the world but I'd like it to be cleaner.

**Comment by joshrabinowitz** [comment]
Closing, this is (mostly) a dup of #268
