### ISSUE TITLE
Managing use across multiple machines (one user, multiple GPG keys with same email)

### ISSUE THREAD

**Issue by damienbutt** [sobolevn/git-secret#862]
Hi all,

I have just started using git-secret and have come up against a slight issue I am not sure how to solve.

I have set up git-secret on one machine, added my key, added secrets and hidden secrets etc... all worked as expected.

Using a different machine, I wanted to pull down the repo and access the secrets. I have GPG set up on the other machine. I tried to add myself from that machine but got an error stating that a key with the specified email already exists. 

I am one user, but I have multiple machines that I move between. My git credentials are obviously the same on each machine and my GPG keys on each machine are all using the same email.  

How can I use git-secret in this situation? Am I missing something? I would have thought this would be a fairly common situation to be in.

Thanks,

D

What versions of software are you using?
----------------------------------------
**Operating system:** (`Darwin db-macbook-pro 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64`) …

**`git-secret` path:** (`/usr/local/bin/git-secret`) …

**`git-secret` version:** (`0.4.0`) …

**`git` version:** (`git version 2.36.0`) …

**Shell type and version:** (`zsh 5.8 (x86_64-apple-darwin21.0)`) …

**`gpg` version:** (`gpg (GnuPG/MacGPG2) 2.2.34`) …

**Comment by joshrabinowitz** [comment]
Hello and thank you for your note.

The design of git-secret assumes each email address is associated with one gnupg key. There are plans to allow keys to be specified by fingerprint, please see #268. If you have the ability to help us move towards this goal, your contributions are welcome!

As of now you'll need to make sure each unique key is associated with a unique email address for use with git-secret

**Comment by joshrabinowitz** [comment]
Closing as dup of #268
