### ISSUE TITLE
Linux deb repo no longer signed

### ISSUE THREAD

**Issue by hakgul** [sobolevn/git-secret#89]
I am having troubles with the bintray repository for git-secret. Originally noticed when the Linux Mint Update Manager was acting up and indicating a problem. Upon trying to update apt-get sources I got an error about the git-secret repo, details below.

What are the steps to reproduce this issue?
-------------------------------------------
1. open terminal
2. run sudo apt-get update

What happens?
-------------
package manager attempts to refresh the source list, but gets a 404 on the Release gpg

What were you expecting to happen?
----------------------------------
was expecting sources to be updated

Any logs, error output, etc?
----------------------------
Err:14 https://dl.bintray.com/sobolevn/deb git-secret Release.gpg
  404  Not Found
E: The repository 'https://dl.bintray.com/sobolevn/deb git-secret Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Any other comments?
-------------------
In an attempt to resolve the issue, I removed the git-secret repo from sources.list, removed the Authentication Key for it and added them back using the commands from the installation instructions on the git-secret webpage. Still getting the same error afterwards unfortunately

What versions of software are you using?
----------------------------------------
**Operating system:** Linux Mint 18

**`git-secret` version:** 0.2.1

**Shell type and version:** GNU bash, version 4.3.42(1)-release

**Comment by sobolevn** [comment]
Thanks for the report! Will fix this soon.

**Comment by hakgul** [comment]
Excellent! Great tool by the way :)

**Comment by vtermanis** [comment]
Hi @sobolevn - any idea when approximately this might be addressed?

**Comment by sobolevn** [comment]
Will try to fix this today.

**Comment by vtermanis** [comment]
Thank you very much!

**Comment by sobolevn** [comment]
@vtermanis  Could you please check this right now?

It did not work:
> root@9d5a6d22c4dd:/# apt-get update
> Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
> Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
> Get:3 http://archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
> Ign:4 https://dl.bintray.com/sobolevn/deb git-secret InRelease
> Get:5 https://dl.bintray.com/sobolevn/deb git-secret Release [2672 B]
> Hit:5 https://dl.bintray.com/sobolevn/deb git-secret Release
> Ign:6 https://dl.bintray.com/sobolevn/deb git-secret Release.gpg
> Fetched 204 kB in 3s (60.7 kB/s)
> Reading package lists... Done
> W: The repository 'https://dl.bintray.com/sobolevn/deb git-secret Release' is not signed.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

Right now it looks like that:
> root@9d5a6d22c4dd:/# apt-get update
> Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
> Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
> Get:3 http://archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
> Ign:4 https://dl.bintray.com/sobolevn/deb git-secret InRelease
> Get:5 https://dl.bintray.com/sobolevn/deb git-secret Release [2672 B]
> Get:6 https://dl.bintray.com/sobolevn/deb git-secret Release.gpg [475 B]
> Fetched 207 kB in 3s (55.7 kB/s)
> Reading package lists... Done

Solved with:

```
POST /calc_metadata/sobolevn/deb/ HTTP/1.1
Host: api.bintray.com
Authorization: Basic my-auth
X-GPG-PASSPHRASE: my-gpg-pass
Cache-Control: no-cache
```

**Comment by vtermanis** [comment]
It works, thank you. :+1:

**Comment by sobolevn** [comment]
Reopened, since I want to automate this API call.
