### ISSUE TITLE
Documentation tweak regarding checked-in status of  .gitsecrets

### ISSUE THREAD

**Issue by liz-mars** [sobolevn/git-secret#93]
Thanks so much for git secret. I love everything except one thing. 

You stipulate that .git-secret should not be ignored, but it's not clear from the documentation if it should be checked in. I've checked it in in my repos, but that also means checking in a file containing a randseed, which makes me uncomfortable. Could you clarify this in the docs?

**Comment by sobolevn** [comment]
Thanks for your feedback!

I have never thought about ignoring `randomseed`. Should it be secure? 
I guess I have to google some material about it.

**Comment by sobolevn** [comment]
Starting some test with ignoring `randomseed`: https://github.com/sobolevn/git-secret-test-randomseed

**Comment by sobolevn** [comment]
Indeed, it it not required to be in the repository. So, I will point that out.

**Comment by hurricanehrndz** [comment]
@sobolevn and @liz-mars,

Randomseed is not automatically added to gitignore when git-secret is initialized. Documentation will be added to clarify workflow.
