### ISSUE TITLE
Can't set SECRETS_DIR

### ISSUE THREAD

**Issue by kmkacpermajor** [sobolevn/git-secret#933]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install git-secret through apt
2. Pull git repository with different .gitsecret directory
3. Try modifing SECRETS_DIR (with or without export)
4. Use any git-secret command

What happens?
-------------
Error appears: .gitsecret does not exist. abort.

What were you expecting to happen?
----------------------------------
Was expecting it to use set SECRETS_DIR env var

Any logs, error output, etc?
----------------------------
.gitsecret does not exist. abort.

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`)
Linux C11-0TSB9YF4WZN 4.4.0-22000-Microsoft #653-Microsoft Wed Apr 27 16:06:00 PST 2022 x86_64 x86_64 x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`) 
/usr/bin/git-secret

**`git-secret` version:** (`git secret --version`) 
0.2.2

**`git` version:** (`git --version`) 
git version 2.25.1

**Shell type and version:** (`$SHELL --version`)
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**`gpg` version:** (`gpg --version`) 
gpg (GnuPG) 2.2.19
libgcrypt 1.8.5

**Comment by sobolevn** [comment]
Hi! The version you are using is quite outdated. Right now the last version is `0.5.0` 
Can you please update your version and check that the error is gone?

**Comment by kmkacpermajor** [comment]
Error is gone, everything is working as expected. Thanks
