### ISSUE TITLE
When building a CI/CD environment with  `Bitrise` by Swift, what is the ideal way to set up an `email` address and `password`?

### ISSUE THREAD

**Issue by keisukeYamagishi** [sobolevn/git-secret#939]
What happens?
-------------
When building a CI/CD environment with  `Bitrise` by Swift, what is the ideal way to set up an `email` address and `password`?

What were you expecting to happen?
----------------------------------
We thought it would be easy to build an environment.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …　Mac OSX

**`git-secret` path:** (`which git-secret`) … 

**`git-secret` version:** (`git secret --version`) … all version

**`git` version:** (`git --version`) … all version

**Shell type and version:** (`$SHELL --version`) … bash

**`gpg` version:** (`gpg --version`) … all version

**Comment by joshrabinowitz** [comment]
Hello @keisukeYamagishi 

I am not famiiar with Bitrise by Swift, but there are instructions for using git-secret with at least one CI/CD system. 
What have you tried with Bitrise, and what went wrong?
Have you seen the CI/CD docs at https://git-secret.io/#commands ?

**Comment by keisukeYamagishi** [comment]
@joshrabinowitz 
Thank you for response
I want to dencrypted an encrypted file, but I feel like I need to add my password and bitrise email address to git-secret to do it?
If so, which email address should I use in Bitrise?
Also, is it possible to use another user's settings as they are?
We would appreciate it if you could also tell us.

**Comment by keisukeYamagishi** [comment]
Please tell me CI/CD page URL

**Comment by keisukeYamagishi** [comment]
@joshrabinowitz 

regarding bellow descreption

> Create an env var on your CI/CD server GPG_PRIVATE_KEY and assign it the private key value. If a passphrase has been setup for the private key, create another env var on the CI/CD server GPG_PASSPHRASE and assign it the passphrase of the private key.

What value should I pass?
どのような値を渡すべきですか？
説明を願います。

**Comment by keisukeYamagishi** [comment]
I would like to export a private key using the following command, but I would like to know how to pass the password as an argument.
```bash
gpg --armor --export-secret-key user@example.com
```
