### ISSUE TITLE
Doesn't work in CentOS7:  error: unknown option `no-index', .gitsecret folder is ignored. abort.

### ISSUE THREAD

**Issue by akonon** [sobolevn/git-secret#94]
I have a repo on Ubuntu 16.04 and git secret works well there. When installed it on CentOS7, whatever command I try, I keep getting:
```
error: unknown option `no-index'
usage: git check-ignore [options] pathname...
   or: git check-ignore [options] --stdin < <list-of-paths>

    -q, --quiet           suppress progress reporting
    -v, --verbose         be verbose

    --stdin               read file names from stdin
    -z                    input paths are terminated by a null character

.gitsecret folder is ignored. abort.
```
I can't even `git secret init` in a new repo there. The same error occurs.

What versions of software are you using?
----------------------------------------
**Operating system:**
```
$ hostnamectl 
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.10.2.el7.x86_64
      Architecture: x86-64
```
**`git-secret` path:**
```
$ which git-secret
/usr/bin/git-secret
```
**`git-secret` version:**
```
$ git secret --version
0.2.2
```
**Shell type and version:**
```
$SHELL --version
GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
```
**`gpg` version:**
```
$ gpg --version
gpg (GnuPG) 2.0.22
libgcrypt 1.5.3
```

**Comment by sobolevn** [comment]
What's your `git` version, please?

**Comment by akonon** [comment]
```
$ git --version
git version 1.8.3.1
```

**Comment by sobolevn** [comment]
Thanks. I have figured out, that `--no-index` is supported since `git 2.0`.

I guess, I should clarify the minimal supporting `git` version. 
So, your version is not supported, sorry.

As a solution you can update your `git`.
Feel free to reopen if needed.

**Comment by sobolevn** [comment]
Related https://github.com/sobolevn/git-secret/issues/96
