### ISSUE TITLE
random_seed not generated with git secret init

### ISSUE THREAD

**Issue by garrettmaring** [sobolevn/git-secret#962]
What are the steps to reproduce this issue?
-------------------------------------------
`git secret init` in an existing git repository

What happens?
-------------
`.gitsecret` is created but there is no `random_seed` file

What were you expecting to happen?
---------------------------------
a `random_seed` file

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
M1 Apple MacBook Pro, Venture, is `brew` to install git-secret

**Operating system:** (`uname -a`) …
`Darwin MYMBP Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64`

**`git-secret` path:** (`which git-secret`) …
/opt/homebrew/bin/git-secret

**`git-secret` version:** (`git secret --version`) …
0.5.0

**`git` version:** (`git --version`) …
git version 2.37.1 (Apple Git-137.1)

**Shell type and version:** (`$SHELL --version`) …
zsh 5.8.1 (x86_64-apple-darwin22.0)

**`gpg` version:** (`gpg --version`) …
```
gpg (GnuPG) 2.3.8
libgcrypt 1.10.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/g/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
AEAD: EAX, OCB
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by garrettmaring** [comment]
It appeared after subsequently making data secret with the `add` and `hide` commands

**Comment by sobolevn** [comment]
You can add a code comment / doc line about it if you wish :)
