### ISSUE TITLE
Doesn't finish the process of asking for a password to reveal

### ISSUE THREAD

**Issue by akonon** [sobolevn/git-secret#97]
Updated git as you advised in the other issue and now it works, almost)
```
$ git secret reveal

Необходима фраза-пароль для доступа к секретному ключу пользователя: "My name<mail@domain.com>"
2048-бит RSA ключ, ID 21F07EFE, создан 2017-04-13 (главный ключ ID 529D6BF9)



```
And then there is no invitation like it's in Ubuntu: `Введите фразу-пароль: `
Any text I type in looks like regular visible text. Pressing Enter doesn't help.
Have to use Ctrl+C to stop it. 

When I use `gpg -o file -d file.secret` to decrypt a file, `git secret reveal` works for a short time (maybe 15 mins) without asking for the password.

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) …
```
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.10.1.el7.x86_64
      Architecture: x86-64
```

**`git-secret` path:** (`which git-secret`) …
```
/usr/bin/git-secret
```

**`git-secret` version:** (`git secret --version`) …
```
0.2.2
```

**Shell type and version:** (`$SHELL --version`) …
```
GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
```

**`gpg` version:** (`gpg --version`) …
```
gpg (GnuPG) 2.0.22
libgcrypt 1.5.3
```

**`git` version:** (`git --version`) ...
```
git version 2.12.2
```

**Comment by sobolevn** [comment]
Thanks for the report! Could you please try to encrypt and decrypt any file using raw `gpg`?
Will it even work?

**Comment by akonon** [comment]
Yes, raw `gpg` encrypts and decrypts without any problems.

**Comment by sobolevn** [comment]
Ok, I will dig into it.

**Comment by akonon** [comment]
I've just noticed that every attempt to `git secret reveal` starts a process `/usr/bin/pinentry-curses`  which loads CPU on 100% until I kill it manually.

**Comment by sobolevn** [comment]
`pinentry` is used by `gpg-agent`. Is it properly configured?

**Comment by akonon** [comment]
I didn't configure it.. didn't know I have to. 
After raw `gpg` decryption, while `gpg-agent` is still in the list of processes, `git secret reveal` works without generating pinentries. So it can reveal files after I used `gpg` first and for a limited period of time when my password is in memory.

**Comment by sobolevn** [comment]
Could you please try this https://ask.fedoraproject.org/en/question/32052/gpg2-problem-with-the-agent-no-pinentry/

Will it help?

**Comment by akonon** [comment]
Unfortunately none of the answers there helped. With `~/.gnupg/gpg-agent.conf` the behaviour is the same, my $DISPLAY is empty and I don't do it as sudo.
Don't know if it is helpful info, but I installed git from source and used `./configure --prefix=/usr --with-curl` not `--prefix=/usr/local` as it was in the tutorial (otherwise git commands didn't work).

**Comment by sobolevn** [comment]
That's surely is an issue with `gpg` and `pinentry`. I guess it is not related to `git`.
I will try to create a `docker` image to reproduce this issue.

**Comment by avra911** [comment]
Hello,

Same issue here in Mac OS and `gpg (GnuPG) 2.1.20`, `libgcrypt 1.7.6`.

**Comment by sobolevn** [comment]
@avra911 do you have `gpg-agent` configured?

**Comment by avra911** [comment]
@sobolevn I am able to run `gpg -o file -d file.secret`. Is there any specific configuration?

```
$gpg-agent
gpg-agent[33974]: gpg-agent running and available
```
