### ISSUE TITLE
question: When will 0.2.3 be released?

### ISSUE THREAD

**Issue by msilvestre** [sobolevn/git-secret#98]
Just to know, if you have any estimation on it.

Thank you

**Comment by sobolevn** [comment]
Thanks for your interest! I am pretty busy with the offline work right now. This month is totally occupied.

I would highly appreciate any contributions resolving these issues: https://github.com/sobolevn/git-secret/milestone/4

Also @aymericbeaumet was ready to help.

**Comment by ilovezfs** [comment]
@sobolevn is 0.2.3 actually released now? I can't tell because

https://github.com/sobolevn/git-secret/releases

lists an 0.2.3 tag but

https://github.com/sobolevn/git-secret/releases/latest

still says 0.2.2.

**Comment by sobolevn** [comment]
@ilovezfs yeap, feel free to use it.

**Comment by ilovezfs** [comment]
@sobolevn excellent. Do you mind designating it as an actual release on https://github.com/sobolevn/git-secret/releases? I'd prefer not to have a discrepancy between the tag and the latest release in Homebrew.

**Comment by ctavan** [comment]
@sobolevn thanks a lot for the release! Would you mind publishing a 0.2.3 debian package as well?

**Comment by joshrabinowitz** [comment]
Looks like the 0.2.3 release happened, along with the debian package:

https://packages.debian.org/sid/git-secret

Should this get close?

**Comment by sobolevn** [comment]
Related #137 
Released a long time ago.
